# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""GCP Dataform transformation engine — generates Dataform SQLX files from FLUID contracts."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ..base import (
    GenerationResult,
    Severity,
    TransformationEngine,
    TransformationIntent,
    ValidationIssue,
)
from ..registry import register_engine

try:
    from fluid_build.util.contract import get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")


_SQLX_HEADER = "-- Generated by fluid generate — do not edit manually.\n-- Regenerate with: fluid generate\n\n"


def _build_column_list(exposes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Extract column definitions from exposes for skeleton generation."""
    columns: List[Dict[str, str]] = []
    for expose in exposes:
        schema = expose.get("schema") or expose.get("columns") or {}
        if isinstance(schema, list):
            for col in schema:
                columns.append({
                    "name": col.get("name", "unknown"),
                    "type": col.get("type", "string"),
                })
        elif isinstance(schema, dict):
            for col_name, col_def in schema.items():
                col_type = col_def if isinstance(col_def, str) else col_def.get("type", "string")
                columns.append({"name": col_name, "type": col_type})
    return columns


def _generate_project_config(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> str:
    """Generate a dataform.json project configuration."""
    contract_name = contract.get("name", "fluid-dataform-project")
    props = build.get("properties", {})

    config = {
        "defaultSchema": props.get("dataset", "analytics"),
        "assertionSchema": props.get("assertionSchema", "dataform_assertions"),
        "warehouse": "bigquery",
        "defaultDatabase": props.get("project", "my-gcp-project"),
        "defaultLocation": props.get("location", "US"),
        "_comment": "TODO: Update GCP project, dataset, and location settings",
    }

    return json.dumps(config, indent=2) + "\n"


def _generate_sqlx_model(
    expose: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> str:
    """Generate a single Dataform SQLX file for an expose."""
    expose_id = get_expose_id(expose) or "output"
    schema = expose.get("schema") or expose.get("columns") or {}
    props = build.get("properties", {})

    # Use embedded SQL from build properties if available (embedded-logic pattern)
    embedded_sql = props.get("sql", "")

    # Build column list for documentation
    columns: List[Dict[str, str]] = []
    if isinstance(schema, list):
        for col in schema:
            columns.append({
                "name": col.get("name", "unknown"),
                "type": col.get("type", "string"),
                "description": col.get("description", ""),
            })
    elif isinstance(schema, dict):
        for col_name, col_def in schema.items():
            if isinstance(col_def, str):
                columns.append({"name": col_name, "type": col_def, "description": ""})
            else:
                columns.append({
                    "name": col_name,
                    "type": col_def.get("type", "string"),
                    "description": col_def.get("description", ""),
                })

    lines = [_SQLX_HEADER]

    # SQLX config block
    lines.append("config {")
    lines.append(f'  type: "table",')
    lines.append(f'  schema: "{props.get("dataset", "analytics")}",')
    lines.append(f'  description: "Generated model for {expose_id}",')
    if columns:
        lines.append("  columns: {")
        for col in columns:
            desc = col["description"] or f"{col['name']} column"
            lines.append(f'    {col["name"]}: "{desc}",')
        lines.append("  },")
    lines.append("  assertions: {")
    lines.append("    nonNull: [")
    if columns:
        # Add non-null assertion for first column as example
        lines.append(f'      "{columns[0]["name"]}",')
    lines.append("      // TODO: Add non-null assertions for required columns")
    lines.append("    ],")
    lines.append("    uniqueKey: [")
    lines.append("      // TODO: Add unique key columns")
    lines.append("    ],")
    lines.append("  },")
    lines.append("}\n")

    # SQL body
    if embedded_sql:
        lines.append(embedded_sql)
    else:
        lines.append(f"-- TODO: Implement transformation logic for '{expose_id}'")
        lines.append("SELECT")
        if columns:
            col_lines = []
            for col in columns:
                col_lines.append(f"  CAST(NULL AS {_bq_type(col['type'])}) AS {col['name']}")
            lines.append(",\n".join(col_lines))
        else:
            lines.append("  -- TODO: Add column selections")
            lines.append("  *")
        lines.append("FROM")
        lines.append("  ${ref(\"source_table\")}  -- TODO: Replace with actual source reference")

    lines.append("")
    return "\n".join(lines)


def _bq_type(fluid_type: str) -> str:
    """Map common FLUID types to BigQuery SQL types."""
    mapping = {
        "string": "STRING",
        "integer": "INT64",
        "int": "INT64",
        "float": "FLOAT64",
        "double": "FLOAT64",
        "boolean": "BOOL",
        "date": "DATE",
        "timestamp": "TIMESTAMP",
        "datetime": "DATETIME",
        "numeric": "NUMERIC",
        "decimal": "NUMERIC",
    }
    return mapping.get(fluid_type.lower(), "STRING")


def _generate_multi_stage_sqlx(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate SQLX files for multi-stage pattern using transformation intent stages."""
    files: GenerationResult = {}

    if transformation_intent and transformation_intent.stages:
        for stage in transformation_intent.stages:
            stage_name = stage.get("name", "stage")
            sql = stage.get("sql", f"-- TODO: Implement stage '{stage_name}'")
            layer = stage.get("layer", "staging")
            path = f"definitions/{layer}/{stage_name}.sqlx"

            lines = [_SQLX_HEADER]
            lines.append("config {")
            lines.append(f'  type: "view",')
            lines.append(f'  description: "Stage: {stage_name}",')
            lines.append("}\n")
            lines.append(sql)
            lines.append("")
            files[path] = "\n".join(lines)
    else:
        # Fallback: generate stubs from exposes
        exposes = get_exposes(contract)
        for expose in exposes:
            expose_id = get_expose_id(expose) or "output"
            path = f"definitions/staging/stg_{expose_id}.sqlx"
            lines = [_SQLX_HEADER]
            lines.append("config {")
            lines.append(f'  type: "view",')
            lines.append(f'  description: "Staging for {expose_id}",')
            lines.append("}\n")
            lines.append(f"-- TODO: Implement staging transformation for '{expose_id}'")
            lines.append("SELECT *")
            lines.append('FROM ${ref("source_table")}  -- TODO: Replace with actual source')
            lines.append("")
            files[path] = "\n".join(lines)

    return files


@register_engine
class DataformEngine(TransformationEngine):
    """Generates GCP Dataform SQLX files from a FLUID contract."""

    name = "dataform"
    supported_patterns = ("hybrid-reference", "embedded-logic", "multi-stage")
    supported_platforms = ("gcp",)

    def generate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
        *,
        build_index: int = 0,
        schema_context: Optional[Dict[str, Any]] = None,
        transformation_intent: Optional[TransformationIntent] = None,
    ) -> GenerationResult:
        files: GenerationResult = {}
        pattern = build.get("pattern", "hybrid-reference")

        # dataform.json project configuration
        files["dataform.json"] = _generate_project_config(contract, build)

        if pattern == "multi-stage":
            files.update(_generate_multi_stage_sqlx(
                contract, build, transformation_intent=transformation_intent,
            ))
        else:
            # Generate one SQLX file per expose
            exposes = get_exposes(contract)
            if exposes:
                for expose in exposes:
                    expose_id = get_expose_id(expose) or "output"
                    path = f"definitions/{expose_id}.sqlx"
                    files[path] = _generate_sqlx_model(
                        expose, build, transformation_intent=transformation_intent,
                    )
            else:
                # No exposes — generate a single placeholder
                files["definitions/output.sqlx"] = _generate_sqlx_model(
                    {}, build, transformation_intent=transformation_intent,
                )

        return files

    def validate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
    ) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []

        engine = build.get("engine") or build.get("type")
        if engine and engine != "dataform":
            issues.append(ValidationIssue(
                message=f"Engine '{engine}' is not 'dataform'",
                severity=Severity.ERROR,
                field="builds[].engine",
            ))

        pattern = build.get("pattern", "hybrid-reference")
        if pattern not in self.supported_patterns:
            issues.append(ValidationIssue(
                message=f"Pattern '{pattern}' is not supported by the dataform engine",
                severity=Severity.WARNING,
                field="builds[].pattern",
            ))

        exposes = get_exposes(contract)
        if not exposes:
            issues.append(ValidationIssue(
                message="Contract has no exposes[] — dataform needs at least one output to generate models",
                severity=Severity.WARNING,
                field="exposes",
            ))

        return issues
