# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dbt SQL model files from FLUID contract builds."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..base import GenerationResult, TransformationIntent

_HEADER = "-- Generated by fluid generate — do not edit manually.\n-- Regenerate with: fluid generate\n\n"

try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def generate_models(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate SQL model files for a dbt project."""
    pattern = build.get("pattern", "hybrid-reference")

    if pattern == "multi-stage":
        return _generate_multi_stage(contract, build, transformation_intent=transformation_intent)
    elif pattern == "embedded-logic":
        return _generate_embedded(contract, build)
    else:
        # hybrid-reference: generate from AI intent or skeleton
        return _generate_hybrid(
            contract, build,
            schema_context=schema_context,
            transformation_intent=transformation_intent,
        )


# ---------------------------------------------------------------------------
# Hybrid-reference pattern
# ---------------------------------------------------------------------------


def _generate_hybrid(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    files: GenerationResult = {}

    if transformation_intent and transformation_intent.stages:
        return _generate_from_intent(contract, transformation_intent)

    # No AI intent — generate skeletons from consumes + exposes
    consumes = contract.get("consumes", [])
    exposes = get_exposes(contract)

    # Staging models: one per consume
    for consume in consumes:
        if not isinstance(consume, dict):
            continue
        source_id = consume.get("exposeId") or consume.get("id") or "source"
        model_name = f"stg_{source_id}"
        files[f"models/staging/{model_name}.sql"] = _staging_skeleton(source_id)

    # Mart models: one per expose
    for expose in exposes:
        expose_id = get_expose_id(expose) or "output"
        schema_cols = _extract_schema_columns(expose)
        staging_refs = [f"stg_{c.get('exposeId') or c.get('id', 'source')}" for c in consumes if isinstance(c, dict)]
        files[f"models/marts/{expose_id}.sql"] = _mart_skeleton(expose_id, schema_cols, staging_refs)

    return files


def _staging_skeleton(source_id: str) -> str:
    """Generate a staging model skeleton."""
    return (
        f"{_HEADER}"
        f"{{{{ config(materialized='view') }}}}\n\n"
        f"select\n"
        f"    *\n"
        f"    -- TODO: Add column cleaning and standardization\n\n"
        f"from {{{{ source('raw', '{source_id}') }}}}\n"
    )


def _mart_skeleton(
    expose_id: str,
    schema_cols: List[Dict[str, str]],
    staging_refs: List[str],
) -> str:
    """Generate a mart model skeleton."""
    lines = [_HEADER, "{{ config(materialized='table') }}\n\n"]

    if schema_cols:
        lines.append("select\n")
        col_lines = []
        for col in schema_cols:
            col_lines.append(f"    cast(null as {_sql_type(col.get('type', 'string'))}) as {col['name']}")
        lines.append(",\n".join(col_lines))
        lines.append("\n\n")
    else:
        lines.append("select\n    *\n    -- TODO: Define output columns\n\n")

    if staging_refs:
        lines.append(f"from {{{{ ref('{staging_refs[0]}') }}}}\n")
        for ref_name in staging_refs[1:]:
            lines.append(f"-- TODO: join {{ ref('{ref_name}') }}\n")
    else:
        lines.append("-- TODO: Add source references\nfrom dual\n")

    lines.append("\n-- TODO: Add transformation logic (joins, aggregations, filters)\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Embedded-logic pattern
# ---------------------------------------------------------------------------


def _generate_embedded(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Wrap embedded SQL with dbt config macro."""
    properties = build.get("properties", {})
    sql = properties.get("sql", "")
    if not sql:
        return {}

    model_name = build.get("id", "main")
    content = (
        f"{_HEADER}"
        f"{{{{ config(materialized='table') }}}}\n\n"
        f"{sql.strip()}\n"
    )
    return {f"models/marts/{model_name}.sql": content}


# ---------------------------------------------------------------------------
# Multi-stage pattern
# ---------------------------------------------------------------------------


def _generate_multi_stage(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate models from multi-stage build definition."""
    files: GenerationResult = {}
    properties = build.get("properties", {})
    stages = properties.get("stages", [])

    for stage in stages:
        if not isinstance(stage, dict):
            continue

        name = stage.get("name", "unnamed")
        stage_sql = stage.get("properties", {}).get("sql", "")
        depends_on = stage.get("dependsOn", [])
        layer = _infer_layer(name)
        materialization = _layer_materialization(layer)

        if stage_sql:
            # Wrap user SQL with config macro
            content = (
                f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"{stage_sql.strip()}\n"
            )
        else:
            # Skeleton with refs to dependencies
            ref_lines = "".join(
                f"-- depends on: {{{{ ref('{dep}') }}}}\n" for dep in depends_on
            )
            content = (
                f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"{ref_lines}"
                f"select\n"
                f"    *\n"
                f"    -- TODO: Add transformation logic for stage '{name}'\n\n"
                f"from {{{{ ref('{depends_on[0]}') }}}}\n" if depends_on else
                f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"select\n"
                f"    *\n"
                f"    -- TODO: Add transformation logic for stage '{name}'\n\n"
                f"-- TODO: Add source references\n"
            )

        files[f"models/{layer}/{name}.sql"] = content

    return files


# ---------------------------------------------------------------------------
# AI-intent-driven generation
# ---------------------------------------------------------------------------


def _generate_from_intent(
    contract: Dict[str, Any],
    intent: TransformationIntent,
) -> GenerationResult:
    """Generate full models from AI-produced TransformationIntent."""
    files: GenerationResult = {}

    for stage in intent.stages:
        name = stage.get("name", "unnamed")
        sql = stage.get("sql", "")
        layer = stage.get("layer", _infer_layer(name))
        materialization = _layer_materialization(layer)

        content = (
            f"{_HEADER}"
            f"{{{{ config(materialized='{materialization}') }}}}\n\n"
            f"{sql.strip()}\n" if sql else
            f"{_HEADER}"
            f"{{{{ config(materialized='{materialization}') }}}}\n\n"
            f"-- TODO: AI could not generate SQL for stage '{name}'\n"
            f"select 1\n"
        )
        files[f"models/{layer}/{name}.sql"] = content

    return files


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _infer_layer(stage_name: str) -> str:
    """Infer dbt model layer from stage name."""
    lower = stage_name.lower()
    if any(token in lower for token in ("stg_", "staging", "extract", "raw")):
        return "staging"
    if any(token in lower for token in ("int_", "intermediate", "prep")):
        return "intermediate"
    return "marts"


def _layer_materialization(layer: str) -> str:
    """Default materialization for a layer."""
    return {"staging": "view", "intermediate": "view", "marts": "table"}.get(layer, "table")


def _extract_schema_columns(expose: Dict[str, Any]) -> List[Dict[str, str]]:
    """Extract column definitions from an expose's contract.schema."""
    contract_section = get_expose_contract(expose) or {}
    schema = contract_section.get("schema", [])
    if isinstance(schema, list):
        return [{"name": col["name"], "type": col.get("type", "string")}
                for col in schema if isinstance(col, dict) and col.get("name")]
    return []


def _sql_type(fluid_type: str) -> str:
    """Map FLUID type to SQL type for skeleton casts."""
    mapping = {
        "string": "varchar",
        "STRING": "varchar",
        "integer": "integer",
        "INTEGER": "integer",
        "number": "numeric",
        "NUMBER": "numeric",
        "float": "numeric",
        "FLOAT": "numeric",
        "boolean": "boolean",
        "BOOLEAN": "boolean",
        "date": "date",
        "DATE": "date",
        "timestamp": "timestamp",
        "TIMESTAMP": "timestamp",
        "datetime": "timestamp",
        "array": "varchar",  # fallback
        "object": "varchar",  # fallback
    }
    return mapping.get(fluid_type, "varchar")
