# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``profiles.yml`` template based on target platform."""

from __future__ import annotations

from typing import Any, Dict, Optional

import yaml

from .project_yml import _sanitize_project_name

_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n#\n# Fill in the placeholder values or use dbt env_var() for secrets.\n\n"


def generate_profiles(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> Optional[str]:
    """Generate ``profiles.yml`` template content."""
    contract_id = contract.get("id", "fluid_project")
    profile_name = _sanitize_project_name(contract_id)

    execution = build.get("execution", {})
    runtime = execution.get("runtime", {})
    platform = runtime.get("platform", "local")

    profile = _profile_for_platform(platform, profile_name)
    if not profile:
        return None

    return _HEADER + yaml.dump(profile, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _profile_for_platform(platform: str, profile_name: str) -> Dict[str, Any]:
    """Build a profiles.yml dict for the given platform."""
    lower = platform.lower()

    if lower in ("gcp", "bigquery"):
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "bigquery",
                        "method": "oauth",
                        "project": "{{ env_var('GCP_PROJECT') }}",
                        "dataset": "analytics_dev",
                        "threads": 4,
                        "location": "US",
                    },
                    "prod": {
                        "type": "bigquery",
                        "method": "oauth",
                        "project": "{{ env_var('GCP_PROJECT') }}",
                        "dataset": "analytics",
                        "threads": 8,
                        "location": "US",
                    },
                },
            }
        }

    if lower in ("snowflake",):
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "snowflake",
                        "account": "{{ env_var('SNOWFLAKE_ACCOUNT') }}",
                        "user": "{{ env_var('SNOWFLAKE_USER') }}",
                        "password": "{{ env_var('SNOWFLAKE_PASSWORD') }}",
                        "role": "TRANSFORMER",
                        "database": "ANALYTICS",
                        "warehouse": "TRANSFORM_WH",
                        "schema": "DEV",
                        "threads": 4,
                    },
                },
            }
        }

    if lower in ("aws", "redshift"):
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "redshift",
                        "host": "{{ env_var('REDSHIFT_HOST') }}",
                        "user": "{{ env_var('REDSHIFT_USER') }}",
                        "password": "{{ env_var('REDSHIFT_PASSWORD') }}",
                        "port": 5439,
                        "dbname": "analytics",
                        "schema": "dev",
                        "threads": 4,
                    },
                },
            }
        }

    # Default: local / DuckDB
    return {
        profile_name: {
            "target": "dev",
            "outputs": {
                "dev": {
                    "type": "duckdb",
                    "path": "target/dev.duckdb",
                    "threads": 4,
                },
            },
        }
    }
