# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``dbt_project.yml`` from a FLUID contract."""

from __future__ import annotations

import re
from typing import Any, Dict

import yaml

_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"


def _sanitize_project_name(contract_id: str) -> str:
    """Convert a FLUID contract ID to a valid dbt project name."""
    # Take the last segment of dotted IDs (e.g. "gold.analytics.customer_360_v1" → "customer_360_v1")
    parts = contract_id.split(".")
    name = parts[-1] if parts else contract_id
    # Replace non-alphanumeric (except underscores) with underscores
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # Strip leading digits/underscores
    name = re.sub(r"^[^a-zA-Z]+", "", name)
    return name or "fluid_project"


def generate_project_yml(contract: Dict[str, Any], build: Dict[str, Any]) -> str:
    """Generate ``dbt_project.yml`` content."""
    contract_id = contract.get("id", "fluid_project")
    project_name = _sanitize_project_name(contract_id)
    properties = build.get("properties", {})

    # Materializations per layer
    materializations = properties.get("materializations", {})
    staging_mat = materializations.get("staging", "view")
    intermediate_mat = materializations.get("intermediate", "view")
    marts_mat = materializations.get("marts", "table")

    data: Dict[str, Any] = {
        "name": project_name,
        "version": "1.0.0",
        "config-version": 2,
        "profile": project_name,
        "model-paths": ["models"],
        "analysis-paths": ["analyses"],
        "test-paths": ["tests"],
        "seed-paths": ["seeds"],
        "macro-paths": ["macros"],
        "snapshot-paths": ["snapshots"],
        "target-path": "target",
        "clean-targets": ["target", "dbt_packages"],
        "models": {
            project_name: {
                "staging": {"+materialized": staging_mat},
                "intermediate": {"+materialized": intermediate_mat},
                "marts": {"+materialized": marts_mat},
            },
        },
    }

    # Variables from contract
    dbt_vars = properties.get("vars")
    if dbt_vars and isinstance(dbt_vars, dict):
        data["vars"] = dbt_vars

    return _HEADER + yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
