# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``schema.yml`` (dbt tests) from ``exposes[].contract.dq``."""

from __future__ import annotations

from typing import Any, Dict, List

import yaml

from ..base import GenerationResult

_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"

try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def generate_schema_yml(contract: Dict[str, Any]) -> GenerationResult:
    """Generate ``schema.yml`` files with dbt tests from DQ rules.

    Returns one ``schema.yml`` per layer where models have DQ rules.
    """
    exposes = get_exposes(contract)
    if not exposes:
        return {}

    # All mart models go into a single schema.yml for now
    model_defs: List[Dict[str, Any]] = []

    for expose in exposes:
        if not isinstance(expose, dict):
            continue
        expose_id = get_expose_id(expose)
        if not expose_id:
            continue

        contract_section = get_expose_contract(expose) or {}
        schema_cols = contract_section.get("schema", [])
        dq = contract_section.get("dq", {})
        dq_rules = dq.get("rules", []) if isinstance(dq, dict) else []

        columns = _build_column_tests(schema_cols, dq_rules)
        if not columns and not schema_cols:
            continue

        model_def: Dict[str, Any] = {"name": expose_id}

        desc = expose.get("description")
        if desc:
            model_def["description"] = desc

        if columns:
            model_def["columns"] = columns

        model_defs.append(model_def)

    if not model_defs:
        return {}

    data = {"version": 2, "models": model_defs}
    content = _HEADER + yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return {"models/marts/schema.yml": content}


def _build_column_tests(
    schema_cols: List[Dict[str, Any]],
    dq_rules: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Build dbt column test definitions from schema + DQ rules."""
    # Index DQ rules by selector (column name)
    rules_by_col: Dict[str, List[Dict[str, Any]]] = {}
    for rule in dq_rules:
        if not isinstance(rule, dict):
            continue
        selector = rule.get("selector", "")
        if selector:
            rules_by_col.setdefault(selector, []).append(rule)

    columns: List[Dict[str, Any]] = []
    seen_cols = set()

    for col in schema_cols:
        if not isinstance(col, dict):
            continue
        col_name = col.get("name")
        if not col_name:
            continue
        seen_cols.add(col_name)

        tests = _tests_for_column(col, rules_by_col.get(col_name, []))
        col_entry: Dict[str, Any] = {"name": col_name}
        if col.get("description"):
            col_entry["description"] = col["description"]
        if tests:
            col_entry["tests"] = tests
        columns.append(col_entry)

    # DQ rules on columns not in schema
    for col_name, rules in rules_by_col.items():
        if col_name in seen_cols:
            continue
        tests = _tests_for_column({}, rules)
        if tests:
            columns.append({"name": col_name, "tests": tests})

    return columns


def _tests_for_column(
    col_def: Dict[str, Any],
    dq_rules: List[Dict[str, Any]],
) -> List[Any]:
    """Map FLUID DQ rules + column required flag to dbt tests."""
    tests: List[Any] = []
    has_not_null = False
    has_unique = False

    # From schema required flag
    if col_def.get("required"):
        tests.append("not_null")
        has_not_null = True

    for rule in dq_rules:
        rule_type = rule.get("type", "")

        if rule_type == "completeness" and not has_not_null:
            tests.append("not_null")
            has_not_null = True

        elif rule_type == "uniqueness" and not has_unique:
            tests.append("unique")
            has_unique = True

        elif rule_type == "valid_values":
            values = rule.get("parameters", {}).get("values", [])
            if values:
                tests.append({"accepted_values": {"values": values}})

        elif rule_type == "accuracy":
            # Range tests require dbt_utils package.  When available,
            # uncomment the accepted_range test below.
            threshold = rule.get("threshold")
            operator = rule.get("operator", ">=")
            if threshold is not None:
                range_test: Dict[str, Any] = {}
                if operator in (">=", ">"):
                    range_test["min_value"] = threshold
                elif operator in ("<=", "<"):
                    range_test["max_value"] = threshold
                if range_test:
                    # Requires: packages.yml with dbt-labs/dbt_utils
                    tests.append({"dbt_utils.accepted_range": range_test})

    return tests
