# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``models/sources.yml`` from ``consumes[]``."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import yaml

_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"

try:
    from fluid_build.util.contract import consumes_to_canonical_ports
except ImportError:  # pragma: no cover
    def consumes_to_canonical_ports(contract, **_kw):
        return [
            {"id": c.get("exposeId") or c.get("id", "unknown"), "name": c.get("name", "")}
            for c in contract.get("consumes", [])
            if isinstance(c, dict)
        ]


def generate_sources(
    contract: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
) -> Optional[str]:
    """Generate ``sources.yml`` content from contract consumes.

    Returns ``None`` if the contract has no consumes.
    """
    consumes = contract.get("consumes", [])
    if not consumes:
        return None

    canonical = consumes_to_canonical_ports(contract)
    if not canonical:
        return None

    # Build dbt source tables
    tables: List[Dict[str, Any]] = []
    for port in canonical:
        table_name = port["id"]
        table_entry: Dict[str, Any] = {
            "name": table_name,
        }
        if port.get("description"):
            table_entry["description"] = port["description"]

        # Add columns from schema_context (discovered sample schemas)
        columns = _columns_for_source(table_name, schema_context)
        if columns:
            table_entry["columns"] = columns

        tables.append(table_entry)

    source_def: Dict[str, Any] = {
        "version": 2,
        "sources": [
            {
                "name": "raw",
                "description": "Source data consumed by this data product",
                "tables": tables,
            }
        ],
    }

    return _HEADER + yaml.dump(source_def, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _columns_for_source(
    table_name: str,
    schema_context: Optional[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Extract column definitions from schema_context for a source table."""
    if not schema_context:
        return []

    # schema_context maps file/table names to their schemas
    # Try exact match first, then partial match
    schemas = schema_context.get("schemas", {})
    table_schema = schemas.get(table_name)
    if not table_schema:
        # Try matching by file name pattern (e.g., "customers" matches "customers.csv")
        for key, schema in schemas.items():
            base = key.rsplit(".", 1)[0] if "." in key else key
            if base == table_name or base.replace("-", "_") == table_name:
                table_schema = schema
                break

    if not table_schema or not isinstance(table_schema, dict):
        return []

    columns_map = table_schema.get("columns", {})
    if not isinstance(columns_map, dict):
        return []

    columns: List[Dict[str, Any]] = []
    for col_name, col_type in columns_map.items():
        col_entry: Dict[str, Any] = {"name": col_name}
        # Add not_null test for columns that look like identifiers
        if col_name.endswith("_id") or col_name == "id":
            col_entry["tests"] = ["unique", "not_null"]
        columns.append(col_entry)

    return columns
