# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""AWS Glue transformation engine — generates PySpark ETL job scripts from FLUID contracts."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from ..base import (
    GenerationResult,
    Severity,
    TransformationEngine,
    TransformationIntent,
    ValidationIssue,
)
from ..registry import register_engine

try:
    from fluid_build.util.contract import get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")


_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"


def _build_column_list(exposes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Extract column definitions from exposes for skeleton generation."""
    columns: List[Dict[str, str]] = []
    for expose in exposes:
        schema = expose.get("schema") or expose.get("columns") or {}
        if isinstance(schema, list):
            for col in schema:
                columns.append({
                    "name": col.get("name", "unknown"),
                    "type": col.get("type", "string"),
                })
        elif isinstance(schema, dict):
            for col_name, col_def in schema.items():
                col_type = col_def if isinstance(col_def, str) else col_def.get("type", "string")
                columns.append({"name": col_name, "type": col_type})
    return columns


def _generate_glue_job(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> str:
    """Generate a PySpark Glue ETL job script."""
    exposes = get_exposes(contract)
    expose_id = get_expose_id(exposes[0]) if exposes else "output"
    columns = _build_column_list(exposes)

    # Use embedded SQL from build properties if available (embedded-logic pattern)
    embedded_sql = ""
    props = build.get("properties", {})
    if props.get("sql"):
        embedded_sql = props["sql"]

    col_comments = ""
    if columns:
        col_comments = "\n".join(
            f"#   - {c['name']} ({c['type']})" for c in columns
        )
        col_comments = f"# Target columns:\n{col_comments}\n"

    lines = [
        _HEADER,
        "import sys\n",
        "from awsglue.context import GlueContext",
        "from awsglue.job import Job",
        "from awsglue.transforms import *",
        "from awsglue.utils import getResolvedOptions",
        "from pyspark.context import SparkContext\n\n",
        "# ── Glue job boilerplate ──────────────────────────────────────────\n",
        "args = getResolvedOptions(sys.argv, ['JOB_NAME'])",
        "sc = SparkContext()",
        "glue_ctx = GlueContext(sc)",
        "spark = glue_ctx.spark_session",
        "job = Job(glue_ctx)",
        "job.init(args['JOB_NAME'], args)\n\n",
    ]

    if col_comments:
        lines.append(col_comments)

    lines.append(f"# ── Extract ───────────────────────────────────────────────────────\n")
    lines.append(f"# TODO: Replace with your Glue Data Catalog source database/table")
    lines.append(f'source_dyf = glue_ctx.create_dynamic_frame.from_catalog(')
    lines.append(f'    database="my_database",')
    lines.append(f'    table_name="my_source_table",')
    lines.append(f')\n\n')

    lines.append(f"# ── Transform ─────────────────────────────────────────────────────\n")
    if embedded_sql:
        lines.append(f"# Embedded SQL from contract build properties:")
        lines.append(f"# {embedded_sql[:200]}{'...' if len(embedded_sql) > 200 else ''}")
        lines.append(f'source_dyf.toDF().createOrReplaceTempView("source")')
        lines.append(f'result_df = spark.sql("""\n{embedded_sql}\n""")')
        lines.append(f"from awsglue.dynamicframe import DynamicFrame")
        lines.append(f'result_dyf = DynamicFrame.fromDF(result_df, glue_ctx, "{expose_id}")\n\n')
    else:
        lines.append(f"# TODO: Implement transformation logic for '{expose_id}'")
        lines.append(f'result_dyf = ApplyMapping.apply(')
        lines.append(f"    frame=source_dyf,")
        lines.append(f"    mappings=[")
        if columns:
            for c in columns:
                lines.append(f'        ("{c["name"]}", "string", "{c["name"]}", "{c["type"]}"),')
        else:
            lines.append(f'        # TODO: Add column mappings — ("src_col", "src_type", "dst_col", "dst_type")')
        lines.append(f"    ],")
        lines.append(f")\n\n")

    lines.append(f"# ── Load ──────────────────────────────────────────────────────────\n")
    lines.append(f"# TODO: Configure your target sink (S3, Redshift, etc.)")
    lines.append(f'glue_ctx.write_dynamic_frame.from_options(')
    lines.append(f'    frame=result_dyf,')
    lines.append(f'    connection_type="s3",')
    lines.append(f"    connection_options={{")
    lines.append(f'        "path": "s3://my-bucket/{expose_id}/",')
    lines.append(f"    }},")
    lines.append(f'    format="parquet",')
    lines.append(f')\n\n')
    lines.append(f"job.commit()\n")

    return "\n".join(lines)


def _generate_glue_config(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> str:
    """Generate a Glue job configuration JSON."""
    exposes = get_exposes(contract)
    expose_id = get_expose_id(exposes[0]) if exposes else "output"
    contract_name = contract.get("name", "fluid-glue-job")

    config = {
        "jobName": f"{contract_name}-{expose_id}",
        "role": "arn:aws:iam::ACCOUNT_ID:role/GlueServiceRole",
        "command": {
            "name": "glueetl",
            "scriptLocation": f"s3://my-bucket/scripts/glue_job.py",
            "pythonVersion": "3",
        },
        "defaultArguments": {
            "--job-language": "python",
            "--TempDir": "s3://my-bucket/temp/",
            "--enable-metrics": "",
            "--enable-continuous-cloudwatch-log": "true",
        },
        "maxRetries": 1,
        "timeout": 120,
        "workerType": "G.1X",
        "numberOfWorkers": 2,
        "_comment": "TODO: Update role ARN, S3 paths, and worker configuration",
    }

    return json.dumps(config, indent=2) + "\n"


@register_engine
class GlueEngine(TransformationEngine):
    """Generates AWS Glue PySpark ETL job scripts from a FLUID contract."""

    name = "glue"
    supported_patterns = ("hybrid-reference", "embedded-logic")
    supported_platforms = ("aws",)

    def generate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
        *,
        build_index: int = 0,
        schema_context: Optional[Dict[str, Any]] = None,
        transformation_intent: Optional[TransformationIntent] = None,
    ) -> GenerationResult:
        files: GenerationResult = {}

        files["glue_job.py"] = _generate_glue_job(
            contract, build, transformation_intent=transformation_intent,
        )
        files["glue_job_config.json"] = _generate_glue_config(contract, build)

        return files

    def validate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
    ) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []

        engine = build.get("engine") or build.get("type")
        if engine and engine != "glue":
            issues.append(ValidationIssue(
                message=f"Engine '{engine}' is not 'glue'",
                severity=Severity.ERROR,
                field="builds[].engine",
            ))

        pattern = build.get("pattern", "hybrid-reference")
        if pattern not in self.supported_patterns:
            issues.append(ValidationIssue(
                message=f"Pattern '{pattern}' is not supported by the glue engine",
                severity=Severity.WARNING,
                field="builds[].pattern",
            ))

        exposes = get_exposes(contract)
        if not exposes:
            issues.append(ValidationIssue(
                message="Contract has no exposes[] — glue needs at least one output to generate jobs",
                severity=Severity.WARNING,
                field="exposes",
            ))

        return issues
