# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Dagster Pipeline Generation for Snowflake Provider.

Generates Python pipeline code from FLUID contracts for Dagster with Snowflake.
"""

from datetime import datetime
from typing import Any, Dict, List


def generate_dagster_pipeline(
    contract: Dict[str, Any], account: str, database: str, warehouse: str = "COMPUTE_WH"
) -> str:
    """Generate Dagster pipeline from FLUID contract."""
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    code = _generate_header(contract_id, contract_name, account, database, warehouse)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_resources(account, database, warehouse)
    code += "\n\n"
    code += _generate_ops(provider_tasks, database, warehouse)
    code += "\n\n"
    code += _generate_job(contract_id, provider_tasks, schedule, timezone)

    return code


def _generate_header(
    contract_id: str, contract_name: str, account: str, database: str, warehouse: str
) -> str:
    return f'''"""
FLUID Generated Dagster Pipeline: {contract_name}

Contract ID: {contract_id}
Snowflake Account: {account}
Database: {database}
Warehouse: {warehouse}

Auto-generated by FLUID Forge
Generated: {datetime.utcnow().isoformat()}Z
"""'''


def _generate_imports() -> str:
    return """from dagster import op, job, resource, In, Out, Nothing, ScheduleDefinition
from snowflake.connector import connect
import logging

logger = logging.getLogger(__name__)"""


def _generate_resources(account: str, database: str, warehouse: str) -> str:
    return f'''# Snowflake Resources
@resource
def snowflake_conn(context):
    """Snowflake connection resource."""
    import os
    return connect(
        account="{account}",
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        database="{database}",
        warehouse="{warehouse}",
        schema="PUBLIC"
    )'''


def _generate_ops(tasks: List[Dict[str, Any]], database: str, warehouse: str) -> str:
    ops_code = "# Pipeline Ops\n"
    for task in tasks:
        ops_code += _generate_single_op(task, database, warehouse)
        ops_code += "\n\n"
    return ops_code.rstrip()


def _generate_single_op(task: Dict[str, Any], database: str, warehouse: str) -> str:
    task_id = task.get("taskId")
    action = task.get("action", "")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])

    if depends_on:
        dep_items = ", ".join([f'"dep_{d}": In(Nothing)' for d in depends_on])
        ins_def = f"ins={{{dep_items}}}, "
    else:
        ins_def = ""

    action_parts = action.split(".")
    if len(action_parts) >= 3:
        operation = action_parts[2]

        if operation == "query" or operation == "run_query":
            sql = params.get("sql", params.get("query", "SELECT 1"))
            # Escape for Python string
            sql_escaped = sql.replace("\\", "\\\\").replace('"', '\\"')

            return f'''@op({ins_def}required_resource_keys={{"snowflake_conn"}})
def {task_id}(context):
    """Execute Snowflake query"""
    conn = context.resources.snowflake_conn
    cursor = conn.cursor()
    try:
        cursor.execute("{sql_escaped}")
        results = cursor.fetchall()
        context.log.info(f"Query executed: {{{{len(results)}}}} rows")
        return len(results)
    finally:
        cursor.close()'''

    return f'''@op({ins_def})
def {task_id}(context):
    """Generic op: {action}"""
    context.log.info(f"Action: {action}, Params: {params!r}")
    return True'''


def _generate_job(
    contract_id: str, tasks: List[Dict[str, Any]], schedule: str, timezone: str
) -> str:
    op_calls = []
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        if depends_on:
            dep_args = ", ".join([f"dep_{d}={d}_result" for d in depends_on])
            op_calls.append(f"    {task_id}_result = {task_id}({dep_args})")
        else:
            op_calls.append(f"    {task_id}_result = {task_id}()")

    op_calls_str = "\n".join(op_calls)
    job_name = _sanitize_name(contract_id)
    cron_schedule = _convert_schedule(schedule)

    return f'''# Job definition
@job(
    resource_defs={{"snowflake_conn": snowflake_conn}},
    tags={{"fluid": "auto-generated", "contract_id": "{contract_id}", "provider": "snowflake"}},
)
def {job_name}():
    """{contract_id} pipeline on Snowflake."""
{op_calls_str}

# Schedule
{job_name}_schedule = ScheduleDefinition(
    job={job_name},
    cron_schedule="{cron_schedule}",
    execution_timezone="{timezone}",
)'''


def _convert_schedule(schedule: str) -> str:
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"
    if schedule.count(" ") >= 4:
        return schedule
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    import re

    return re.sub(r"[^a-zA-Z0-9_]", "_", name)
