# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for Snowflake Provider.

Generates Python flow code from FLUID contracts for Prefect with Snowflake.
"""

from typing import Dict, Any, List
from datetime import datetime
from fluid_build.cli.console import cprint, info, success


def generate_prefect_flow(
    contract: Dict[str, Any],
    account: str,
    database: str,
    warehouse: str = "COMPUTE_WH"
) -> str:
    """Generate Prefect flow from FLUID contract."""
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")
    
    tasks = orchestration.get("tasks", [])
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]
    
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")
    
    code = _generate_header(contract_id, contract_name, account, database, warehouse)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_config(account, database, warehouse)
    code += "\n\n"
    code += _generate_tasks(provider_tasks, database, warehouse)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)
    
    return code


def _generate_header(contract_id: str, contract_name: str, account: str, database: str, warehouse: str) -> str:
    return f'''"""
FLUID Generated Prefect Flow: {contract_name}

Contract ID: {contract_id}
Snowflake Account: {account}
Database: {database}
Warehouse: {warehouse}

Auto-generated by FLUID Forge
Generated: {datetime.utcnow().isoformat()}Z
"""'''


def _generate_imports() -> str:
    return '''from prefect import flow, task
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
from snowflake.connector import connect
import logging
import os

logger = logging.getLogger(__name__)'''


def _generate_config(account: str, database: str, warehouse: str) -> str:
    return f'''# Snowflake Configuration
SNOWFLAKE_ACCOUNT = "{account}"
SNOWFLAKE_DATABASE = "{database}"
SNOWFLAKE_WAREHOUSE = "{warehouse}"
SNOWFLAKE_SCHEMA = "PUBLIC"

def get_snowflake_connection():
    """Get Snowflake connection."""
    return connect(
        account=SNOWFLAKE_ACCOUNT,
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        database=SNOWFLAKE_DATABASE,
        warehouse=SNOWFLAKE_WAREHOUSE,
        schema=SNOWFLAKE_SCHEMA
    )'''


def _generate_tasks(tasks: List[Dict[str, Any]], database: str, warehouse: str) -> str:
    tasks_code = "# Prefect Tasks\n"
    for task_spec in tasks:
        tasks_code += _generate_single_task(task_spec, database, warehouse)
        tasks_code += "\n\n"
    return tasks_code.rstrip()


def _generate_single_task(task_spec: Dict[str, Any], database: str, warehouse: str) -> str:
    task_id = task_spec.get("taskId")
    action = task_spec.get("action", "")
    params = task_spec.get("params", {})
    
    action_parts = action.split(".")
    if len(action_parts) >= 3:
        operation = action_parts[2]
        
        if operation == "query" or operation == "run_query":
            sql = params.get("sql", params.get("query", "SELECT 1"))
            # Escape for Python string
            sql_escaped = sql.replace('\\', '\\\\').replace('"', '\\"')
            
            return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=1800)
def {task_id}():
    """Execute Snowflake query"""
    conn = get_snowflake_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("{sql_escaped}")
        results = cursor.fetchall()
        logger.info(f"Query executed: {{{{len(results)}}}} rows")
        return len(results)
    finally:
        cursor.close()
        conn.close()'''
    
    return f'''@task(retries=2, retry_delay_seconds=30)
def {task_id}():
    """Generic task: {action}"""
    logger.info(f"Action: {action}, Params: {params!r}")
    return True'''


def _generate_flow(contract_id: str, contract_name: str, tasks: List[Dict[str, Any]]) -> str:
    flow_name = _sanitize_name(contract_id)
    task_executions = []
    for task in tasks:
        task_id = task.get("taskId")
        task_executions.append(f"    {task_id}_result = {task_id}()")
    
    task_exec_str = "\n".join(task_executions)
    
    return f'''# Flow definition
@flow(
    name="{flow_name}",
    description="{contract_name}",
    retries=1,
    retry_delay_seconds=60,
)
def {flow_name}_flow():
    """{contract_name} flow on Snowflake."""
{task_exec_str}
    
    logger.info("Flow completed successfully")
    return True'''


def _generate_deployment(contract_id: str, contract_name: str, schedule: str, timezone: str) -> str:
    flow_name = _sanitize_name(contract_id)
    cron_schedule = _convert_schedule(schedule)
    
    return f'''# Deployment configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name="{flow_name}-deployment",
        version="1.0",
        tags=["fluid", "auto-generated", "snowflake", "{contract_id}"],
        schedule=CronSchedule(
            cron="{cron_schedule}",
            timezone="{timezone}",
        ),
        work_queue_name="default",
    )
    
    deployment.apply()
    
    success(f"Deployment created: {{deployment.name}}")
    cprint(f"   Schedule: {cron_schedule} ({timezone})")
    cprint(f"   Run: prefect deployment run '{flow_name}_flow/{flow_name}-deployment'")'''


def _convert_schedule(schedule: str) -> str:
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"
    if schedule.count(" ") >= 4:
        return schedule
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    import re
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)
