# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the LLM-backed forge copilot runtime."""

import json
import types
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import httpx
import pytest

from fluid_build.cli.forge_copilot_runtime import (
    AnthropicProvider,
    CopilotGenerationError,
    DiscoveryReport,
    GeminiProvider,
    LlmConfig,
    OllamaProvider,
    OpenAIProvider,
    call_llm,
    discover_local_context,
    extract_json_object,
    generate_copilot_artifacts,
    _read_avro_metadata,
    _read_parquet_metadata,
    resolve_llm_config,
    sanitize_additional_files,
    validate_generated_result,
)
from fluid_build.forge.core.engine import ForgeEngine
from fluid_build.forge.core.interfaces import ComplexityLevel, GenerationContext, TemplateMetadata
from fluid_build.forge.generators.config_generator import ConfigGenerator
from fluid_build.forge.generators.contract_generator import ContractGenerator
from fluid_build.forge.generators.readme_generator import ReadmeGenerator
from fluid_build.schema_manager import ValidationResult


def _minimal_contract(provider: str = "local", engine: str = "sql") -> dict:
    properties = {"sql": "SELECT 1 AS id"}
    build = {
        "id": "main_build",
        "pattern": "embedded-logic",
        "engine": engine,
        "properties": properties,
        "execution": {
            "trigger": {"type": "manual", "iterations": 1},
            "runtime": {"platform": provider, "resources": {"cpu": "1", "memory": "2Gi"}},
        },
    }
    if engine == "python":
        build["properties"] = {"model": "src.main:build"}
        build["repository"] = "src/main.py"

    return {
        "fluidVersion": "0.7.1",
        "kind": "DataProduct",
        "id": "generated.test",
        "name": "Test Product",
        "description": "Generated by unit tests",
        "domain": "analytics",
        "metadata": {"owner": {"team": "data-team", "email": "data-team@example.com"}},
        "builds": [build],
        "exposes": [
            {
                "exposeId": "test_output",
                "kind": "table",
                "binding": {
                    "platform": provider,
                    "format": "csv",
                    "location": {"path": "runtime/out/test_output.csv"},
                },
                "contract": {"schema": [{"name": "id", "type": "integer", "required": True}]},
            }
        ],
        "quality": [
            {
                "dimension": "completeness",
                "assertion": "id IS NOT NULL",
                "severity": "error",
            }
        ],
    }


def _capability_matrix() -> dict:
    return {
        "providers": ["local", "gcp", "aws", "snowflake"],
        "templates": {
            "starter": {},
            "analytics": {},
            "etl_pipeline": {},
            "ml_pipeline": {},
            "streaming": {},
        },
    }


def _generation_context(tmp_path: Path, project_config: dict) -> GenerationContext:
    return GenerationContext(
        project_config=project_config,
        target_dir=tmp_path,
        template_metadata=TemplateMetadata(
            name="starter",
            description="Starter template",
            complexity=ComplexityLevel.BEGINNER,
            provider_support=["local", "gcp", "aws", "snowflake"],
            use_cases=["testing"],
            technologies=["python"],
            estimated_time="5 min",
            tags=["test"],
        ),
        provider_config={},
        user_selections={},
        forge_version="2.0.0",
        creation_time="2026-03-31T00:00:00Z",
    )


def _make_engine():
    with patch("fluid_build.forge.core.engine.initialize_all_registries"):
        with patch(
            "fluid_build.forge.core.engine.get_registry_status",
            return_value={"templates": {"count": 1}, "providers": {"count": 1}},
        ):
            return ForgeEngine(auto_init_registries=True)


class TestResolveLlmConfig:
    def test_cli_overrides_env_for_provider_model_and_endpoint(self):
        args = SimpleNamespace(
            llm_provider="gemini",
            llm_model="gemini-2.5-pro",
            llm_endpoint="https://gateway.example.test/v1/generate",
        )

        config = resolve_llm_config(
            args,
            environ={
                "FLUID_LLM_PROVIDER": "openai",
                "FLUID_LLM_MODEL": "gpt-4o-mini",
                "FLUID_LLM_ENDPOINT": "https://api.openai.com/v1/chat/completions",
                "FLUID_LLM_API_KEY": "generic-key",
                "GEMINI_API_KEY": "gemini-key",
            },
        )

        assert config.provider == "gemini"
        assert config.model == "gemini-2.5-pro"
        assert config.endpoint == "https://gateway.example.test/v1/generate"
        assert config.api_key == "generic-key"

    def test_prefers_generic_api_key_over_provider_specific_key(self):
        args = SimpleNamespace(llm_provider="openai", llm_model=None, llm_endpoint=None)

        config = resolve_llm_config(
            args,
            environ={
                "FLUID_LLM_API_KEY": "generic-key",
                "OPENAI_API_KEY": "provider-key",
            },
        )

        assert config.provider == "openai"
        assert config.api_key == "generic-key"

    def test_ollama_uses_default_endpoint_without_api_key(self):
        args = SimpleNamespace(llm_provider="ollama", llm_model=None, llm_endpoint=None)

        config = resolve_llm_config(
            args,
            environ={"OLLAMA_HOST": "http://localhost:11434"},
        )

        assert config.provider == "ollama"
        assert config.api_key is None
        assert config.endpoint == "http://localhost:11434/v1/chat/completions"


class TestProviderAdapters:
    @pytest.mark.parametrize(
        ("provider", "config", "expected_header", "expected_payload_key"),
        [
            (
                OpenAIProvider(),
                LlmConfig("openai", "gpt-4o-mini", "https://api.openai.com/v1/chat/completions", "key"),
                "Authorization",
                "messages",
            ),
            (
                AnthropicProvider(),
                LlmConfig(
                    "anthropic",
                    "claude-3-5-sonnet-latest",
                    "https://api.anthropic.com/v1/messages",
                    "key",
                ),
                "x-api-key",
                "messages",
            ),
            (
                GeminiProvider(),
                LlmConfig("gemini", "gemini-1.5-pro", "https://example.test/generate", "key"),
                "x-goog-api-key",
                "contents",
            ),
            (
                OllamaProvider(),
                LlmConfig("ollama", "llama3.1", "http://localhost:11434/v1/chat/completions", None),
                None,
                "messages",
            ),
        ],
    )
    def test_builtin_provider_build_request_shapes(
        self, provider, config, expected_header, expected_payload_key
    ):
        headers, payload = provider.build_request(config, "system prompt", "user prompt")

        if expected_header:
            assert expected_header in headers
        else:
            assert "Authorization" not in headers
        assert expected_payload_key in payload


class TestRuntimeHelpers:
    def test_extract_json_object_handles_fences_and_extra_text(self):
        text = 'Here you go:\n```json\n{"recommended_template":"starter"}\n```\n'
        parsed = extract_json_object(text)
        assert parsed["recommended_template"] == "starter"

    def test_sanitize_additional_files_blocks_path_traversal(self):
        sanitized = sanitize_additional_files(
            {
                "docs/notes.md": "# Notes\n",
                "../secret.txt": "blocked",
                "/tmp/absolute.md": "blocked",
                "runtime/out.bin": "blocked",
            }
        )

        assert sanitized == {"docs/notes.md": "# Notes\n"}

    def test_call_llm_wraps_http_errors(self):
        class FailingClient:
            def __init__(self, *args, **kwargs):
                pass

            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc, tb):
                return False

            def post(self, *args, **kwargs):
                raise httpx.HTTPError("boom")

        with patch("fluid_build.cli.forge_copilot_runtime.httpx.Client", FailingClient):
            with pytest.raises(CopilotGenerationError) as exc_info:
                call_llm(
                    OpenAIProvider(),
                    LlmConfig(
                        "openai",
                        "gpt-4o-mini",
                        "https://api.openai.com/v1/chat/completions",
                        "key",
                    ),
                    "system",
                    "user",
                )

        assert exc_info.value.event == "copilot_llm_request_failed"


class TestDiscovery:
    def test_discovery_payload_is_metadata_only(self, tmp_path):
        (tmp_path / "README.md").write_text(
            "# Test Project\n\nAPI token is sk-live-secret and should never be forwarded.\n",
            encoding="utf-8",
        )
        (tmp_path / "sql").mkdir()
        (tmp_path / "sql" / "model.sql").write_text(
            "select * from raw.orders join raw.customers using (customer_id)\n",
            encoding="utf-8",
        )
        (tmp_path / "samples").mkdir()
        (tmp_path / "samples" / "customers.csv").write_text(
            "id,email,active\n1,alice@example.com,true\n2,bob@example.com,false\n",
            encoding="utf-8",
        )

        report = discover_local_context(None, workspace_root=tmp_path)
        payload = report.to_prompt_payload()
        payload_text = json.dumps(payload)

        assert report.sample_files[0]["columns"] == {
            "id": "integer",
            "email": "string",
            "active": "boolean",
        }
        assert "raw.orders" in report.sql_files[0]["referenced_tables"]
        assert "alice@example.com" not in payload_text
        assert "bob@example.com" not in payload_text
        assert "sk-live-secret" not in payload_text
        assert "API token is" not in payload_text

    def test_discovery_ignores_airbyte_directories(self, tmp_path):
        source_dir = tmp_path / "airbyte" / "sources"
        connection_dir = tmp_path / "airbyte" / "connections"
        source_dir.mkdir(parents=True)
        connection_dir.mkdir(parents=True)

        (source_dir / "postgres-source.json").write_text(
            json.dumps(
                {
                    "name": "postgres-source",
                    "connectionConfiguration": {
                        "database": "warehouse",
                        "schemas": ["public"],
                        "replication_method": {"method": "CDC"},
                        "replication_slot": "slot_1",
                    },
                }
            ),
            encoding="utf-8",
        )
        (connection_dir / "warehouse-sync.json").write_text(
            json.dumps(
                {
                    "name": "warehouse-sync",
                    "scheduleType": "manual",
                    "status": "active",
                    "syncCatalog": {
                        "streams": [
                            {
                                "stream": {"name": "orders"},
                                "config": {
                                    "syncMode": "incremental",
                                    "cursorField": ["updated_at"],
                                    "primaryKey": [["id"]],
                                },
                            }
                        ]
                    },
                }
            ),
            encoding="utf-8",
        )

        report = discover_local_context(None, workspace_root=tmp_path)

        assert report.files_scanned == 0
        assert report.sample_files == []
        assert report.detected_sources == []

    def test_discovery_summarizes_parquet_metadata(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        with patch(
            "fluid_build.cli.forge_copilot_runtime._read_parquet_metadata",
            return_value={
                "columns": {"id": "integer", "created_at": "datetime"},
                "row_count": 42,
                "schema_source": "pyarrow",
            },
        ):
            report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "parquet"
        assert report.sample_files[0]["columns"] == {
            "id": "integer",
            "created_at": "datetime",
        }
        assert report.sample_files[0]["row_count"] == 42
        assert report.sample_files[0]["schema_source"] == "pyarrow"

    def test_discovery_summarizes_avro_metadata(self, tmp_path):
        sample_path = tmp_path / "events.avro"
        sample_path.write_bytes(b"Obj\x01")

        with patch(
            "fluid_build.cli.forge_copilot_runtime._read_avro_metadata",
            return_value={
                "columns": {"event_id": "string", "occurred_at": "datetime"},
                "schema_source": "fastavro",
            },
        ):
            report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "avro"
        assert report.sample_files[0]["columns"] == {
            "event_id": "string",
            "occurred_at": "datetime",
        }
        assert report.sample_files[0]["schema_source"] == "fastavro"

    def test_discovery_includes_warning_when_parquet_support_missing(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "parquet"
        assert report.sample_files[0]["columns"] == {}
        assert report.discovery_warnings
        assert "pyarrow or duckdb" in report.discovery_warnings[0]

    def test_read_parquet_metadata_with_pyarrow_module(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        class FakeField:
            def __init__(self, name, type_name):
                self.name = name
                self.type = type_name

        class FakeParquetFile:
            def __init__(self, path):
                self.schema_arrow = [
                    FakeField("id", "int64"),
                    FakeField("created_at", "timestamp[us]"),
                ]
                self.metadata = types.SimpleNamespace(num_rows=24)

        fake_parquet_module = types.SimpleNamespace(ParquetFile=FakeParquetFile)
        fake_pyarrow_module = types.ModuleType("pyarrow")
        fake_pyarrow_module.parquet = fake_parquet_module

        with patch.dict(
            "sys.modules",
            {
                "pyarrow": fake_pyarrow_module,
                "pyarrow.parquet": fake_parquet_module,
            },
        ):
            metadata = _read_parquet_metadata(sample_path)

        assert metadata["columns"] == {"id": "integer", "created_at": "datetime"}
        assert metadata["row_count"] == 24
        assert metadata["schema_source"] == "pyarrow"

    def test_read_avro_metadata_with_fastavro_module(self, tmp_path):
        sample_path = tmp_path / "events.avro"
        sample_path.write_bytes(b"Obj\x01")

        class FakeReader:
            def __init__(self, handle):
                self.writer_schema = {
                    "type": "record",
                    "name": "events",
                    "fields": [
                        {"name": "event_id", "type": "string"},
                        {
                            "name": "occurred_at",
                            "type": {"type": "long", "logicalType": "timestamp-millis"},
                        },
                    ],
                }

        fake_fastavro_module = types.SimpleNamespace(reader=FakeReader)

        with patch.dict("sys.modules", {"fastavro": fake_fastavro_module}):
            metadata = _read_avro_metadata(sample_path)

        assert metadata["columns"] == {
            "event_id": "string",
            "occurred_at": "datetime",
        }
        assert metadata["schema_source"] == "fastavro"


class TestGenerationValidation:
    @patch("fluid_build.cli.forge_copilot_runtime.FluidSchemaManager")
    def test_validate_generated_result_checks_provider_engine_compatibility(self, mock_schema_manager):
        mock_schema_manager.return_value.validate_contract.return_value = ValidationResult(
            is_valid=True, errors=[], warnings=[]
        )
        normalized = {
            "contract": _minimal_contract(provider="aws", engine="dataform"),
            "suggestions": {
                "recommended_provider": "aws",
                "recommended_template": "starter",
            },
        }

        errors, warnings = validate_generated_result(normalized, capabilities=_capability_matrix())

        assert not warnings
        assert any("not supported for provider 'aws'" in error for error in errors)

    def test_generate_copilot_artifacts_retries_and_recovers(self):
        payload = {
            "recommended_template": "starter",
            "recommended_provider": "local",
            "recommended_patterns": [],
            "architecture_suggestions": [],
            "best_practices": [],
            "technology_stack": [],
            "readme_markdown": "# Copilot Project\n",
            "contract": _minimal_contract(),
            "additional_files": {"docs/notes.md": "metadata only"},
        }

        with patch(
            "fluid_build.cli.forge_copilot_runtime.call_llm",
            side_effect=[json.dumps(payload), json.dumps(payload)],
        ) as mock_call_llm:
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                side_effect=[(["First attempt failed"], []), ([], ["Schema warning"])],
            ):
                result = generate_copilot_artifacts(
                    {"project_goal": "Copilot project", "data_sources": "CSV files"},
                    llm_config=LlmConfig(
                        provider="openai",
                        model="gpt-4o-mini",
                        endpoint="https://api.openai.com/v1/chat/completions",
                        api_key="key",
                    ),
                    discovery_report=DiscoveryReport(workspace_roots=["/tmp/project"]),
                    capability_matrix=_capability_matrix(),
                )

        assert mock_call_llm.call_count == 2
        assert len(result.attempt_reports) == 2
        assert result.attempt_reports[0].validation_errors == ["First attempt failed"]
        assert result.contract["id"] == "generated.test"
        assert result.additional_files == {"docs/notes.md": "metadata only"}

    def test_generate_copilot_artifacts_raises_after_three_failed_attempts(self):
        payload = {
            "recommended_template": "starter",
            "recommended_provider": "local",
            "readme_markdown": "# Copilot Project\n",
            "contract": _minimal_contract(),
        }

        with patch(
            "fluid_build.cli.forge_copilot_runtime.call_llm",
            side_effect=[json.dumps(payload), json.dumps(payload), json.dumps(payload)],
        ) as mock_call_llm:
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=(["Still invalid"], []),
            ):
                with pytest.raises(CopilotGenerationError) as exc_info:
                    generate_copilot_artifacts(
                        {"project_goal": "Copilot project", "data_sources": "CSV files"},
                        llm_config=LlmConfig(
                            provider="openai",
                            model="gpt-4o-mini",
                            endpoint="https://api.openai.com/v1/chat/completions",
                            api_key="key",
                        ),
                        discovery_report=DiscoveryReport(workspace_roots=["/tmp/project"]),
                        capability_matrix=_capability_matrix(),
                    )

        assert mock_call_llm.call_count == 3
        assert exc_info.value.event == "copilot_generation_failed"
        assert any("Attempt 1" in suggestion for suggestion in exc_info.value.suggestions)


class TestCopilotOverrides:
    def test_generators_use_copilot_overrides(self, tmp_path):
        project_config = {
            "name": "copilot-project",
            "template": "starter",
            "provider": "local",
            "copilot_generated_contract": _minimal_contract(),
            "copilot_generated_readme": "# Copilot Project\n",
            "copilot_generated_files": {"docs/notes.md": "metadata only"},
        }
        context = _generation_context(tmp_path, project_config)

        contract_files = ContractGenerator().generate(context)
        readme_files = ReadmeGenerator().generate(context)
        config_files = ConfigGenerator().generate(context)

        assert "contract.fluid.yaml" in contract_files
        assert "generated.test" in contract_files["contract.fluid.yaml"]
        assert readme_files == {"README.md": "# Copilot Project\n"}
        assert "requirements.txt" in config_files
        assert config_files["docs/notes.md"] == "metadata only"

    def test_engine_run_generators_writes_copilot_files(self, tmp_path):
        engine = _make_engine()
        project_config = {
            "name": "copilot-project",
            "template": "starter",
            "provider": "local",
            "copilot_generated_contract": _minimal_contract(),
            "copilot_generated_readme": "# Copilot Project\n",
            "copilot_generated_files": {"docs/notes.md": "metadata only"},
        }
        engine.project_config = project_config
        engine.generation_context = _generation_context(tmp_path, project_config)

        generators = {
            "readme": ReadmeGenerator(),
            "config": ConfigGenerator(),
        }

        with patch(
            "fluid_build.forge.core.engine.generator_registry.list_available",
            return_value=["contract", "readme", "config"],
        ):
            with patch(
                "fluid_build.forge.core.engine.generator_registry.get_dependency_order",
                side_effect=lambda names: names,
            ):
                with patch(
                    "fluid_build.forge.core.engine.generator_registry.get",
                    side_effect=lambda name: generators.get(name),
                ):
                    engine._run_generators()

        assert (tmp_path / "README.md").read_text(encoding="utf-8") == "# Copilot Project\n"
        assert (tmp_path / "docs" / "notes.md").read_text(encoding="utf-8") == "metadata only"
        assert (tmp_path / "requirements.txt").exists()
