# Copyright 2024-2026 Agentics Transformation Ltd
# Licensed under the Apache License, Version 2.0

"""Tests for fluid_build.cli.artifact_envelope."""

from __future__ import annotations

import json

import yaml

from fluid_build.cli.artifact_envelope import (
    build_envelope,
    dump_json_with_envelope,
    dump_yaml_with_envelope,
    utc_now_iso,
)
from fluid_build.cli.artifact_paths import ENVELOPE_SCHEMA_VERSION


class TestBuildEnvelope:
    def test_minimum_fields(self):
        env = build_envelope(
            kind="InitReceipt",
            command="fluid init",
            tool_version="0.7.9",
            generated_at="2026-01-01T00:00:00Z",
        )
        assert env["schema_version"] == ENVELOPE_SCHEMA_VERSION
        assert env["kind"] == "InitReceipt"
        assert env["generated_at"] == "2026-01-01T00:00:00Z"
        assert env["generated_by"] == {
            "tool": "fluid-cli",
            "version": "0.7.9",
            "command": "fluid init",
        }

    def test_defaults_generated_at_to_utc_now_iso(self):
        env = build_envelope(
            kind="InitReceipt", command="fluid init", tool_version="0.7.9"
        )
        # Must parse as an ISO string ending in Z
        assert env["generated_at"].endswith("Z")
        assert "T" in env["generated_at"]

    def test_envelope_keys_are_stable(self):
        """Reviewers should see the same four fields every time."""
        env = build_envelope(
            kind="InitReceipt",
            command="fluid init",
            tool_version="0.7.9",
            generated_at="2026-01-01T00:00:00Z",
        )
        assert set(env.keys()) == {
            "schema_version",
            "kind",
            "generated_at",
            "generated_by",
        }


class TestUtcNowIso:
    def test_ends_with_z(self):
        assert utc_now_iso().endswith("Z")

    def test_has_t_separator(self):
        assert "T" in utc_now_iso()


class TestDumpJsonWithEnvelope:
    def test_envelope_fields_come_first(self):
        text = dump_json_with_envelope(
            {"artifacts": [], "flow": "blank"},
            kind="InitReceipt",
            command="fluid init",
            tool_version="0.7.9",
            generated_at="2026-01-01T00:00:00Z",
        )
        doc = json.loads(text)
        keys = list(doc.keys())
        # Envelope keys before payload keys
        assert keys[:4] == [
            "schema_version",
            "kind",
            "generated_at",
            "generated_by",
        ]
        assert "flow" in keys
        assert "artifacts" in keys

    def test_trailing_newline(self):
        text = dump_json_with_envelope(
            {"ok": True},
            kind="InitReceipt",
            command="fluid init",
            tool_version="0.7.9",
        )
        assert text.endswith("\n")

    def test_payload_preserved(self):
        text = dump_json_with_envelope(
            {"nested": {"a": 1, "b": [2, 3]}},
            kind="ProjectMemory",
            command="fluid forge",
            tool_version="0.7.9",
            generated_at="2026-01-01T00:00:00Z",
        )
        doc = json.loads(text)
        assert doc["nested"] == {"a": 1, "b": [2, 3]}


class TestDumpYamlWithEnvelope:
    def test_envelope_at_top_of_yaml(self):
        text = dump_yaml_with_envelope(
            {"workspace": {"name": "acme"}},
            kind="WorkspaceConfig",
            command="fluid init",
            tool_version="0.7.9",
            generated_at="2026-01-01T00:00:00Z",
        )
        doc = yaml.safe_load(text)
        assert doc["schema_version"] == ENVELOPE_SCHEMA_VERSION
        assert doc["kind"] == "WorkspaceConfig"
        assert doc["workspace"] == {"name": "acme"}

    def test_header_comment_prepended(self):
        text = dump_yaml_with_envelope(
            {"workspace": {"name": "acme"}},
            kind="WorkspaceConfig",
            command="fluid init",
            tool_version="0.7.9",
            header_comment="# Generated by fluid-cli\n",
        )
        assert text.startswith("# Generated by fluid-cli\n")

    def test_no_header_by_default(self):
        text = dump_yaml_with_envelope(
            {"workspace": {"name": "acme"}},
            kind="WorkspaceConfig",
            command="fluid init",
            tool_version="0.7.9",
        )
        # No leading "#" when no header supplied
        assert not text.startswith("#")
