# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for project-scoped forge copilot memory."""

import json
from pathlib import Path
from unittest.mock import patch

from fluid_build.cli.forge_copilot_memory import (
    CopilotMemoryStore,
    CopilotProjectMemory,
    build_copilot_project_memory,
    resolve_copilot_memory_root,
    summarize_copilot_memory,
)
from fluid_build.cli.forge_copilot_runtime import (
    DiscoveryReport,
    LlmConfig,
    generate_copilot_artifacts,
    suggest_scaffold,
)


def _minimal_contract(provider: str = "local") -> dict:
    return {
        "fluidVersion": "0.7.1",
        "kind": "DataProduct",
        "id": "generated.test",
        "name": "Test Product",
        "description": "Generated by tests",
        "domain": "analytics",
        "metadata": {
            "template": "analytics",
            "owner": {"team": "data-team", "email": "data-team@example.com"},
        },
        "builds": [
            {
                "id": "main_build",
                "pattern": "embedded-logic",
                "engine": "sql",
                "properties": {"sql": "SELECT 1 AS id"},
                "execution": {
                    "trigger": {"type": "manual", "iterations": 1},
                    "runtime": {"platform": provider, "resources": {"cpu": "1", "memory": "2Gi"}},
                },
            }
        ],
        "exposes": [
            {
                "exposeId": "orders_output",
                "kind": "table",
                "binding": {
                    "platform": provider,
                    "format": "csv",
                    "location": {"path": "runtime/out/orders_output.csv"},
                },
                "contract": {
                    "schema": [
                        {"name": "id", "type": "integer", "required": True},
                        {"name": "created_at", "type": "timestamp", "required": False},
                    ]
                },
            }
        ],
        "quality": [
            {
                "dimension": "completeness",
                "assertion": "id IS NOT NULL",
                "severity": "error",
            }
        ],
    }


def _capability_matrix() -> dict:
    return {
        "providers": ["local", "gcp", "aws", "snowflake"],
        "templates": {
            "starter": {},
            "analytics": {},
            "etl_pipeline": {},
            "ml_pipeline": {},
            "streaming": {},
        },
    }


class TestCopilotMemoryStore:
    def test_save_and_load_round_trip(self, tmp_path: Path):
        store = CopilotMemoryStore(tmp_path)
        memory = build_copilot_project_memory(
            project_root=tmp_path,
            context={"domain": "analytics"},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(),
            discovery_report=DiscoveryReport(
                workspace_roots=[str(tmp_path)],
                sample_files=[
                    {
                        "path": str(tmp_path / "samples" / "customers.parquet"),
                        "format": "parquet",
                        "columns": {"id": "integer", "created_at": "datetime"},
                        "row_count": 42,
                        "schema_source": "pyarrow",
                    }
                ],
                provider_hints=["local"],
            ),
        )

        store.save(memory)
        loaded = store.load()

        assert loaded is not None
        assert store.path == tmp_path / "runtime/.state/copilot-memory.json"
        assert loaded.project_profile["provider"] == "local"
        assert loaded.conventions["schema_summaries"][0]["path"] == "samples/customers.parquet"

    def test_load_ignores_corrupt_file(self, tmp_path: Path):
        store = CopilotMemoryStore(tmp_path)
        store.path.parent.mkdir(parents=True, exist_ok=True)
        store.path.write_text("{not-json", encoding="utf-8")

        assert store.load() is None

    def test_memory_payload_excludes_absolute_home_paths_and_raw_rows(self, tmp_path: Path):
        memory = build_copilot_project_memory(
            project_root=tmp_path,
            context={},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "Bearer secret-token",
            },
            contract=_minimal_contract(),
            discovery_report={
                "provider_hints": ["local"],
                "sample_files": [
                    {
                        "path": "/Users/example/private/customers.avro",
                        "format": "avro",
                        "columns": {"customer_id": "integer", "created_at": "datetime"},
                        "schema_source": "fastavro",
                        "rows": [{"email": "alice@example.com"}],
                    }
                ],
            },
        )

        payload_text = json.dumps(memory.to_prompt_snapshot().to_prompt_payload())

        assert "alice@example.com" not in payload_text
        assert "/Users/example" not in payload_text
        assert "external/customers.avro" in payload_text
        assert "Bearer ***" in payload_text

    def test_resolve_memory_root_prefers_existing_project_file(self, tmp_path: Path):
        workspace_root = tmp_path / "workspace"
        target_root = tmp_path / "target"
        workspace_root.mkdir()
        target_root.mkdir()
        target_memory = target_root / "runtime/.state/copilot-memory.json"
        target_memory.parent.mkdir(parents=True)
        target_memory.write_text("{}", encoding="utf-8")

        resolved = resolve_copilot_memory_root(workspace_root, target_root)

        assert resolved == target_root

    def test_summarize_copilot_memory_returns_friendly_counts(self, tmp_path: Path):
        memory = build_copilot_project_memory(
            project_root=tmp_path,
            context={},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(),
            discovery_report=DiscoveryReport(
                workspace_roots=[str(tmp_path)],
                sample_files=[
                    {
                        "path": str(tmp_path / "samples" / "orders.parquet"),
                        "format": "parquet",
                        "columns": {"id": "integer"},
                        "schema_source": "pyarrow",
                    }
                ],
                provider_hints=["local"],
            ),
        )

        summary = summarize_copilot_memory(memory)

        assert summary["preferred_template"] == "analytics"
        assert summary["preferred_provider"] == "local"
        assert summary["schema_summary_count"] == 1
        assert summary["recent_outcome_count"] == 1


class TestCopilotMemoryRuntimeIntegration:
    def test_project_memory_is_included_in_prompt_payload(self, tmp_path: Path):
        memory = CopilotProjectMemory(
            schema_version=1,
            saved_at="2026-03-31T00:00:00Z",
            project_profile={
                "template": "analytics",
                "provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            conventions={
                "build_engines": ["sql"],
                "binding_platforms": ["local"],
                "binding_formats": ["csv"],
                "expose_kinds": ["table"],
                "provider_hints": ["local"],
                "source_formats": {"parquet": 1},
                "schema_summaries": [
                    {
                        "path": "samples/customers.parquet",
                        "format": "parquet",
                        "columns": {"id": "integer"},
                    }
                ],
            },
            recent_outcomes=[
                {
                    "saved_at": "2026-03-31T00:00:00Z",
                    "template": "analytics",
                    "provider": "local",
                    "domain": "analytics",
                    "owner": "data-team",
                    "build_engines": ["sql"],
                    "binding_platforms": ["local"],
                    "binding_formats": ["csv"],
                    "expose_kinds": ["table"],
                    "expose_ids": ["orders_output"],
                    "quality_dimensions": ["completeness"],
                    "source_formats": {"parquet": 1},
                }
            ],
        )
        captured = {}
        payload = {
            "recommended_template": "analytics",
            "recommended_provider": "local",
            "recommended_patterns": [],
            "architecture_suggestions": [],
            "best_practices": [],
            "technology_stack": [],
            "readme_markdown": "# Copilot Project\n",
            "contract": _minimal_contract(),
        }

        def _fake_call_llm(provider, config, system_prompt, user_prompt):
            captured["user_prompt"] = json.loads(user_prompt)
            return json.dumps(payload)

        with patch("fluid_build.cli.forge_copilot_runtime.call_llm", side_effect=_fake_call_llm):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                result = generate_copilot_artifacts(
                    {"project_goal": "Copilot project"},
                    llm_config=LlmConfig(
                        provider="openai",
                        model="gpt-4o-mini",
                        endpoint="https://api.openai.com/v1/chat/completions",
                        api_key="key",
                    ),
                    discovery_report=DiscoveryReport(workspace_roots=[str(tmp_path)]),
                    project_memory=memory.to_prompt_snapshot(),
                    capability_matrix=_capability_matrix(),
                )

        assert result.contract["id"] == "generated.test"
        assert captured["user_prompt"]["project_memory"]["preferred_provider"] == "local"
        assert captured["user_prompt"]["project_memory"]["schema_summaries"][0]["format"] == "parquet"

    def test_suggest_scaffold_uses_project_memory_after_current_context(self):
        memory = CopilotProjectMemory(
            schema_version=1,
            saved_at="2026-03-31T00:00:00Z",
            project_profile={
                "template": "analytics",
                "provider": "snowflake",
                "domain": "analytics",
                "owner": "data-team",
            },
            conventions={
                "build_engines": ["sql"],
                "binding_platforms": ["snowflake"],
                "binding_formats": ["table"],
                "expose_kinds": ["table"],
                "provider_hints": ["snowflake"],
                "source_formats": {"json": 1},
                "schema_summaries": [],
            },
            recent_outcomes=[],
        )

        template, provider = suggest_scaffold(
            context={},
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/test"]),
            capability_matrix=_capability_matrix(),
            project_memory=memory.to_prompt_snapshot(),
        )

        assert template == "analytics"
        assert provider == "snowflake"

    def test_suggest_scaffold_prefers_current_discovery_provider_over_memory(self):
        memory = CopilotProjectMemory(
            schema_version=1,
            saved_at="2026-03-31T00:00:00Z",
            project_profile={
                "template": "analytics",
                "provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            conventions={
                "build_engines": ["sql"],
                "binding_platforms": ["local"],
                "binding_formats": ["csv"],
                "expose_kinds": ["table"],
                "provider_hints": ["local"],
                "source_formats": {"csv": 1},
                "schema_summaries": [],
            },
            recent_outcomes=[],
        )

        template, provider = suggest_scaffold(
            context={},
            discovery_report=DiscoveryReport(
                workspace_roots=["/tmp/test"],
                provider_hints=["gcp"],
            ),
            capability_matrix=_capability_matrix(),
            project_memory=memory.to_prompt_snapshot(),
        )

        assert template == "analytics"
        assert provider == "gcp"
