# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the LLM-backed forge copilot runtime."""

import json
import types
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import httpx
import pytest

from fluid_build.cli.forge_copilot_discovery import (
    DiscoveryReport,
    discover_local_context,
)
from fluid_build.cli.forge_copilot_llm_providers import (
    AnthropicProvider,
    CopilotGenerationError,
    GeminiProvider,
    LlmConfig,
    OllamaProvider,
    OpenAIProvider,
    _parse_param_size,
    _resolve_api_key,
    call_llm,
    check_llm_readiness,
    clear_api_key_from_keyring,
    detect_provider_from_api_key,
    resolve_llm_config,
    resolve_model_name,
    resolve_ollama_model,
    save_api_key_to_keyring,
)
from fluid_build.cli.forge_copilot_runtime import (
    _build_scaffold_decision,
    build_capability_matrix,
    build_clarification_system_prompt,
    build_clarification_user_prompt,
    build_seed_contract,
    build_system_prompt,
    build_user_prompt,
    extract_json_object,
    generate_copilot_artifacts,
    sanitize_additional_files,
    validate_generated_result,
)
from fluid_build.cli.forge_copilot_schema_inference import (
    read_avro_metadata as _read_avro_metadata,
)
from fluid_build.cli.forge_copilot_schema_inference import (
    read_parquet_metadata as _read_parquet_metadata,
)
from fluid_build.forge.core.engine import ForgeEngine
from fluid_build.forge.core.interfaces import ComplexityLevel, GenerationContext, TemplateMetadata
from fluid_build.forge.generators.config_generator import ConfigGenerator
from fluid_build.forge.generators.contract_generator import ContractGenerator
from fluid_build.forge.generators.readme_generator import ReadmeGenerator
from fluid_build.schema_manager import FluidSchemaManager, ValidationResult


def _minimal_contract(provider: str = "local", engine: str = "sql") -> dict:
    properties = {"sql": "SELECT 1 AS id"}
    build = {
        "id": "main_build",
        "pattern": "embedded-logic",
        "engine": engine,
        "properties": properties,
        "execution": {
            "trigger": {"type": "manual", "iterations": 1},
            "runtime": {"platform": provider, "resources": {"cpu": "1", "memory": "2Gi"}},
        },
    }
    if engine == "python":
        build["properties"] = {"model": "src.main:build"}
        build["repository"] = "src/main.py"

    return {
        "fluidVersion": "0.7.2",
        "kind": "DataProduct",
        "id": "generated.test",
        "name": "Test Product",
        "description": "Generated by unit tests",
        "domain": "analytics",
        "metadata": {
            "layer": "Bronze",
            "owner": {"team": "data-team", "email": "data-team@example.com"},
        },
        "builds": [build],
        "exposes": [
            {
                "exposeId": "test_output",
                "kind": "table",
                "binding": {
                    "platform": provider,
                    "format": "csv",
                    "location": {"path": "runtime/out/test_output.csv"},
                },
                "contract": {"schema": [{"name": "id", "type": "integer", "required": True}]},
                "semantics": {
                    "name": "Test Output",
                    "description": "Semantic model for test output.",
                    "entities": [{"name": "id", "type": "primary"}],
                    "measures": [
                        {
                            "name": "id_count",
                            "agg": "count",
                            "expr": "id",
                            "description": "Count of id records.",
                        }
                    ],
                    "dimensions": [{"name": "id", "type": "categorical"}],
                    "metrics": [
                        {
                            "name": "id_count_metric",
                            "type": "simple",
                            "measure": "id_count",
                            "description": "Metric for id count.",
                        }
                    ],
                },
            }
        ],
    }


def _capability_matrix() -> dict:
    return {
        "providers": ["local", "gcp", "aws", "snowflake"],
        "templates": {
            "starter": {},
            "analytics": {},
            "etl_pipeline": {},
            "ml_pipeline": {},
            "streaming": {},
        },
    }


def _generation_context(tmp_path: Path, project_config: dict) -> GenerationContext:
    return GenerationContext(
        project_config=project_config,
        target_dir=tmp_path,
        template_metadata=TemplateMetadata(
            name="starter",
            description="Starter template",
            complexity=ComplexityLevel.BEGINNER,
            provider_support=["local", "gcp", "aws", "snowflake"],
            use_cases=["testing"],
            technologies=["python"],
            estimated_time="5 min",
            tags=["test"],
        ),
        provider_config={},
        user_selections={},
        forge_version="2.0.0",
        creation_time="2026-03-31T00:00:00Z",
    )


def _make_engine():
    with patch("fluid_build.forge.core.engine.initialize_all_registries"):
        with patch(
            "fluid_build.forge.core.engine.get_registry_status",
            return_value={"templates": {"count": 1}, "providers": {"count": 1}},
        ):
            return ForgeEngine(auto_init_registries=True)


class TestResolveLlmConfig:
    def test_cli_overrides_env_for_provider_model_and_endpoint(self):
        args = SimpleNamespace(
            llm_provider="gemini",
            llm_model="gemini-2.5-pro",
            llm_endpoint="https://gateway.example.test/v1/generate",
        )

        config = resolve_llm_config(
            args,
            environ={
                "FLUID_LLM_PROVIDER": "openai",
                "FLUID_LLM_MODEL": "gpt-4o-mini",
                "FLUID_LLM_ENDPOINT": "https://api.openai.com/v1/chat/completions",
                "FLUID_LLM_API_KEY": "generic-key",
                "GEMINI_API_KEY": "gemini-key",
            },
        )

        assert config.provider == "gemini"
        assert config.model == "gemini-2.5-pro"
        assert config.endpoint == "https://gateway.example.test/v1/generate"
        assert config.api_key == "generic-key"

    def test_prefers_generic_api_key_over_provider_specific_key(self):
        args = SimpleNamespace(llm_provider="openai", llm_model=None, llm_endpoint=None)

        config = resolve_llm_config(
            args,
            environ={
                "FLUID_LLM_API_KEY": "generic-key",
                "OPENAI_API_KEY": "provider-key",
            },
        )

        assert config.provider == "openai"
        assert config.api_key == "generic-key"

    def test_ollama_uses_default_endpoint_without_api_key(self):
        args = SimpleNamespace(llm_provider="ollama", llm_model=None, llm_endpoint=None)

        config = resolve_llm_config(
            args,
            environ={"OLLAMA_HOST": "http://localhost:11434"},
        )

        assert config.provider == "ollama"
        assert config.api_key is None
        assert config.endpoint == "http://localhost:11434/v1/chat/completions"


class TestCheckLlmReadiness:
    def test_reports_missing_api_key_for_hosted_provider(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            return_value=None,
        ):
            readiness = check_llm_readiness(
                environ={"FLUID_LLM_PROVIDER": "openai"},
            )

        assert readiness.ready is False
        assert readiness.provider == "openai"
        assert readiness.auth_available is False
        assert readiness.error is not None
        assert "API key" in readiness.error or "api" in readiness.error.lower()

    def test_marks_ollama_ready_without_api_key(self):
        readiness = check_llm_readiness(
            environ={"FLUID_LLM_PROVIDER": "ollama", "OLLAMA_HOST": "http://localhost:11434"},
        )

        assert readiness.ready is True
        assert readiness.provider == "ollama"
        assert readiness.auth_available is True
        assert readiness.endpoint == "http://localhost:11434/v1/chat/completions"

    def test_redacts_endpoint_in_readiness_output(self):
        readiness = check_llm_readiness(
            environ={
                "FLUID_LLM_PROVIDER": "openai",
                "FLUID_LLM_MODEL": "gpt-4o-mini",
                "FLUID_LLM_ENDPOINT": "https://gateway.example.test/chat?api_key=secret-token",
                "OPENAI_API_KEY": "openai-key",
            },
        )

        assert readiness.ready is True
        assert readiness.endpoint is not None
        assert "gateway.example.test" in readiness.endpoint


class TestEndpointRedaction:
    def test_redacts_auth_parameter(self):
        config = LlmConfig("openai", "gpt-4o", "https://api.example.com?auth=mysecret", "k")
        assert "auth=***" in config.redacted_endpoint
        assert "mysecret" not in config.redacted_endpoint

    def test_redacts_secret_parameter(self):
        config = LlmConfig("openai", "gpt-4o", "https://api.example.com?secret=abc123", "k")
        assert "secret=***" in config.redacted_endpoint
        assert "abc123" not in config.redacted_endpoint

    def test_redacts_credential_parameter(self):
        config = LlmConfig("openai", "gpt-4o", "https://api.example.com?credential=x", "k")
        assert "credential=***" in config.redacted_endpoint

    def test_redacts_password_parameter(self):
        config = LlmConfig("openai", "gpt-4o", "https://api.example.com?password=pw", "k")
        assert "password=***" in config.redacted_endpoint

    def test_redacts_userinfo_in_url(self):
        config = LlmConfig("openai", "gpt-4o", "https://user:pass@api.example.com/v1", "k")
        assert "user:pass" not in config.redacted_endpoint
        assert "***:***@api.example.com" in config.redacted_endpoint


class TestProviderAdapters:
    @pytest.mark.parametrize(
        ("provider", "config", "expected_header", "expected_payload_key"),
        [
            (
                OpenAIProvider(),
                LlmConfig(
                    "openai", "gpt-4o-mini", "https://api.openai.com/v1/chat/completions", "key"
                ),
                "Authorization",
                "messages",
            ),
            (
                AnthropicProvider(),
                LlmConfig(
                    "anthropic",
                    "claude-3-5-sonnet-latest",
                    "https://api.anthropic.com/v1/messages",
                    "key",
                ),
                "x-api-key",
                "messages",
            ),
            (
                GeminiProvider(),
                LlmConfig("gemini", "gemini-1.5-pro", "https://example.test/generate", "key"),
                "x-goog-api-key",
                "contents",
            ),
            (
                OllamaProvider(),
                LlmConfig("ollama", "llama3.1", "http://localhost:11434/v1/chat/completions", None),
                None,
                "messages",
            ),
        ],
    )
    def test_builtin_provider_build_request_shapes(
        self, provider, config, expected_header, expected_payload_key
    ):
        headers, payload = provider.build_request(config, "system prompt", "user prompt")

        if expected_header:
            assert expected_header in headers
        else:
            assert "Authorization" not in headers
        assert expected_payload_key in payload


class TestRuntimeHelpers:
    def test_extract_json_object_handles_fences_and_extra_text(self):
        text = 'Here you go:\n```json\n{"recommended_template":"starter"}\n```\n'
        parsed = extract_json_object(text)
        assert parsed["recommended_template"] == "starter"

    def test_sanitize_additional_files_blocks_path_traversal(self):
        sanitized = sanitize_additional_files(
            {
                "docs/notes.md": "# Notes\n",
                "../secret.txt": "blocked",
                "/tmp/absolute.md": "blocked",
                "runtime/out.bin": "blocked",
            }
        )

        assert sanitized == {"docs/notes.md": "# Notes\n"}

    def test_call_llm_wraps_http_errors(self):
        class FailingClient:
            def __init__(self, *args, **kwargs):
                pass

            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc, tb):
                return False

            def post(self, *args, **kwargs):
                raise httpx.HTTPError("boom")

        with patch("fluid_build.cli.forge_copilot_llm_providers.httpx.Client", FailingClient):
            with pytest.raises(CopilotGenerationError) as exc_info:
                call_llm(
                    OpenAIProvider(),
                    LlmConfig(
                        "openai",
                        "gpt-4o-mini",
                        "https://api.openai.com/v1/chat/completions",
                        "key",
                    ),
                    "system",
                    "user",
                )

        assert exc_info.value.event in ("copilot_llm_request_failed", "copilot_llm_network_error")

    def test_scaffold_decision_uses_use_case_other_for_other_context(self):
        decision = _build_scaffold_decision(
            {
                "project_goal": "Operations platform",
                "use_case": "other",
                "use_case_other": "CDC sync and lakehouse ingestion",
                "data_sources": "warehouse feeds",
            },
            DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            _capability_matrix(),
        )

        assert decision.template == "etl_pipeline"
        assert decision.template_source == "heuristic_context"

    def test_build_user_prompt_includes_use_case_other(self):
        prompt = build_user_prompt(
            context={
                "project_goal": "Operations platform",
                "data_sources": "warehouse feeds",
                "use_case": "other",
                "use_case_other": "CDC sync",
                "complexity": "intermediate",
            },
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            capability_matrix=_capability_matrix(),
            seed_contract=_minimal_contract(),
            seed_template="starter",
            seed_provider="local",
            attempt_index=1,
            previous_errors=[],
            previous_payload=None,
        )

        payload = json.loads(prompt)
        assert payload["interview_summary"]["use_case_other"] == "CDC sync"
        assert payload["interview_summary"]["use_case"] == "other"

    def test_build_user_prompt_includes_modeling_standards(self):
        prompt = build_user_prompt(
            context={
                "project_goal": "Digital retail journeys",
                "data_sources": "web sdk events",
                "domain": "retail",
                "canonical_model": "adobe_xdm",
                "supporting_standards": [],
            },
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            capability_matrix=_capability_matrix(),
            seed_contract=_minimal_contract(),
            seed_template="starter",
            seed_provider="local",
            attempt_index=1,
            previous_errors=[],
            previous_payload=None,
        )

        payload = json.loads(prompt)
        assert payload["interview_summary"]["canonical_model"] == "adobe_xdm"
        assert payload["interview_summary"]["supporting_standards"] == []

    def test_build_seed_contract_is_strictly_valid_for_072(self):
        contract = build_seed_contract(
            context={
                "project_goal": "Orders dashboard",
                "use_case": "analytics",
                "primary_entity": "customer_id",
                "primary_measures": ["revenue"],
                "primary_dimensions": ["country"],
                "time_dimension": "order_date",
                "time_granularity": "day",
            },
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            template_name="analytics",
            provider_name="local",
        )

        validation = FluidSchemaManager().validate_contract(
            contract, strict=True, offline_only=True
        )

        assert validation.is_valid is True
        assert validation.errors == []

    def test_build_seed_contract_describes_traceability_modeling(self):
        contract = build_seed_contract(
            context={
                "project_goal": "Retail traceability events",
                "domain": "retail",
                "data_sources": "epcis lot and serial events",
            },
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            template_name="analytics",
            provider_name="local",
        )

        semantics = contract["exposes"][0]["semantics"]
        assert "GS1" in semantics["description"]
        assert "EPCIS / CBV" in semantics["description"]
        assert semantics["entities"][0]["name"] == "trade_item"

    def test_build_seed_contract_describes_healthcare_interoperability_modeling(self):
        contract = build_seed_contract(
            context={
                "project_goal": "EHR interoperability feeds",
                "domain": "healthcare",
                "data_sources": "FHIR patient and encounter resources",
            },
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            template_name="analytics",
            provider_name="local",
        )

        semantics = contract["exposes"][0]["semantics"]
        assert "HL7 FHIR" in semantics["description"]
        assert semantics["entities"][0]["name"] == "patient"

    def test_clarification_prompt_mentions_fuzzy_user_answers(self):
        prompt = build_clarification_system_prompt(_capability_matrix())

        assert "partial phrases" in prompt
        assert "transcript.raw_input" in prompt

    def test_system_prompt_mentions_canonical_model_guidance(self):
        prompt = build_system_prompt(_capability_matrix())

        assert "canonical_model" in prompt
        assert "supporting_standards" in prompt

    def test_clarification_user_prompt_targets_modeling_slots(self):
        prompt = build_clarification_user_prompt(
            interview_state={"normalized_context": {}, "answered_fields": [], "assumptions": []},
            discovery_report=DiscoveryReport(workspace_roots=["/tmp/workspace"]),
            capability_matrix=_capability_matrix(),
        )

        payload = json.loads(prompt)
        assert "canonical_model" in payload["target_slots"]
        assert "supporting_standards" in payload["target_slots"]


class TestDiscovery:
    def test_discovery_payload_is_metadata_only(self, tmp_path):
        (tmp_path / "README.md").write_text(
            "# Test Project\n\nAPI token is sk-live-secret and should never be forwarded.\n",
            encoding="utf-8",
        )
        (tmp_path / "sql").mkdir()
        (tmp_path / "sql" / "model.sql").write_text(
            "select * from raw.orders join raw.customers using (customer_id)\n",
            encoding="utf-8",
        )
        (tmp_path / "samples").mkdir()
        (tmp_path / "samples" / "customers.csv").write_text(
            "id,email,active\n1,alice@example.com,true\n2,bob@example.com,false\n",
            encoding="utf-8",
        )

        report = discover_local_context(None, workspace_root=tmp_path)
        payload = report.to_prompt_payload()
        payload_text = json.dumps(payload)

        assert report.sample_files[0]["columns"] == {
            "id": "integer",
            "email": "string",
            "active": "boolean",
        }
        assert "raw.orders" in report.sql_files[0]["referenced_tables"]
        assert "alice@example.com" not in payload_text
        assert "bob@example.com" not in payload_text
        assert "sk-live-secret" not in payload_text
        assert "API token is" not in payload_text

    def test_discovery_ignores_airbyte_directories(self, tmp_path):
        source_dir = tmp_path / "airbyte" / "sources"
        connection_dir = tmp_path / "airbyte" / "connections"
        source_dir.mkdir(parents=True)
        connection_dir.mkdir(parents=True)

        (source_dir / "postgres-source.json").write_text(
            json.dumps(
                {
                    "name": "postgres-source",
                    "connectionConfiguration": {
                        "database": "warehouse",
                        "schemas": ["public"],
                        "replication_method": {"method": "CDC"},
                        "replication_slot": "slot_1",
                    },
                }
            ),
            encoding="utf-8",
        )
        (connection_dir / "warehouse-sync.json").write_text(
            json.dumps(
                {
                    "name": "warehouse-sync",
                    "scheduleType": "manual",
                    "status": "active",
                    "syncCatalog": {
                        "streams": [
                            {
                                "stream": {"name": "orders"},
                                "config": {
                                    "syncMode": "incremental",
                                    "cursorField": ["updated_at"],
                                    "primaryKey": [["id"]],
                                },
                            }
                        ]
                    },
                }
            ),
            encoding="utf-8",
        )

        report = discover_local_context(None, workspace_root=tmp_path)

        assert report.files_scanned == 0
        assert report.sample_files == []
        assert report.detected_sources == []

    def test_discovery_summarizes_parquet_metadata(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        with patch(
            "fluid_build.cli.forge_copilot_schema_inference.read_parquet_metadata",
            return_value={
                "columns": {"id": "integer", "created_at": "datetime"},
                "row_count": 42,
                "schema_source": "pyarrow",
            },
        ):
            report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "parquet"
        assert report.sample_files[0]["columns"] == {
            "id": "integer",
            "created_at": "datetime",
        }
        assert report.sample_files[0]["row_count"] == 42
        assert report.sample_files[0]["schema_source"] == "pyarrow"

    def test_discovery_summarizes_avro_metadata(self, tmp_path):
        sample_path = tmp_path / "events.avro"
        sample_path.write_bytes(b"Obj\x01")

        with patch(
            "fluid_build.cli.forge_copilot_schema_inference.read_avro_metadata",
            return_value={
                "columns": {"event_id": "string", "occurred_at": "datetime"},
                "schema_source": "fastavro",
            },
        ):
            report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "avro"
        assert report.sample_files[0]["columns"] == {
            "event_id": "string",
            "occurred_at": "datetime",
        }
        assert report.sample_files[0]["schema_source"] == "fastavro"

    def test_discovery_includes_warning_when_parquet_support_missing(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        with (
            patch(
                "fluid_build.cli.forge_copilot_schema_inference._read_parquet_metadata_pyarrow",
                side_effect=ImportError,
            ),
            patch(
                "fluid_build.cli.forge_copilot_schema_inference._read_parquet_metadata_duckdb",
                side_effect=ImportError,
            ),
        ):
            report = discover_local_context(None, workspace_root=tmp_path)

        assert report.sample_files[0]["format"] == "parquet"
        assert report.sample_files[0]["columns"] == {}
        assert report.discovery_warnings
        assert "pyarrow or duckdb" in report.discovery_warnings[0]

    def test_discovery_continues_when_json_sample_is_invalid(self, tmp_path):
        (tmp_path / "broken.json").write_text("{not json", encoding="utf-8")
        (tmp_path / "customers.csv").write_text(
            "id,email\n1,alice@example.com\n",
            encoding="utf-8",
        )

        report = discover_local_context(None, workspace_root=tmp_path)

        assert len(report.sample_files) == 2
        assert any(sample["path"].endswith("broken.json") for sample in report.sample_files)
        assert any(sample["path"].endswith("customers.csv") for sample in report.sample_files)
        assert any("broken.json" in warning for warning in report.discovery_warnings)

    def test_read_parquet_metadata_with_pyarrow_module(self, tmp_path):
        sample_path = tmp_path / "customers.parquet"
        sample_path.write_bytes(b"PAR1")

        class FakeField:
            def __init__(self, name, type_name):
                self.name = name
                self.type = type_name

        class FakeParquetFile:
            def __init__(self, path):
                self.schema_arrow = [
                    FakeField("id", "int64"),
                    FakeField("created_at", "timestamp[us]"),
                ]
                self.metadata = types.SimpleNamespace(num_rows=24)

        fake_parquet_module = types.SimpleNamespace(ParquetFile=FakeParquetFile)
        fake_pyarrow_module = types.ModuleType("pyarrow")
        fake_pyarrow_module.parquet = fake_parquet_module

        with patch.dict(
            "sys.modules",
            {
                "pyarrow": fake_pyarrow_module,
                "pyarrow.parquet": fake_parquet_module,
            },
        ):
            metadata = _read_parquet_metadata(sample_path)

        assert metadata["columns"] == {"id": "integer", "created_at": "datetime"}
        assert metadata["row_count"] == 24
        assert metadata["schema_source"] == "pyarrow"

    def test_read_avro_metadata_with_fastavro_module(self, tmp_path):
        sample_path = tmp_path / "events.avro"
        sample_path.write_bytes(b"Obj\x01")

        class FakeReader:
            def __init__(self, handle):
                self.writer_schema = {
                    "type": "record",
                    "name": "events",
                    "fields": [
                        {"name": "event_id", "type": "string"},
                        {
                            "name": "occurred_at",
                            "type": {"type": "long", "logicalType": "timestamp-millis"},
                        },
                    ],
                }

        fake_fastavro_module = types.SimpleNamespace(reader=FakeReader)

        with patch.dict("sys.modules", {"fastavro": fake_fastavro_module}):
            metadata = _read_avro_metadata(sample_path)

        assert metadata["columns"] == {
            "event_id": "string",
            "occurred_at": "datetime",
        }
        assert metadata["schema_source"] == "fastavro"


class TestGenerationValidation:
    def setup_method(self):
        """Slice UX-G memoizes build_capability_matrix() at module level.
        Clear the cache between tests that monkey-patch the registry so
        each test sees its own fresh computation."""
        from fluid_build.cli.forge_copilot_runtime import clear_capability_matrix_cache

        clear_capability_matrix_cache()

    def teardown_method(self):
        from fluid_build.cli.forge_copilot_runtime import clear_capability_matrix_cache

        clear_capability_matrix_cache()

    def test_build_capability_matrix_falls_back_to_builtin_providers_when_registry_listing_fails(
        self,
    ):
        with patch(
            "fluid_build.forge.core.registry.provider_registry.list_available",
            side_effect=RuntimeError("provider registry unavailable"),
        ):
            with patch(
                "fluid_build.forge.core.registry.template_registry.list_available",
                return_value=[],
            ):
                capability_matrix = build_capability_matrix()

        assert capability_matrix["providers"] == ["local", "gcp", "aws", "snowflake"]
        assert capability_matrix["warnings"]
        assert "couldn't list local providers" in capability_matrix["warnings"][0].lower()

    def test_build_capability_matrix_keeps_verified_providers_when_one_builtin_check_fails(self):
        with patch(
            "fluid_build.forge.core.registry.provider_registry.list_available",
            return_value=["local", "gcp", "aws"],
        ):
            with patch(
                "fluid_build.forge.core.registry.provider_registry.get",
                side_effect=lambda name: None if name == "aws" else object(),
            ):
                with patch(
                    "fluid_build.forge.core.registry.template_registry.list_available",
                    return_value=[],
                ):
                    capability_matrix = build_capability_matrix()

        assert capability_matrix["providers"] == ["local", "gcp"]
        assert any("aws provider" in warning.lower() for warning in capability_matrix["warnings"])

    @patch("fluid_build.cli.forge_copilot_runtime.FluidSchemaManager")
    def test_validate_generated_result_checks_provider_engine_compatibility(
        self, mock_schema_manager
    ):
        mock_schema_manager.return_value.validate_contract.return_value = ValidationResult(
            is_valid=True, errors=[], warnings=[]
        )
        normalized = {
            "contract": _minimal_contract(provider="aws", engine="dataform"),
            "suggestions": {
                "recommended_provider": "aws",
                "recommended_template": "starter",
            },
        }

        errors, warnings = validate_generated_result(normalized, capabilities=_capability_matrix())

        assert not warnings
        assert any("not supported for provider 'aws'" in error for error in errors)

    def test_build_scaffold_decision_defaults_to_local_when_provider_list_is_empty(self):
        decision = _build_scaffold_decision(
            {"project_goal": "Simple analytics project"},
            DiscoveryReport(workspace_roots=["/tmp/project"]),
            {"providers": [], "templates": {"starter": {}}},
        )

        assert decision.provider == "local"
        assert decision.provider_source == "default"

    def test_generate_copilot_artifacts_retries_and_recovers(self):
        payload = {
            "recommended_template": "starter",
            "recommended_provider": "local",
            "recommended_patterns": [],
            "architecture_suggestions": [],
            "best_practices": [],
            "technology_stack": [],
            "readme_markdown": "# Copilot Project\n",
            "contract": _minimal_contract(),
            "additional_files": {"docs/notes.md": "metadata only"},
        }

        with patch(
            "fluid_build.cli.forge_copilot_runtime.call_llm",
            side_effect=[json.dumps(payload), json.dumps(payload)],
        ) as mock_call_llm:
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                side_effect=[(["First attempt failed"], []), ([], ["Schema warning"])],
            ):
                result = generate_copilot_artifacts(
                    {"project_goal": "Copilot project", "data_sources": "CSV files"},
                    llm_config=LlmConfig(
                        provider="openai",
                        model="gpt-4o-mini",
                        endpoint="https://api.openai.com/v1/chat/completions",
                        api_key="key",
                    ),
                    discovery_report=DiscoveryReport(workspace_roots=["/tmp/project"]),
                    capability_matrix=_capability_matrix(),
                )

        assert mock_call_llm.call_count == 2
        assert len(result.attempt_reports) == 2
        assert result.attempt_reports[0].validation_errors == ["First attempt failed"]
        assert result.contract["id"] == "generated.test"
        assert result.additional_files == {"docs/notes.md": "metadata only"}

    def test_generate_copilot_artifacts_raises_after_three_failed_attempts(self):
        payload = {
            "recommended_template": "starter",
            "recommended_provider": "local",
            "readme_markdown": "# Copilot Project\n",
            "contract": _minimal_contract(),
        }

        with patch(
            "fluid_build.cli.forge_copilot_runtime.call_llm",
            side_effect=[json.dumps(payload), json.dumps(payload), json.dumps(payload)],
        ) as mock_call_llm:
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=(["Still invalid"], []),
            ):
                with pytest.raises(CopilotGenerationError) as exc_info:
                    generate_copilot_artifacts(
                        {"project_goal": "Copilot project", "data_sources": "CSV files"},
                        llm_config=LlmConfig(
                            provider="openai",
                            model="gpt-4o-mini",
                            endpoint="https://api.openai.com/v1/chat/completions",
                            api_key="key",
                        ),
                        discovery_report=DiscoveryReport(workspace_roots=["/tmp/project"]),
                        capability_matrix=_capability_matrix(),
                    )

        assert mock_call_llm.call_count == 3
        assert exc_info.value.event == "copilot_generation_failed"
        assert any("Attempt 1" in suggestion for suggestion in exc_info.value.suggestions)


class TestCopilotOverrides:
    def test_generators_use_copilot_overrides(self, tmp_path):
        project_config = {
            "name": "copilot-project",
            "template": "starter",
            "provider": "local",
            "copilot_generated_contract": _minimal_contract(),
            "copilot_generated_readme": "# Copilot Project\n",
            "copilot_generated_files": {"docs/notes.md": "metadata only"},
        }
        context = _generation_context(tmp_path, project_config)

        contract_files = ContractGenerator().generate(context)
        readme_files = ReadmeGenerator().generate(context)
        config_files = ConfigGenerator().generate(context)

        assert "contract.fluid.yaml" in contract_files
        assert "generated.test" in contract_files["contract.fluid.yaml"]
        assert readme_files == {"README.md": "# Copilot Project\n"}
        assert "requirements.txt" in config_files
        assert config_files["docs/notes.md"] == "metadata only"

    def test_engine_run_generators_writes_copilot_files(self, tmp_path):
        engine = _make_engine()
        project_config = {
            "name": "copilot-project",
            "template": "starter",
            "provider": "local",
            "copilot_generated_contract": _minimal_contract(),
            "copilot_generated_readme": "# Copilot Project\n",
            "copilot_generated_files": {"docs/notes.md": "metadata only"},
        }
        engine.project_config = project_config
        engine.generation_context = _generation_context(tmp_path, project_config)

        generators = {
            "readme": ReadmeGenerator(),
            "config": ConfigGenerator(),
        }

        with patch(
            "fluid_build.forge.core.engine.generator_registry.list_available",
            return_value=["contract", "readme", "config"],
        ):
            with patch(
                "fluid_build.forge.core.engine.generator_registry.get_dependency_order",
                side_effect=lambda names: names,
            ):
                with patch(
                    "fluid_build.forge.core.engine.generator_registry.get",
                    side_effect=lambda name: generators.get(name),
                ):
                    engine._run_generators()

        assert (tmp_path / "README.md").read_text(encoding="utf-8") == "# Copilot Project\n"
        assert (tmp_path / "docs" / "notes.md").read_text(encoding="utf-8") == "metadata only"
        assert (tmp_path / "requirements.txt").exists()


class TestDetectProviderFromApiKey:
    def test_anthropic_key(self):
        assert detect_provider_from_api_key("sk-ant-api03-abc123") == "anthropic"

    def test_openai_key_proj(self):
        assert detect_provider_from_api_key("sk-proj-abc123") == "openai"

    def test_openai_key_plain(self):
        assert detect_provider_from_api_key("sk-abc123") == "openai"

    def test_openai_key_svcacct(self):
        assert detect_provider_from_api_key("sk-svcacct-abc123") == "openai"

    def test_gemini_key(self):
        assert detect_provider_from_api_key("AIzaSyD" + "x" * 30) == "gemini"

    def test_unrecognized_key_returns_none(self):
        assert detect_provider_from_api_key("random-string-no-match") is None

    def test_empty_string_returns_none(self):
        assert detect_provider_from_api_key("") is None

    def test_none_returns_none(self):
        assert detect_provider_from_api_key(None) is None

    def test_whitespace_stripped(self):
        assert detect_provider_from_api_key("  sk-ant-api03-abc  ") == "anthropic"


class TestKeyringResolution:
    """Tests for keyring-backed API key resolution."""

    def test_resolve_api_key_falls_back_to_keyring(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            return_value="keyring-secret",
        ):
            result = _resolve_api_key("openai", {})
        assert result == "keyring-secret"

    def test_env_var_takes_priority_over_keyring(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            return_value="keyring-secret",
        ):
            result = _resolve_api_key("openai", {"OPENAI_API_KEY": "env-secret"})
        assert result == "env-secret"

    def test_fluid_llm_api_key_takes_priority_over_keyring(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            return_value="keyring-secret",
        ):
            result = _resolve_api_key("openai", {"FLUID_LLM_API_KEY": "generic-key"})
        assert result == "generic-key"

    def test_keyring_returns_none_when_not_available(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            return_value=None,
        ):
            result = _resolve_api_key("openai", {})
        assert result is None

    def test_save_api_key_to_keyring_success(self):
        mock_store = MagicMock()
        with patch.dict(
            "sys.modules",
            {"fluid_build.credentials.keyring_store": mock_store},
        ):
            mock_store.KeyringCredentialStore.set_credential = MagicMock()
            result = save_api_key_to_keyring("openai", "test-key")
        assert result is True

    def test_save_api_key_to_keyring_graceful_failure(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers._get_api_key_from_keyring",
            side_effect=ImportError("no keyring"),
        ):
            # save uses its own import — simulate failure via exception in the function
            pass
        # Direct test: if keyring module is missing, function returns False
        with patch.dict("sys.modules", {"fluid_build.credentials.keyring_store": None}):
            result = save_api_key_to_keyring("openai", "test-key")
        assert result is False

    def test_clear_api_key_from_keyring_graceful_failure(self):
        with patch.dict("sys.modules", {"fluid_build.credentials.keyring_store": None}):
            result = clear_api_key_from_keyring("openai")
        assert result is False


class TestParseParamSize:
    def test_billions(self):
        assert _parse_param_size("32.8B") == 32.8

    def test_integer_billions(self):
        assert _parse_param_size("7B") == 7.0

    def test_millions(self):
        assert _parse_param_size("671M") == pytest.approx(0.671)

    def test_empty(self):
        assert _parse_param_size("") == 0.0

    def test_unparseable(self):
        assert _parse_param_size("unknown") == 0.0

    def test_no_unit(self):
        assert _parse_param_size("14") == 14.0


class TestOllamaModelResolution:
    def test_resolve_picks_largest_model(self):
        fake_response = {
            "models": [
                {
                    "name": "llama3.1:7b",
                    "details": {"parameter_size": "7B"},
                },
                {
                    "name": "qwen2.5-coder:32b",
                    "details": {"parameter_size": "32.8B"},
                },
                {
                    "name": "phi3:3b",
                    "details": {"parameter_size": "3B"},
                },
            ]
        }

        with patch("fluid_build.cli.forge_copilot_llm_providers.httpx.get") as mock_get:
            mock_get.return_value = MagicMock(status_code=200, json=lambda: fake_response)
            mock_get.return_value.raise_for_status = MagicMock()
            result = resolve_ollama_model({})

        assert result == "qwen2.5-coder:32b"

    def test_resolve_falls_back_when_ollama_unreachable(self):
        with patch(
            "fluid_build.cli.forge_copilot_llm_providers.httpx.get",
            side_effect=Exception("connection refused"),
        ):
            result = resolve_ollama_model({})
        assert result == "llama3.1"

    def test_resolve_falls_back_when_no_models(self):
        with patch("fluid_build.cli.forge_copilot_llm_providers.httpx.get") as mock_get:
            mock_get.return_value = MagicMock(status_code=200, json=lambda: {"models": []})
            mock_get.return_value.raise_for_status = MagicMock()
            result = resolve_ollama_model({})
        assert result == "llama3.1"


class TestModelCatalog:
    def test_resolve_exact_id(self):
        assert resolve_model_name("openai", "gpt-4o") == "gpt-4o"

    def test_resolve_alias(self):
        assert resolve_model_name("openai", "gpt4o") == "gpt-4o"

    def test_resolve_anthropic_alias(self):
        assert resolve_model_name("anthropic", "sonnet") == "claude-sonnet-4-5-20250514"

    def test_resolve_anthropic_haiku(self):
        assert resolve_model_name("anthropic", "haiku") == "claude-haiku-4-5-20251001"

    def test_resolve_gemini_alias(self):
        assert resolve_model_name("gemini", "gemini-pro") == "gemini-2.5-pro"

    def test_unknown_passes_through(self):
        assert resolve_model_name("openai", "my-custom-finetune") == "my-custom-finetune"

    def test_case_insensitive(self):
        assert resolve_model_name("anthropic", "Opus") == "claude-opus-4-0-20250514"

    def test_empty_input(self):
        assert resolve_model_name("openai", "") == ""
