# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""High-level forge copilot scenarios using fake mockup workspaces."""

from __future__ import annotations

import json
from contextlib import ExitStack
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from fluid_build.cli.forge import CopilotAgent, handle_memory_management
from fluid_build.cli.forge_copilot_memory import CopilotMemoryStore
from fluid_build.cli.forge_copilot_runtime import LlmConfig


def _capability_matrix() -> dict:
    return {
        "providers": ["local", "gcp", "aws", "snowflake"],
        "templates": {
            "starter": {},
            "analytics": {},
            "etl_pipeline": {},
            "ml_pipeline": {},
            "streaming": {},
        },
    }


def _binding(provider: str, expose_name: str) -> dict:
    if provider == "gcp":
        return {
            "platform": "gcp",
            "format": "bigquery_table",
            "location": {
                "project": "${FLUID_GCP_PROJECT}",
                "dataset": "analytics",
                "table": expose_name,
            },
        }
    if provider == "snowflake":
        return {
            "platform": "snowflake",
            "format": "table",
            "location": {
                "database": "${SNOWFLAKE_DATABASE}",
                "schema": "ANALYTICS",
                "table": expose_name.upper(),
            },
        }
    return {
        "platform": "local",
        "format": "csv",
        "location": {"path": f"runtime/out/{expose_name}.csv"},
    }


def _minimal_contract(
    *,
    provider: str = "local",
    template: str = "analytics",
    domain: str = "analytics",
    owner: str = "data-team",
    columns: dict[str, str] | None = None,
) -> dict:
    expose_name = "orders_output"
    schema_columns = [
        {
            "name": name,
            "type": {
                "integer": "integer",
                "number": "number",
                "date": "date",
                "datetime": "timestamp",
            }.get(column_type, "string"),
            "required": False,
        }
        for name, column_type in (columns or {"id": "integer", "email": "string"}).items()
    ]
    return {
        "fluidVersion": "0.7.2",
        "kind": "DataProduct",
        "id": "generated.test",
        "name": "Test Product",
        "description": "Generated by fake copilot scenario tests",
        "domain": domain,
        "metadata": {
            "layer": "Bronze",
            "owner": {"team": owner, "email": "data-team@example.com"},
        },
        "builds": [
            {
                "id": "main_build",
                "pattern": "embedded-logic",
                "engine": "sql",
                "properties": {"sql": "SELECT 1 AS id"},
                "execution": {
                    "trigger": {"type": "manual", "iterations": 1},
                    "runtime": {"platform": provider, "resources": {"cpu": "1", "memory": "2Gi"}},
                },
            }
        ],
        "exposes": [
            {
                "exposeId": expose_name,
                "kind": "table",
                "binding": _binding(provider, expose_name),
                "contract": {"schema": schema_columns},
                "semantics": {
                    "name": "Orders Output",
                    "description": "Semantic model for scenario tests.",
                    "entities": [{"name": schema_columns[0]["name"], "type": "primary"}],
                    "measures": [
                        {
                            "name": f"{schema_columns[0]['name']}_count",
                            "agg": "count",
                            "expr": schema_columns[0]["name"],
                            "description": "Scenario count metric.",
                        }
                    ],
                    "dimensions": [{"name": schema_columns[0]["name"], "type": "categorical"}],
                    "metrics": [
                        {
                            "name": f"{schema_columns[0]['name']}_count_metric",
                            "type": "simple",
                            "measure": f"{schema_columns[0]['name']}_count",
                            "description": "Scenario metric.",
                        }
                    ],
                },
            }
        ],
    }


def _payload(
    *,
    provider: str = "local",
    template: str = "analytics",
    domain: str = "analytics",
    owner: str = "data-team",
    columns: dict[str, str] | None = None,
) -> dict:
    return {
        "recommended_template": template,
        "recommended_provider": provider,
        "recommended_patterns": ["layered_architecture"],
        "architecture_suggestions": ["Use modular builds"],
        "best_practices": ["Validate before apply"],
        "technology_stack": ["sql"],
        "description": "Fake scenario payload",
        "domain": domain,
        "owner": owner,
        "readme_markdown": "# Scenario Project\n",
        "contract": _minimal_contract(
            provider=provider,
            template=template,
            domain=domain,
            owner=owner,
            columns=columns,
        ),
        "additional_files": {"docs/notes.md": "scenario metadata only"},
    }


def _make_agent() -> CopilotAgent:
    agent = CopilotAgent()
    agent.console = None
    return agent


def _mock_llm_config() -> LlmConfig:
    return LlmConfig(
        provider="openai",
        model="gpt-4o-mini",
        endpoint="https://api.openai.com/v1/chat/completions",
        api_key="test-key",
    )


def _write_common_workspace(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "README.md").write_text(
        "# Fake project\n\nUsed for copilot scenarios.\n", encoding="utf-8"
    )
    (path / "sql").mkdir(exist_ok=True)
    (path / "sql" / "orders.sql").write_text(
        "select * from raw.orders join raw.customers using (customer_id)\n",
        encoding="utf-8",
    )


def _write_sample_workspace(
    path: Path, sample_format: str
) -> tuple[dict[str, str], dict[str, object]]:
    _write_common_workspace(path)
    samples_dir = path / "samples"
    samples_dir.mkdir(exist_ok=True)

    if sample_format == "csv":
        (samples_dir / "customers.csv").write_text(
            "id,email,active\n1,alice@example.com,true\n2,bob@example.com,false\n",
            encoding="utf-8",
        )
        return {"id": "integer", "email": "string", "active": "boolean"}, {}

    if sample_format == "json":
        (samples_dir / "customers.json").write_text(
            json.dumps(
                [
                    {"id": 1, "email": "alice@example.com", "active": True},
                    {"id": 2, "email": "bob@example.com", "active": False},
                ]
            ),
            encoding="utf-8",
        )
        return {"id": "integer", "email": "string", "active": "boolean"}, {}

    if sample_format == "parquet":
        (samples_dir / "customers.parquet").write_bytes(b"PAR1")
        return (
            {"customer_id": "integer", "created_at": "datetime", "country": "string"},
            {
                "patch_target": "fluid_build.cli.forge_copilot_schema_inference.read_parquet_metadata",
                "patch_value": {
                    "columns": {
                        "customer_id": "integer",
                        "created_at": "datetime",
                        "country": "string",
                    },
                    "row_count": 12,
                    "schema_source": "pyarrow",
                },
            },
        )

    if sample_format == "avro":
        (samples_dir / "customers.avro").write_bytes(b"Obj\x01")
        return (
            {"customer_id": "integer", "created_at": "datetime", "country": "string"},
            {
                "patch_target": "fluid_build.cli.forge_copilot_schema_inference.read_avro_metadata",
                "patch_value": {
                    "columns": {
                        "customer_id": "integer",
                        "created_at": "datetime",
                        "country": "string",
                    },
                    "schema_source": "fastavro",
                },
            },
        )

    raise ValueError(f"Unsupported sample format: {sample_format}")


def _write_gcp_workspace(path: Path) -> None:
    _write_common_workspace(path)
    (path / "dbt_project.yml").write_text(
        "name: fake_project\nprofile: bigquery\nmodel-paths: ['models']\n",
        encoding="utf-8",
    )
    (path / "infra").mkdir(parents=True, exist_ok=True)
    (path / "infra" / "main.tf").write_text(
        'resource "google_bigquery_dataset" "analytics" {}\n',
        encoding="utf-8",
    )


@pytest.mark.parametrize("sample_format", ["csv", "json", "parquet", "avro"])
def test_copilot_scenario_mock_samples_save_metadata_only_memory(
    tmp_path: Path, monkeypatch, sample_format: str
):
    workspace = tmp_path / f"workspace-{sample_format}"
    expected_columns, patch_config = _write_sample_workspace(workspace, sample_format)
    monkeypatch.chdir(workspace)

    agent = _make_agent()
    agent._create_with_forge_engine = lambda project_config, dry_run=False: True
    agent._show_next_steps = lambda *args, **kwargs: None
    agent._show_ai_analysis = lambda *args, **kwargs: None

    with ExitStack() as stack:
        stack.enter_context(
            patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config())
        )
        stack.enter_context(
            patch(
                "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
            )
        )
        stack.enter_context(
            patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            )
        )
        stack.enter_context(
            patch(
                "fluid_build.cli.forge_copilot_runtime.call_llm",
                return_value=json.dumps(
                    _payload(
                        provider="local",
                        template="analytics",
                        columns=expected_columns,
                    )
                ),
            )
        )
        if patch_config:
            stack.enter_context(
                patch(patch_config["patch_target"], return_value=patch_config["patch_value"])
            )
        success = agent.create_project(
            workspace,
            {
                "project_goal": f"{sample_format} analytics project",
                "data_sources": f"{sample_format} files",
                "use_case": "analytics",
            },
            {
                "non_interactive": True,
                "save_memory": True,
                "llm_provider": "openai",
                "target_dir": str(workspace),
            },
        )

    assert success is True

    store = CopilotMemoryStore(workspace)
    memory = store.load()
    assert memory is not None
    assert memory.project_profile["template"] == "analytics"
    assert memory.project_profile["provider"] == "local"
    assert memory.conventions["build_engines"] == ["sql"]
    assert sample_format in memory.conventions["source_formats"]
    assert memory.conventions["schema_summaries"][0]["columns"] == expected_columns

    raw_memory = store.path.read_text(encoding="utf-8")
    assert "alice@example.com" not in raw_memory
    assert "bob@example.com" not in raw_memory
    assert "SELECT * FROM raw.orders" not in raw_memory


def test_copilot_scenario_reuses_saved_memory_for_ambiguous_followup(tmp_path: Path, monkeypatch):
    workspace = tmp_path / "memory-followup"
    workspace.mkdir(parents=True, exist_ok=True)
    store = CopilotMemoryStore(workspace)
    store.save(
        CopilotMemoryStore(workspace).update_from_success(
            context={"project_goal": "Orders analytics"},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(provider="local", template="analytics"),
            discovery_report={"provider_hints": ["local"], "sample_files": []},
        )
    )
    monkeypatch.chdir(workspace)

    agent = _make_agent()
    captured_prompt = {}

    def _capture_llm(_provider, _config, _system_prompt, user_prompt):
        captured_prompt["payload"] = json.loads(user_prompt)
        return json.dumps(_payload(provider="local", template="analytics"))

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm", side_effect=_capture_llm
                ):
                    result = agent.generate_project_artifacts(
                        {
                            "project_goal": "Orders product",
                            "data_sources": "warehouse tables",
                            "use_case": "other",
                        },
                        {"llm_provider": "openai", "target_dir": str(workspace)},
                    )

    assert result.scaffold_decision is not None
    assert result.scaffold_decision.template_source == "project_memory"
    assert result.scaffold_decision.provider_source == "project_memory"
    assert captured_prompt["payload"]["project_memory"]["preferred_template"] == "analytics"
    assert captured_prompt["payload"]["project_memory"]["preferred_provider"] == "local"


def test_copilot_scenario_no_memory_bypasses_saved_memory(tmp_path: Path, monkeypatch):
    workspace = tmp_path / "memory-disabled"
    workspace.mkdir(parents=True, exist_ok=True)
    store = CopilotMemoryStore(workspace)
    store.save(
        CopilotMemoryStore(workspace).update_from_success(
            context={"project_goal": "Orders analytics"},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(provider="local", template="analytics"),
            discovery_report={"provider_hints": ["local"], "sample_files": []},
        )
    )
    monkeypatch.chdir(workspace)

    agent = _make_agent()
    captured_prompt = {}

    def _capture_llm(_provider, _config, _system_prompt, user_prompt):
        captured_prompt["payload"] = json.loads(user_prompt)
        return json.dumps(_payload(provider="local", template="starter"))

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm", side_effect=_capture_llm
                ):
                    result = agent.generate_project_artifacts(
                        {
                            "project_goal": "Orders product",
                            "data_sources": "warehouse tables",
                            "use_case": "other",
                        },
                        {"llm_provider": "openai", "target_dir": str(workspace), "memory": False},
                    )

    assert result.project_memory is None
    assert result.scaffold_decision is not None
    assert result.scaffold_decision.template_source == "default"
    assert result.scaffold_decision.provider_source == "default"
    assert "project_memory" not in captured_prompt["payload"]


def test_copilot_scenario_current_discovery_beats_saved_memory(tmp_path: Path, monkeypatch):
    workspace = tmp_path / "discovery-beats-memory"
    _write_gcp_workspace(workspace)
    store = CopilotMemoryStore(workspace)
    store.save(
        CopilotMemoryStore(workspace).update_from_success(
            context={"project_goal": "Old local analytics"},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(provider="local", template="analytics"),
            discovery_report={"provider_hints": ["local"], "sample_files": []},
        )
    )
    monkeypatch.chdir(workspace)

    agent = _make_agent()

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm",
                    return_value=json.dumps(
                        _payload(provider="gcp", template="etl_pipeline", domain="operations")
                    ),
                ):
                    result = agent.generate_project_artifacts(
                        {
                            "project_goal": "sync warehouse feeds",
                            "data_sources": "multiple sources",
                            "use_case": "analytics",
                        },
                        {"llm_provider": "openai", "target_dir": str(workspace)},
                    )

    assert result.scaffold_decision is not None
    assert result.scaffold_decision.template == "etl_pipeline"
    assert result.scaffold_decision.template_source == "heuristic_context"
    assert result.scaffold_decision.provider == "gcp"
    assert result.scaffold_decision.provider_source == "current_discovery"


def test_copilot_scenario_explicit_input_beats_discovery_and_memory(tmp_path: Path, monkeypatch):
    workspace = tmp_path / "explicit-wins"
    _write_gcp_workspace(workspace)
    store = CopilotMemoryStore(workspace)
    store.save(
        CopilotMemoryStore(workspace).update_from_success(
            context={"project_goal": "Old local analytics"},
            suggestions={
                "recommended_template": "analytics",
                "recommended_provider": "local",
                "domain": "analytics",
                "owner": "data-team",
            },
            contract=_minimal_contract(provider="local", template="analytics"),
            discovery_report={"provider_hints": ["local"], "sample_files": []},
        )
    )
    monkeypatch.chdir(workspace)

    agent = _make_agent()

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm",
                    return_value=json.dumps(
                        _payload(provider="snowflake", template="ml_pipeline", domain="ml")
                    ),
                ):
                    result = agent.generate_project_artifacts(
                        {
                            "project_goal": "Model scoring pipeline",
                            "data_sources": "feature tables",
                            "use_case": "ml_pipeline",
                            "provider": "snowflake",
                            "template": "ml_pipeline",
                        },
                        {"llm_provider": "openai", "target_dir": str(workspace)},
                    )

    assert result.scaffold_decision is not None
    assert result.scaffold_decision.template == "ml_pipeline"
    assert result.scaffold_decision.template_source == "explicit_context"
    assert result.scaffold_decision.provider == "snowflake"
    assert result.scaffold_decision.provider_source == "explicit_context"


def test_copilot_scenario_validation_repair_loop_uses_second_attempt(tmp_path: Path, monkeypatch):
    workspace = tmp_path / "repair-loop"
    _write_sample_workspace(workspace, "csv")
    monkeypatch.chdir(workspace)

    agent = _make_agent()
    captured_prompts = []
    bad_payload = _payload(provider="local", template="starter")
    good_payload = _payload(provider="local", template="analytics")

    def _capture_llm(_provider, _config, _system_prompt, user_prompt):
        captured_prompts.append(json.loads(user_prompt))
        if len(captured_prompts) == 1:
            return json.dumps(bad_payload)
        return json.dumps(good_payload)

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                side_effect=[(["First attempt failed validation"], []), ([], [])],
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm", side_effect=_capture_llm
                ):
                    result = agent.generate_project_artifacts(
                        {
                            "project_goal": "Orders product",
                            "data_sources": "csv files",
                            "use_case": "analytics",
                        },
                        {"llm_provider": "openai", "target_dir": str(workspace)},
                    )

    assert len(result.attempt_reports) == 2
    assert result.attempt_reports[0].validation_errors == ["First attempt failed validation"]
    assert captured_prompts[1]["repair_feedback"] == ["First attempt failed validation"]
    assert captured_prompts[1]["previous_response_summary"]["recommended_template"] == "starter"
    assert result.suggestions["recommended_template"] == "analytics"


def test_copilot_scenario_corrupt_memory_is_ignored_then_show_and_reset_work(
    tmp_path: Path, monkeypatch
):
    workspace = tmp_path / "memory-management"
    _write_common_workspace(workspace)
    store = CopilotMemoryStore(workspace)
    store.path.parent.mkdir(parents=True, exist_ok=True)
    store.path.write_text("{not-json", encoding="utf-8")
    monkeypatch.chdir(workspace)

    agent = _make_agent()
    agent._create_with_forge_engine = lambda project_config, dry_run=False: True
    agent._show_next_steps = lambda *args, **kwargs: None
    agent._show_ai_analysis = lambda *args, **kwargs: None

    with patch("fluid_build.cli.forge.resolve_llm_config", return_value=_mock_llm_config()):
        with patch(
            "fluid_build.cli.forge.build_capability_matrix", return_value=_capability_matrix()
        ):
            with patch(
                "fluid_build.cli.forge_copilot_runtime.validate_generated_result",
                return_value=([], []),
            ):
                with patch(
                    "fluid_build.cli.forge_copilot_runtime.call_llm",
                    return_value=json.dumps(_payload(provider="local", template="starter")),
                ):
                    success = agent.create_project(
                        workspace,
                        {
                            "project_goal": "Fresh starter",
                            "data_sources": "local tables",
                            "use_case": "analytics",
                        },
                        {
                            "non_interactive": True,
                            "save_memory": True,
                            "llm_provider": "openai",
                            "target_dir": str(workspace),
                        },
                    )

    assert success is True
    memory = store.load()
    assert memory is not None
    assert memory.project_profile["template"] == "starter"

    show_result = handle_memory_management(
        SimpleNamespace(target_dir=str(workspace), show_memory=True, reset_memory=False),
        logger=None,
    )
    assert show_result == 0
    assert store.path.exists()

    reset_result = handle_memory_management(
        SimpleNamespace(target_dir=str(workspace), show_memory=False, reset_memory=True),
        logger=None,
    )
    assert reset_result == 0
    assert not store.path.exists()
