# Copyright 2024-2026 Agentics Transformation Ltd
# Licensed under the Apache License, Version 2.0

"""Slice 7 tests: CI header injection + ci-state.json across all providers.

Every generated CI file carries a provider-native comment header
(``#`` for the six YAML providers, ``//`` for Jenkinsfile) that names
the generator, timestamp, command, and a sha256 prefix.  After
successful generation, ``.fluid/ci-state.json`` records the inputs and
per-file sha256 so cross-machine drift detection can work.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fluid_build.cli.artifact_ci_state import (
    build_ci_state_payload,
    write_ci_state,
)
from fluid_build.cli.artifact_paths import (
    ENVELOPE_SCHEMA_VERSION,
    product_ci_state_path,
)
from fluid_build.cli.pipeline_generator import (
    _comment_prefix_for,
    _render_header,
    build_pipeline_config,
    write_pipeline_files,
)
from fluid_build.forge.core.pipeline_templates import PipelineTemplateGenerator


class TestCommentPrefix:
    """_comment_prefix_for must pick the right comment syntax per file."""

    def test_yaml_files_use_hash(self):
        assert _comment_prefix_for("foo.yml") == "#"
        assert _comment_prefix_for("foo.yaml") == "#"
        assert _comment_prefix_for("bar/baz.yml") == "#"
        assert _comment_prefix_for(".github/workflows/fluid.yml") == "#"
        assert _comment_prefix_for(".circleci/config.yml") == "#"
        assert _comment_prefix_for("tekton/pipeline.yaml") == "#"

    def test_jenkinsfile_uses_double_slash(self):
        assert _comment_prefix_for("Jenkinsfile") == "//"
        assert _comment_prefix_for("subdir/Jenkinsfile") == "//"

    def test_unknown_falls_back_to_hash(self):
        """Defaulting to `#` covers every config format we might add later."""
        assert _comment_prefix_for("some-file.conf") == "#"
        assert _comment_prefix_for("Dockerfile") == "#"


class TestRenderHeader:
    def test_contains_generator_timestamp_command_and_schema(self):
        header = _render_header(
            filename=".github/workflows/fluid.yml",
            command="fluid forge --ci github_actions",
            tool_version="0.7.9",
            generated_at="2026-04-11T14:22:18Z",
        )
        lines = header.splitlines()
        assert "Generated by fluid-cli v0.7.9" in lines[0]
        assert "2026-04-11T14:22:18Z" in lines[0]
        assert "fluid forge --ci github_actions" in lines[1]
        # Schema line is always last
        assert lines[-1].strip().endswith("fluid.ci/v1")

    def test_yaml_header_starts_with_hash(self):
        header = _render_header(
            filename="test.yml",
            command="fluid forge --ci gitlab_ci",
            tool_version="0.7.9",
        )
        for line in header.splitlines():
            assert line.startswith("#")

    def test_jenkinsfile_header_starts_with_double_slash(self):
        header = _render_header(
            filename="Jenkinsfile",
            command="fluid forge --ci jenkins",
            tool_version="0.7.9",
        )
        for line in header.splitlines():
            assert line.startswith("//")

    def test_sha256_prefix_is_included_when_given(self):
        header = _render_header(
            filename="test.yml",
            command="fluid forge",
            tool_version="0.7.9",
            sha256_prefix="deadbeef1234",
        )
        assert "deadbeef1234" in header


@pytest.mark.parametrize(
    "provider,expected_comment",
    [
        ("github_actions", "#"),
        ("gitlab_ci", "#"),
        ("jenkins", "//"),
    ],
)
class TestWritePipelineFilesWithHeader:
    def test_generated_files_carry_header(
        self,
        provider: str,
        expected_comment: str,
        tmp_path: Path,
    ):
        config = build_pipeline_config(provider=provider, complexity="standard")
        files = PipelineTemplateGenerator().generate_pipeline(config)

        written = write_pipeline_files(
            files,
            tmp_path,
            command=f"fluid forge --ci {provider}",
            tool_version="0.7.9",
        )
        assert written, f"no files written for {provider}"

        for path in written:
            first_line = path.read_text().splitlines()[0]
            assert first_line.startswith(
                f"{expected_comment} Generated by fluid-cli"
            ), f"{provider} header wrong: {first_line!r}"

    def test_preserves_original_body_after_header(
        self,
        provider: str,
        expected_comment: str,
        tmp_path: Path,
    ):
        config = build_pipeline_config(provider=provider, complexity="standard")
        files = PipelineTemplateGenerator().generate_pipeline(config)

        # Capture the original (unheaded) content so we can assert the body survives
        originals = {name: content for name, content in files.items()}

        written = write_pipeline_files(
            files,
            tmp_path,
            command=f"fluid forge --ci {provider}",
            tool_version="0.7.9",
        )

        for path in written:
            on_disk = path.read_text()
            # The original content must appear after the header
            rel = str(path.relative_to(tmp_path))
            assert originals[rel] in on_disk, (
                f"{provider} ({rel}): body not preserved"
            )


class TestWritePipelineFilesHeaderOptOut:
    def test_inject_header_false_produces_clean_output(self, tmp_path: Path):
        config = build_pipeline_config(provider="gitlab_ci", complexity="basic")
        files = PipelineTemplateGenerator().generate_pipeline(config)

        written = write_pipeline_files(
            files,
            tmp_path,
            command="fluid forge",
            tool_version="0.7.9",
            inject_header=False,
        )
        for path in written:
            first_line = path.read_text().splitlines()[0]
            # Should NOT be our header
            assert "Generated by fluid-cli" not in first_line


class TestBuildCIStatePayload:
    def test_records_provider_complexity_and_files(self, tmp_path: Path):
        config = build_pipeline_config(provider="github_actions", complexity="standard")
        files = PipelineTemplateGenerator().generate_pipeline(config)
        written = write_pipeline_files(
            files,
            tmp_path,
            command="fluid forge --ci github_actions",
            tool_version="0.7.9",
        )

        doc = build_ci_state_payload(
            provider="github_actions",
            complexity="standard",
            environments=["dev", "staging"],
            options={"enable_approvals": False},
            written_files=written,
            product_root=tmp_path,
        )

        assert doc.provider == "github_actions"
        assert doc.complexity == "standard"
        assert doc.environments == ["dev", "staging"]
        assert doc.options == {"enable_approvals": False}
        assert len(doc.files) == len(written)
        for entry in doc.files:
            assert "path" in entry
            assert "sha256" in entry
            assert len(entry["sha256"]) == 64  # full hex digest
            assert "size" in entry

    def test_paths_are_relative_to_product_root(self, tmp_path: Path):
        config = build_pipeline_config(provider="github_actions")
        files = PipelineTemplateGenerator().generate_pipeline(config)
        written = write_pipeline_files(
            files, tmp_path, command="fluid forge", tool_version="0.7.9"
        )

        doc = build_ci_state_payload(
            provider="github_actions",
            complexity="standard",
            environments=[],
            options={},
            written_files=written,
            product_root=tmp_path,
        )

        for entry in doc.files:
            assert not Path(entry["path"]).is_absolute()
            # GitHub Actions lives under .github/workflows/ (plus ancillary files like .env.ci.example)
            assert entry["path"].startswith(".github/workflows/") or entry["path"] == ".env.ci.example"


class TestWriteCIState:
    def test_writes_to_dot_fluid_ci_state_json(self, tmp_path: Path):
        doc = build_ci_state_payload(
            provider="github_actions",
            complexity="standard",
            environments=["dev"],
            options={},
            written_files=[],
            product_root=tmp_path,
        )
        result = write_ci_state(
            doc,
            tmp_path,
            command="fluid forge --ci github_actions",
            tool_version="0.7.9",
        )
        assert result == product_ci_state_path(tmp_path)
        assert result.exists()

    def test_payload_has_envelope_and_kind(self, tmp_path: Path):
        doc = build_ci_state_payload(
            provider="jenkins",
            complexity="advanced",
            environments=["prod"],
            options={"enable_approvals": True},
            written_files=[],
            product_root=tmp_path,
        )
        write_ci_state(
            doc,
            tmp_path,
            command="fluid forge --ci jenkins",
            tool_version="0.7.9",
        )
        data = json.loads(product_ci_state_path(tmp_path).read_text())
        assert data["schema_version"] == ENVELOPE_SCHEMA_VERSION
        assert data["kind"] == "CIState"
        assert data["provider"] == "jenkins"
        assert data["complexity"] == "advanced"
        assert data["environments"] == ["prod"]
        assert data["options"]["enable_approvals"] is True


class TestEndToEndGenerate:
    """Integration: generating a pipeline produces both header AND ci-state."""

    def test_github_actions_end_to_end(self, tmp_path: Path):
        config = build_pipeline_config(provider="github_actions", complexity="standard")
        files = PipelineTemplateGenerator().generate_pipeline(config)
        written = write_pipeline_files(
            files,
            tmp_path,
            command="fluid forge --ci github_actions --ci-complexity standard",
            tool_version="0.7.9",
        )

        doc = build_ci_state_payload(
            provider="github_actions",
            complexity="standard",
            environments=list(config.environments or []),
            options={
                "enable_approvals": bool(config.enable_approvals),
                "enable_security_scan": bool(config.enable_security_scan),
                "enable_marketplace_publishing": bool(config.enable_marketplace_publishing),
            },
            written_files=written,
            product_root=tmp_path,
        )
        write_ci_state(
            doc,
            tmp_path,
            command="fluid forge --ci github_actions --ci-complexity standard",
            tool_version="0.7.9",
        )

        # Every written file must have the header
        for path in written:
            assert path.read_text().startswith("# Generated by fluid-cli")

        # ci-state exists, references each file, and sha256s match
        state = json.loads(product_ci_state_path(tmp_path).read_text())
        assert len(state["files"]) == len(written)

        # Every recorded sha matches a real on-disk file
        recorded_paths = {Path(e["path"]).name for e in state["files"]}
        written_names = {p.name for p in written}
        assert recorded_paths == written_names
