# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
README Generator for FLUID Forge

Generates comprehensive README files for projects
"""

from typing import Dict

from ..core.interfaces import GenerationContext, Generator, ValidationResult


class ReadmeGenerator(Generator):
    """Generator for README.md files"""

    def generate(self, context: GenerationContext) -> Dict[str, str]:
        """Generate README.md file"""
        if context.project_config.get("copilot_generated_readme"):
            return {"README.md": context.project_config["copilot_generated_readme"]}

        project_config = context.project_config

        project_name = project_config.get("name", "FLUID Data Product")
        description = project_config.get("description", "A FLUID data product")
        template_name = project_config.get("template", "unknown")
        provider = project_config.get("provider", "local")
        owner = project_config.get("owner", "team")
        domain = project_config.get("domain", "data")

        readme_content = f"""# {project_name}

{description}

This is a FLUID data product created using the **{template_name}** template.

## Overview

- **Template**: {template_name}
- **Provider**: {provider}
- **Domain**: {domain}
- **Owner**: {owner}
- **Created**: {context.creation_time}
- **FLUID Version**: {context.project_config.get('fluid_version', '0.5.7')}

## Quick Start

1. **Install dependencies**:
   ```bash
   pip install -r requirements.txt
   ```

2. **Review the FLUID contract**:
   ```bash
   cat contract.fluid.yaml
   ```

3. **Run locally**:
   ```bash
   ./scripts/run-local.sh
   ```

## Project Structure

```
{project_name}/
├── contract.fluid.yaml    # FLUID contract definition
├── README.md             # This file
├── requirements.txt      # Python dependencies
├── config/              # Configuration files
├── src/                 # Source code
├── tests/               # Test suite
├── docs/                # Documentation
└── scripts/             # Utility scripts
```

## Development

### Local Setup

```bash
# Set up development environment
./scripts/setup-dev.sh

# Run tests
./scripts/run-tests.sh
```

### Configuration

Copy `.env.example` to `.env` and update with your configuration:

```bash
cp .env.example .env
# Edit .env with your settings
```

## Deployment

Refer to the provider-specific deployment documentation:
- [Local Development](docs/deployment/local.md)
- [Cloud Deployment](docs/deployment/cloud.md)

## Contributing

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Run tests
5. Submit a pull request

## Support

- **Documentation**: [FLUID Docs](https://fluid-forge.io)
- **Community**: [Discussions](https://github.com/fluid-forge/community)
- **Issues**: [GitHub Issues](https://github.com/your-org/{project_name}/issues)

---

*Generated by FLUID Forge v{context.forge_version}*
"""

        return {"README.md": readme_content}

    def validate_context(self, context: GenerationContext) -> ValidationResult:
        """Validate that context has required data"""
        if not context.project_config.get("name"):
            return False, ["Project name is required for README generation"]
        return True, []
