# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""GCP Dataflow transformation engine — generates Apache Beam pipeline scripts from FLUID contracts."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..base import (
    GenerationResult,
    Severity,
    TransformationEngine,
    TransformationIntent,
    ValidationIssue,
)
from ..registry import register_engine

try:
    from fluid_build.util.contract import get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")


_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"


def _build_column_list(exposes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Extract column definitions from exposes for skeleton generation."""
    columns: List[Dict[str, str]] = []
    for expose in exposes:
        schema = expose.get("schema") or expose.get("columns") or {}
        if isinstance(schema, list):
            for col in schema:
                columns.append({
                    "name": col.get("name", "unknown"),
                    "type": col.get("type", "string"),
                })
        elif isinstance(schema, dict):
            for col_name, col_def in schema.items():
                col_type = col_def if isinstance(col_def, str) else col_def.get("type", "string")
                columns.append({"name": col_name, "type": col_type})
    return columns


def _generate_pipeline(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> str:
    """Generate an Apache Beam pipeline script."""
    exposes = get_exposes(contract)
    expose_id = get_expose_id(exposes[0]) if exposes else "output"
    columns = _build_column_list(exposes)
    props = build.get("properties", {})

    # Use embedded SQL from build properties if available (embedded-logic pattern)
    embedded_sql = props.get("sql", "")

    col_comments = ""
    if columns:
        col_comments = "\n".join(
            f"#   - {c['name']} ({c['type']})" for c in columns
        )
        col_comments = f"# Target columns:\n{col_comments}\n"

    lines = [
        _HEADER,
        '"""',
        f"Apache Beam pipeline for '{expose_id}'.",
        "",
        "Run locally:",
        "    python pipeline.py --runner DirectRunner",
        "",
        "Run on Dataflow:",
        "    python pipeline.py \\",
        "        --runner DataflowRunner \\",
        "        --project my-gcp-project \\",
        "        --region us-central1 \\",
        "        --temp_location gs://my-bucket/temp/",
        '"""',
        "",
        "import argparse",
        "import logging",
        "",
        "import apache_beam as beam",
        "from apache_beam.options.pipeline_options import PipelineOptions",
        "from apache_beam.options.pipeline_options import SetupOptions",
        "",
        "",
    ]

    # Output schema definition
    if columns:
        lines.append("# ── Output schema ─────────────────────────────────────────────────\n")
        lines.append(col_comments)
        lines.append("OUTPUT_SCHEMA = {")
        for c in columns:
            lines.append(f'    "{c["name"]}": "{c["type"]}",')
        lines.append("}\n\n")

    # Transform DoFn
    lines.append("# ── Transform functions ───────────────────────────────────────────\n")
    lines.append(f"class TransformFn(beam.DoFn):")
    lines.append(f'    """Transform input records for \'{expose_id}\'."""\n')
    lines.append(f"    def process(self, element):")
    lines.append(f"        # TODO: Implement transformation logic")
    if columns:
        lines.append(f"        yield {{")
        for c in columns:
            lines.append(f'            "{c["name"]}": element.get("{c["name"]}"),  # TODO: transform')
        lines.append(f"        }}")
    else:
        lines.append(f"        yield element")
    lines.append("\n")

    if embedded_sql:
        lines.append("# Embedded SQL from contract build properties (for reference):")
        for sql_line in embedded_sql.split("\n")[:20]:
            lines.append(f"# {sql_line}")
        if embedded_sql.count("\n") > 20:
            lines.append("# ... (truncated)")
        lines.append("\n")

    # Main pipeline
    lines.append("# ── Pipeline ──────────────────────────────────────────────────────\n")
    lines.append("def run(argv=None):")
    lines.append('    """Build and run the Beam pipeline."""')
    lines.append("    parser = argparse.ArgumentParser()")
    lines.append("    parser.add_argument(")
    lines.append(f'        "--input",')
    lines.append(f'        default="gs://my-bucket/input/*",')
    lines.append(f'        help="Input file pattern or BigQuery table reference",')
    lines.append("    )")
    lines.append("    parser.add_argument(")
    lines.append(f'        "--output",')
    lines.append(f'        default="gs://my-bucket/output/{expose_id}",')
    lines.append(f'        help="Output location (GCS path or BigQuery table)",')
    lines.append("    )")
    lines.append("    known_args, pipeline_args = parser.parse_known_args(argv)\n")
    lines.append("    pipeline_options = PipelineOptions(pipeline_args)")
    lines.append("    pipeline_options.view_as(SetupOptions).save_main_session = True\n")
    lines.append("    with beam.Pipeline(options=pipeline_options) as p:")
    lines.append("        # ── Read ──")
    lines.append("        # TODO: Replace with your actual source (BigQuery, GCS, Pub/Sub, etc.)")
    lines.append("        records = (")
    lines.append("            p")
    lines.append(f'            | "ReadInput" >> beam.io.ReadFromText(known_args.input)')
    lines.append("        )\n")
    lines.append("        # ── Transform ──")
    lines.append("        transformed = (")
    lines.append("            records")
    lines.append(f'            | "Transform" >> beam.ParDo(TransformFn())')
    lines.append("        )\n")
    lines.append("        # ── Write ──")
    lines.append("        # TODO: Replace with your actual sink (BigQuery, GCS, etc.)")
    lines.append("        transformed | \"WriteOutput\" >> beam.io.WriteToText(  # noqa: E501")
    lines.append("            known_args.output,")
    lines.append(f'            file_name_suffix=".json",')
    lines.append("        )\n")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    logging.getLogger().setLevel(logging.INFO)")
    lines.append("    run()")
    lines.append("")

    return "\n".join(lines)


@register_engine
class DataflowEngine(TransformationEngine):
    """Generates GCP Dataflow (Apache Beam) pipeline scripts from a FLUID contract."""

    name = "dataflow"
    supported_patterns = ("hybrid-reference", "embedded-logic")
    supported_platforms = ("gcp",)

    def generate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
        *,
        build_index: int = 0,
        schema_context: Optional[Dict[str, Any]] = None,
        transformation_intent: Optional[TransformationIntent] = None,
    ) -> GenerationResult:
        files: GenerationResult = {}

        files["pipeline.py"] = _generate_pipeline(
            contract, build, transformation_intent=transformation_intent,
        )

        return files

    def validate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
    ) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []

        engine = build.get("engine") or build.get("type")
        if engine and engine != "dataflow":
            issues.append(ValidationIssue(
                message=f"Engine '{engine}' is not 'dataflow'",
                severity=Severity.ERROR,
                field="builds[].engine",
            ))

        pattern = build.get("pattern", "hybrid-reference")
        if pattern not in self.supported_patterns:
            issues.append(ValidationIssue(
                message=f"Pattern '{pattern}' is not supported by the dataflow engine",
                severity=Severity.WARNING,
                field="builds[].pattern",
            ))

        exposes = get_exposes(contract)
        if not exposes:
            issues.append(ValidationIssue(
                message="Contract has no exposes[] — dataflow needs at least one output to generate pipelines",
                severity=Severity.WARNING,
                field="exposes",
            ))

        return issues
