# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Shared utilities for code generation across all providers.

Common functions for DAG/pipeline generation to reduce code duplication
and ensure consistent behavior across AWS, GCP, and Snowflake providers.
"""

import re
from datetime import datetime
from typing import Dict, Any, List


def sanitize_identifier(name: str) -> str:
    """
    Sanitize a name to be a valid Python identifier.
    
    Converts to lowercase, replaces non-alphanumeric with underscores,
    and removes leading digits.
    
    Args:
        name: Original name
        
    Returns:
        Valid Python identifier
    """
    # Replace non-alphanumeric with underscores
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    
    # Remove leading digits
    sanitized = re.sub(r'^[0-9]+', '', sanitized)
    
    # Ensure not empty
    if not sanitized:
        sanitized = 'unnamed'
    
    return sanitized


def convert_schedule_to_cron(schedule: str) -> str:
    """
    Convert FLUID schedule notation to cron expression.
    
    Handles special keywords and passes through valid cron expressions.
    
    Args:
        schedule: FLUID schedule string (@hourly, @daily, cron expression)
        
    Returns:
        Cron expression (5 fields: minute hour day month weekday)
    """
    schedule_lower = schedule.lower().strip()
    
    # Handle special keywords
    keyword_map = {
        '@hourly': '0 * * * *',
        '@daily': '0 0 * * *',
        '@weekly': '0 0 * * 0',
        '@monthly': '0 0 1 * *',
        '@yearly': '0 0 1 1 *',
        '@annually': '0 0 1 1 *',
    }
    
    if schedule_lower in keyword_map:
        return keyword_map[schedule_lower]
    
    # Pass through cron expressions (5+ fields)
    if schedule.count(' ') >= 4:
        return schedule
    
    # Default to daily at 2 AM
    return '0 2 * * *'


def convert_schedule_to_airflow(schedule: str) -> str:
    """
    Convert FLUID schedule to Airflow schedule_interval format.
    
    Airflow accepts both cron and special keywords like @daily.
    
    Args:
        schedule: FLUID schedule string
        
    Returns:
        Airflow schedule_interval value
    """
    schedule_lower = schedule.lower().strip()
    
    # Airflow native keywords
    if schedule_lower in ('@hourly', '@daily', '@weekly', '@monthly', '@yearly', '@once'):
        return schedule_lower
    
    # Pass through cron expressions
    if schedule.count(' ') >= 4:
        return schedule
    
    # Default to daily
    return '@daily'


def generate_file_header(
    contract_id: str,
    contract_name: str,
    provider: str,
    **kwargs: Any
) -> str:
    """
    Generate standardized file header with metadata.
    
    Args:
        contract_id: Contract identifier
        contract_name: Human-readable contract name
        provider: Provider name (aws, gcp, snowflake)
        **kwargs: Additional metadata to include
        
    Returns:
        Multi-line docstring header
    """
    lines = [
        f'FLUID Generated Pipeline: {contract_name}',
        '',
        f'Contract ID: {contract_id}',
        f'Provider: {provider.upper()}',
    ]
    
    # Add any additional metadata
    for key, value in sorted(kwargs.items()):
        if value:
            # Format key for display
            display_key = key.replace('_', ' ').title()
            lines.append(f'{display_key}: {value}')
    
    lines.extend([
        '',
        'Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY',
        f'Generated: {datetime.utcnow().isoformat()}Z',
    ])
    
    # Wrap in docstring
    return '"""\n' + '\n'.join(lines) + '\n"""'


def escape_sql_for_python(sql: str) -> str:
    """
    Escape SQL string for safe inclusion in Python code.
    
    Handles quotes, backslashes, and other special characters.
    
    Args:
        sql: Raw SQL string
        
    Returns:
        Escaped SQL safe for Python string literals
    """
    # Escape backslashes first
    escaped = sql.replace('\\', '\\\\')
    # Escape double quotes
    escaped = escaped.replace('"', '\\"')
    # Escape triple quotes if present
    escaped = escaped.replace('"""', '\\"\\"\\""')
    
    return escaped


def generate_task_dependencies_code(
    tasks: List[Dict[str, Any]],
    syntax: str = 'airflow'
) -> str:
    """
    Generate task dependency declarations.
    
    Args:
        tasks: List of task specifications with 'taskId' and 'dependsOn'
        syntax: Dependency syntax style ('airflow', 'dagster', 'prefect')
        
    Returns:
        Code declaring task dependencies
    """
    if not tasks:
        return "# No task dependencies"
    
    dep_code = "# Task dependencies\n"
    
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        
        if not depends_on:
            continue
        
        if syntax == 'airflow':
            # Airflow: upstream >> downstream
            if len(depends_on) == 1:
                dep_code += f"{depends_on[0]} >> {task_id}\n"
            else:
                dep_code += f"[{', '.join(depends_on)}] >> {task_id}\n"
        
        elif syntax == 'dagster':
            # Dagster: handled via op() ins parameter
            pass
        
        elif syntax == 'prefect':
            # Prefect: implicit via execution order
            pass
    
    return dep_code.rstrip()


def validate_contract_for_export(contract: Dict[str, Any]) -> None:
    """
    Validate contract has required fields for code generation.
    
    Args:
        contract: FLUID contract
        
    Raises:
        ValueError: If contract is invalid
    """
    if not contract.get("orchestration"):
        raise ValueError("Contract missing 'orchestration' section")
    
    orchestration = contract["orchestration"]
    
    if not orchestration.get("tasks"):
        raise ValueError("Orchestration has no tasks")
    
    tasks = orchestration["tasks"]
    if not isinstance(tasks, list) or len(tasks) == 0:
        raise ValueError("Orchestration tasks must be a non-empty list")
    
    # Validate task IDs are unique
    task_ids = [t.get("taskId") for t in tasks]
    if len(task_ids) != len(set(task_ids)):
        raise ValueError("Duplicate task IDs found in orchestration")
    
    # Validate dependencies reference existing tasks
    task_id_set = set(task_ids)
    for task in tasks:
        depends_on = task.get("dependsOn", [])
        for dep in depends_on:
            if dep not in task_id_set:
                raise ValueError(f"Task '{task.get('taskId')}' depends on non-existent task '{dep}'")


def detect_circular_dependencies(tasks: List[Dict[str, Any]]) -> List[str]:
    """
    Detect circular dependencies in task graph.
    
    Args:
        tasks: List of task specifications
        
    Returns:
        List of task IDs involved in circular dependencies (empty if none)
    """
    # Build dependency graph
    graph = {}
    for task in tasks:
        task_id = task.get("taskId")
        graph[task_id] = task.get("dependsOn", [])
    
    # DFS to detect cycles
    visited = set()
    rec_stack = set()
    cycles = []
    
    def visit(node):
        if node in rec_stack:
            cycles.append(node)
            return True
        if node in visited:
            return False
        
        visited.add(node)
        rec_stack.add(node)
        
        for neighbor in graph.get(node, []):
            if visit(neighbor):
                cycles.append(node)
                return True
        
        rec_stack.remove(node)
        return False
    
    for task_id in graph:
        if task_id not in visited:
            visit(task_id)
    
    return list(set(cycles))


def calculate_code_metrics(code: str) -> Dict[str, Any]:
    """
    Calculate basic metrics for generated code.
    
    Args:
        code: Generated Python code
        
    Returns:
        Dictionary with metrics (lines, size, complexity estimate)
    """
    lines = code.split('\n')
    
    return {
        'line_count': len(lines),
        'non_empty_lines': sum(1 for line in lines if line.strip()),
        'comment_lines': sum(1 for line in lines if line.strip().startswith('#')),
        'docstring_lines': sum(1 for line in lines if '"""' in line or "'''" in line),
        'byte_size': len(code.encode('utf-8')),
        'function_count': code.count('def '),
        'class_count': code.count('class '),
    }
