# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Apache Spark transformation engine — generates PySpark transformation scripts from FLUID contracts."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..base import (
    GenerationResult,
    Severity,
    TransformationEngine,
    TransformationIntent,
    ValidationIssue,
)
from ..registry import register_engine

try:
    from fluid_build.util.contract import get_expose_id, get_exposes
except ImportError:  # pragma: no cover
    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")


_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"


def _build_column_list(exposes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Extract column definitions from exposes for skeleton generation."""
    columns: List[Dict[str, str]] = []
    for expose in exposes:
        schema = expose.get("schema") or expose.get("columns") or {}
        if isinstance(schema, list):
            for col in schema:
                columns.append({
                    "name": col.get("name", "unknown"),
                    "type": col.get("type", "string"),
                })
        elif isinstance(schema, dict):
            for col_name, col_def in schema.items():
                col_type = col_def if isinstance(col_def, str) else col_def.get("type", "string")
                columns.append({"name": col_name, "type": col_type})
    return columns


def _spark_type(fluid_type: str) -> str:
    """Map common FLUID types to PySpark types."""
    mapping = {
        "string": "StringType()",
        "integer": "IntegerType()",
        "int": "IntegerType()",
        "long": "LongType()",
        "float": "FloatType()",
        "double": "DoubleType()",
        "boolean": "BooleanType()",
        "date": "DateType()",
        "timestamp": "TimestampType()",
        "decimal": "DecimalType(18, 2)",
        "numeric": "DecimalType(18, 2)",
    }
    return mapping.get(fluid_type.lower(), "StringType()")


def _generate_spark_job(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> str:
    """Generate a PySpark transformation script."""
    exposes = get_exposes(contract)
    expose_id = get_expose_id(exposes[0]) if exposes else "output"
    columns = _build_column_list(exposes)
    props = build.get("properties", {})
    pattern = build.get("pattern", "hybrid-reference")

    # Use embedded SQL from build properties if available (embedded-logic pattern)
    embedded_sql = props.get("sql", "")

    col_comments = ""
    if columns:
        col_comments = "\n".join(
            f"#   - {c['name']} ({c['type']})" for c in columns
        )
        col_comments = f"# Target columns:\n{col_comments}\n"

    lines = [
        _HEADER,
        '"""',
        f"PySpark transformation job for '{expose_id}'.",
        "",
        "Run locally:",
        "    spark-submit spark_job.py",
        "",
        "Run on cluster:",
        "    spark-submit --master yarn --deploy-mode cluster spark_job.py",
        '"""',
        "",
        "from pyspark.sql import SparkSession",
        "from pyspark.sql import functions as F",
        "from pyspark.sql.types import (",
        "    StructType,",
        "    StructField,",
        "    StringType,",
        "    IntegerType,",
        "    LongType,",
        "    FloatType,",
        "    DoubleType,",
        "    BooleanType,",
        "    DateType,",
        "    TimestampType,",
        "    DecimalType,",
        ")",
        "",
        "",
    ]

    # Output schema definition
    if columns:
        lines.append("# ── Output schema ─────────────────────────────────────────────────\n")
        lines.append(col_comments)
        lines.append("OUTPUT_SCHEMA = StructType([")
        for c in columns:
            lines.append(f'    StructField("{c["name"]}", {_spark_type(c["type"])}, nullable=True),')
        lines.append("])\n\n")

    # Transformation function
    lines.append("# ── Transformation ────────────────────────────────────────────────\n")
    lines.append("def transform(spark, source_df):")
    lines.append(f'    """Apply transformations to produce \'{expose_id}\'."""')

    if embedded_sql:
        lines.append('    source_df.createOrReplaceTempView("source")')
        lines.append(f'    result_df = spark.sql("""\n{embedded_sql}\n    """)')
        lines.append("    return result_df\n")
    elif columns:
        lines.append("    # TODO: Implement transformation logic")
        lines.append("    result_df = source_df.select(")
        for c in columns:
            lines.append(f'        F.col("{c["name"]}"),  # TODO: transform or derive')
        lines.append("    )")
        lines.append("    return result_df\n")
    else:
        lines.append("    # TODO: Implement transformation logic")
        lines.append("    return source_df\n")

    # Multi-stage helper
    if pattern == "multi-stage" and transformation_intent and transformation_intent.stages:
        lines.append("")
        lines.append("# ── Multi-stage transformations ────────────────────────────────────\n")
        for stage in transformation_intent.stages:
            stage_name = stage.get("name", "stage")
            sql = stage.get("sql", "")
            lines.append(f"def stage_{stage_name}(spark, df):")
            lines.append(f'    """Stage: {stage_name}."""')
            if sql:
                lines.append(f'    df.createOrReplaceTempView("{stage_name}_input")')
                lines.append(f'    return spark.sql("""\n{sql}\n    """)')
            else:
                lines.append(f"    # TODO: Implement stage '{stage_name}'")
                lines.append(f"    return df")
            lines.append("\n")

    # Main entry point
    lines.append("")
    lines.append("# ── Main ──────────────────────────────────────────────────────────\n")
    lines.append("def main():")
    contract_name = contract.get("name", "fluid-spark-job")
    lines.append(f'    spark = SparkSession.builder.appName("{contract_name}").getOrCreate()\n')
    lines.append("    try:")
    lines.append("        # ── Read ──")
    lines.append("        # TODO: Replace with your actual data source (Parquet, Delta, JDBC, etc.)")
    lines.append('        source_df = spark.read.parquet("s3a://my-bucket/input/")\n')

    if pattern == "multi-stage" and transformation_intent and transformation_intent.stages:
        lines.append("        # ── Execute stages ──")
        lines.append("        df = source_df")
        for stage in transformation_intent.stages:
            stage_name = stage.get("name", "stage")
            lines.append(f"        df = stage_{stage_name}(spark, df)")
        lines.append("        result_df = df\n")
    else:
        lines.append("        # ── Transform ──")
        lines.append("        result_df = transform(spark, source_df)\n")

    lines.append("        # ── Write ──")
    lines.append("        # TODO: Replace with your actual data sink")
    lines.append("        result_df.write \\")
    lines.append("            .mode(\"overwrite\") \\")
    lines.append(f'            .parquet("s3a://my-bucket/output/{expose_id}/")\n')
    lines.append("    finally:")
    lines.append("        spark.stop()\n")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    lines.append("")

    return "\n".join(lines)


@register_engine
class SparkEngine(TransformationEngine):
    """Generates Apache Spark (PySpark) transformation scripts from a FLUID contract."""

    name = "spark"
    supported_patterns = ("hybrid-reference", "embedded-logic", "multi-stage")

    def generate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
        *,
        build_index: int = 0,
        schema_context: Optional[Dict[str, Any]] = None,
        transformation_intent: Optional[TransformationIntent] = None,
    ) -> GenerationResult:
        files: GenerationResult = {}

        files["spark_job.py"] = _generate_spark_job(
            contract, build, transformation_intent=transformation_intent,
        )

        return files

    def validate(
        self,
        contract: Dict[str, Any],
        build: Dict[str, Any],
    ) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []

        engine = build.get("engine") or build.get("type")
        if engine and engine != "spark":
            issues.append(ValidationIssue(
                message=f"Engine '{engine}' is not 'spark'",
                severity=Severity.ERROR,
                field="builds[].engine",
            ))

        pattern = build.get("pattern", "hybrid-reference")
        if pattern not in self.supported_patterns:
            issues.append(ValidationIssue(
                message=f"Pattern '{pattern}' is not supported by the spark engine",
                severity=Severity.WARNING,
                field="builds[].pattern",
            ))

        exposes = get_exposes(contract)
        if not exposes:
            issues.append(ValidationIssue(
                message="Contract has no exposes[] — spark needs at least one output to generate jobs",
                severity=Severity.WARNING,
                field="exposes",
            ))

        return issues
