# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate SQL script files from FLUID contract builds."""

from __future__ import annotations

from typing import Any, Dict, Optional

from ..base import GenerationResult, TransformationIntent

_HEADER = "-- Generated by fluid generate — do not edit manually.\n-- Regenerate with: fluid generate\n"


def generate_scripts(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate SQL script files."""
    pattern = build.get("pattern", "embedded-logic")

    if transformation_intent and transformation_intent.stages:
        return _generate_from_intent(contract, transformation_intent)

    if pattern == "multi-stage":
        return _generate_multi_stage(contract, build)
    else:
        return _generate_embedded(contract, build)


def _generate_embedded(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Generate a single SQL script from embedded-logic."""
    properties = build.get("properties", {})
    sql = properties.get("sql", "")
    build_id = build.get("id", "main")
    contract_id = contract.get("id", "unknown")

    header = (
        f"{_HEADER}"
        f"-- Contract: {contract_id}\n"
        f"-- Build: {build_id}\n\n"
    )

    if sql:
        return {f"{build_id}.sql": header + sql.strip() + "\n"}

    return {
        f"{build_id}.sql": (
            header
            + "-- TODO: Add transformation SQL\n"
            + "SELECT 1;\n"
        )
    }


def _generate_multi_stage(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Generate ordered SQL scripts from multi-stage build."""
    files: GenerationResult = {}
    properties = build.get("properties", {})
    stages = properties.get("stages", [])
    contract_id = contract.get("id", "unknown")

    for idx, stage in enumerate(stages):
        if not isinstance(stage, dict):
            continue

        name = stage.get("name", f"stage_{idx}")
        sql = stage.get("properties", {}).get("sql", "")
        depends_on = stage.get("dependsOn", [])

        header = (
            f"{_HEADER}"
            f"-- Contract: {contract_id}\n"
            f"-- Stage: {name} ({idx + 1}/{len(stages)})\n"
        )
        if depends_on:
            header += f"-- Depends on: {', '.join(depends_on)}\n"
        header += "\n"

        if sql:
            content = header + sql.strip() + "\n"
        else:
            content = (
                header
                + f"-- TODO: Add transformation SQL for stage '{name}'\n"
                + "SELECT 1;\n"
            )

        # Prefix with index for execution order
        files[f"{idx + 1:02d}_{name}.sql"] = content

    return files


def _generate_from_intent(
    contract: Dict[str, Any],
    intent: TransformationIntent,
) -> GenerationResult:
    """Generate SQL scripts from AI-produced TransformationIntent."""
    files: GenerationResult = {}
    contract_id = contract.get("id", "unknown")

    for idx, stage in enumerate(intent.stages):
        name = stage.get("name", f"stage_{idx}")
        sql = stage.get("sql", "")
        depends_on = stage.get("depends_on", [])

        header = (
            f"{_HEADER}"
            f"-- Contract: {contract_id}\n"
            f"-- Stage: {name}\n"
        )
        if depends_on:
            header += f"-- Depends on: {', '.join(depends_on)}\n"
        header += "\n"

        if sql:
            content = header + sql.strip() + "\n"
        else:
            content = (
                header
                + f"-- TODO: AI could not generate SQL for stage '{name}'\n"
                + "SELECT 1;\n"
            )

        files[f"{idx + 1:02d}_{name}.sql"] = content

    return files
