# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Industry skills loader — generates .fluid/skills.yaml for workspace projects.

Each industry has a bundled YAML file with domain taxonomy, canonical model,
compliance requirements, and common data sources.  The shared ``_tools.yaml``
is merged into every generated skills file so agents know which platforms,
transformations, orchestration engines, and formats FLUID supports.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

_SKILLS_DIR = Path(__file__).parent

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def load_tools() -> Dict[str, Any]:
    """Load the shared FLUID tool catalog from ``_tools.yaml``."""
    tools_path = _SKILLS_DIR / "_tools.yaml"
    with tools_path.open() as f:
        data = yaml.safe_load(f)
    return data.get("tools", {})


def load_industry_skills(name: str) -> Dict[str, Any]:
    """Load an industry-specific skills file by name (e.g. ``telco``).

    Returns the raw YAML dict (without the tools section — that is merged
    separately via :func:`generate_skills_file`).

    Raises ``FileNotFoundError`` if the industry YAML does not exist.
    """
    path = _SKILLS_DIR / f"{name}.yaml"
    if not path.exists():
        raise FileNotFoundError(f"No industry skills file for '{name}' at {path}")
    with path.open() as f:
        return yaml.safe_load(f)


def list_industries() -> List[Dict[str, str]]:
    """Return a list of available industry choices.

    Each entry has ``key`` (file stem), ``label``, and ``description``.
    The list is built dynamically from YAML files in this directory
    (excluding ``_tools.yaml``).

    An ``other`` entry is always appended as the last option.
    """
    choices: List[Dict[str, str]] = []
    for path in sorted(_SKILLS_DIR.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        try:
            with path.open() as f:
                data = yaml.safe_load(f)
            industry = data.get("industry", {})
            choices.append(
                {
                    "key": path.stem,
                    "label": industry.get("label", path.stem.title()),
                    "description": industry.get("description", ""),
                }
            )
        except Exception:
            continue
    choices.append(
        {
            "key": "other",
            "label": "Other / General",
            "description": "No industry-specific skills — tools catalog only",
        }
    )
    return choices


def generate_skills_file(
    industry: Optional[str],
    output_dir: Path,
    *,
    cli_version: Optional[str] = None,
) -> Path:
    """Generate ``.fluid/skills.yaml`` by merging industry data with the tool catalog.

    Parameters
    ----------
    industry:
        Industry key (e.g. ``telco``, ``retail``).  ``None`` or ``"other"``
        produces a tools-only file.
    output_dir:
        Workspace root directory.  The file is written to
        ``<output_dir>/.fluid/skills.yaml``.
    cli_version:
        FLUID CLI version stamp.  Defaults to the installed version.

    Returns
    -------
    Path to the generated skills file.
    """
    if cli_version is None:
        try:
            from fluid_build import __version__

            cli_version = __version__
        except ImportError:
            cli_version = "unknown"

    tools = load_tools()

    if industry and industry != "other":
        skills = load_industry_skills(industry)
    else:
        skills = {}

    skills["_version"] = cli_version
    skills["_generated"] = datetime.date.today().isoformat()
    skills["tools"] = tools

    fluid_dir = output_dir / ".fluid"
    fluid_dir.mkdir(parents=True, exist_ok=True)
    out_path = fluid_dir / "skills.yaml"

    header = (
        "# Auto-generated by fluid init — shared agentic knowledge for this project.\n"
        "# All FLUID agents read this file for project context.\n"
        "# Update with: fluid skills update\n"
    )
    with out_path.open("w") as f:
        f.write(header)
        yaml.dump(skills, f, default_flow_style=False, sort_keys=False)

    return out_path


def compile_skill(merged: Dict[str, Any]) -> Dict[str, Any]:
    """Extract only the prompt-relevant fields from a merged skills dict.

    Slice UX-J: the full ``.fluid/skills.yaml`` carries many fields
    that are only used locally (``common_data_sources``, ``tools``,
    ``key_entities`` on each domain, etc.).  Only four sub-fields
    actually reach the LLM prompt via ``build_user_prompt`` in
    ``forge_copilot_prompts.py:204-221``:

    1. ``industry.label``
    2. ``canonical_model.label`` (+ optional ``supporting[].label``)
    3. ``domains[].label``
    4. ``compliance[]``

    ``compile_skill`` extracts exactly those, producing a dict that
    is typically 10-20x smaller than the raw YAML.  The compiled form
    is written to ``.fluid/skills.compiled.json`` by the
    ``fluid skills compile`` subcommand and memoized in-process by
    ``forge_copilot_skills_cache.load_compiled_skills``.
    """
    compiled: Dict[str, Any] = {}

    industry = merged.get("industry", {})
    if industry.get("label"):
        compiled["industry"] = industry["label"]

    canonical = merged.get("canonical_model", {})
    if canonical.get("label"):
        compiled["canonical_model"] = canonical["label"]
    supporting = canonical.get("supporting") or []
    if supporting:
        labels = [s.get("label") or s.get("name") for s in supporting if isinstance(s, dict)]
        labels = [l for l in labels if l]
        if labels:
            compiled["supporting_standards"] = labels

    domains = merged.get("domains") or []
    if domains:
        compiled["domains"] = [
            d.get("label") or d.get("name")
            for d in domains
            if isinstance(d, dict) and (d.get("label") or d.get("name"))
        ]

    compliance = merged.get("compliance") or []
    if compliance:
        compiled["compliance"] = list(compliance)

    return compiled


def refresh_tools_section(skills_path: Path, *, cli_version: Optional[str] = None) -> None:
    """Update only the ``tools`` and ``_version`` keys in an existing skills file.

    Preserves all other content (industry, domains, compliance, etc.).
    """
    if cli_version is None:
        try:
            from fluid_build import __version__

            cli_version = __version__
        except ImportError:
            cli_version = "unknown"

    with skills_path.open() as f:
        data = yaml.safe_load(f) or {}

    data["tools"] = load_tools()
    data["_version"] = cli_version
    data["_generated"] = datetime.date.today().isoformat()

    header = (
        "# Auto-generated by fluid init — shared agentic knowledge for this project.\n"
        "# All FLUID agents read this file for project context.\n"
        "# Update with: fluid skills update\n"
    )
    with skills_path.open("w") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
