# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Dagster Pipeline Generation for GCP Provider.

Generates Python pipeline code from FLUID contracts for Dagster on GCP.

Supports:
- BigQuery ops with type safety
- Cloud Storage resources
- Pub/Sub integration
- Dataflow pipelines
"""

from typing import Dict, Any, List
from datetime import datetime


def generate_dagster_pipeline(
    contract: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """
    Generate Dagster pipeline Python code from FLUID contract.
    
    Args:
        contract: FLUID contract with orchestration section
        project: GCP project ID
        region: GCP region
        
    Returns:
        Python code for Dagster pipeline
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")
    
    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")
    
    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")
    
    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]
    
    # Generate pipeline code
    code = _generate_header(contract_id, contract_name, schedule, timezone, project, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_resources(project, region)
    code += "\n\n"
    code += _generate_ops(provider_tasks, project, region)
    code += "\n\n"
    code += _generate_job(contract_id, provider_tasks, schedule, timezone)
    
    return code


def _generate_header(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str,
    project: str,
    region: str
) -> str:
    """Generate file header with metadata."""
    return f'''"""
FLUID Generated Dagster Pipeline: {contract_name}

Contract ID: {contract_id}
Schedule: {schedule}
Timezone: {timezone}
GCP Project: {project}
GCP Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}Z
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return '''from dagster import (
    op,
    job,
    resource,
    In,
    Out,
    Nothing,
    DagsterEventType,
    ScheduleDefinition,
)
from google.cloud import bigquery, storage, pubsub_v1, dataflow_v1beta3
import json
import logging

logger = logging.getLogger(__name__)'''


def _generate_resources(project: str, region: str) -> str:
    """Generate GCP resource definitions."""
    return f'''# GCP Resources
@resource
def gcp_project():
    """GCP project ID resource."""
    return "{project}"

@resource
def gcp_region():
    """GCP region resource."""
    return "{region}"

@resource
def bigquery_client(context):
    """BigQuery client resource."""
    project = context.resources.gcp_project
    return bigquery.Client(project=project)

@resource
def gcs_client(context):
    """Cloud Storage client resource."""
    project = context.resources.gcp_project
    return storage.Client(project=project)

@resource
def pubsub_client(context):
    """Pub/Sub client resource."""
    project = context.resources.gcp_project
    return pubsub_v1.PublisherClient()'''


def _generate_ops(
    tasks: List[Dict[str, Any]],
    project: str,
    region: str
) -> str:
    """Generate op definitions."""
    ops_code = "# Pipeline Ops\n"
    
    for task in tasks:
        ops_code += _generate_single_op(task, project, region)
        ops_code += "\n\n"
    
    return ops_code.rstrip()


def _generate_single_op(
    task: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """Generate code for a single op."""
    task.get("taskId")
    action = task.get("action", "")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])
    
    # Parse action
    action_parts = action.split(".")
    if len(action_parts) < 3:
        return _generate_generic_op(task, project, region)
    
    service = action_parts[1]
    operation = action_parts[2]
    
    # Determine input dependencies
    if depends_on:
        dep_items = ', '.join(['"dep_{}": In(Nothing)'.format(d) for d in depends_on])
        ins_def = f"ins={{{dep_items}}}, "
    else:
        ins_def = ""
    
    # Map to appropriate op
    if service == "bigquery":
        return _generate_bigquery_op(task, operation, params, ins_def)
    elif service == "gcs" or service == "storage":
        return _generate_gcs_op(task, operation, params, ins_def)
    elif service == "pubsub":
        return _generate_pubsub_op(task, operation, params, ins_def)
    else:
        return _generate_generic_op(task, project, region)


def _generate_bigquery_op(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    ins_def: str
) -> str:
    """Generate BigQuery op code."""
    task_id = task.get("taskId")
    
    if operation == "create_dataset":
        dataset_id = params.get("dataset_id", "unknown_dataset")
        location = params.get("location", "US")
        return f'''@op({ins_def}required_resource_keys={{"bigquery_client", "gcp_project"}})
def {task_id}(context):
    """Create BigQuery dataset: {dataset_id}"""
    client = context.resources.bigquery_client
    dataset = bigquery.Dataset(f"{{{{context.resources.gcp_project}}}}.{dataset_id}")
    dataset.location = "{location}"
    
    try:
        dataset = client.create_dataset(dataset, exists_ok=True)
        context.log.info(f"Created dataset {{{{dataset.dataset_id}}}}")
        return dataset.dataset_id
    except Exception as e:
        context.log.error(f"Failed to create dataset: {{{{e}}}}")
        raise'''
    
    elif operation == "query" or operation == "run_query":
        query_sql = params.get("query", "SELECT 1")
        # Escape for Python string
        query_escaped = query_sql.replace('\\', '\\\\').replace('"', '\\"')
        
        return f'''@op({ins_def}required_resource_keys={{"bigquery_client"}})
def {task_id}(context):
    """Run BigQuery query"""
    client = context.resources.bigquery_client
    query = "{query_escaped}"
    
    try:
        query_job = client.query(query)
        results = query_job.result()
        row_count = results.total_rows
        context.log.info(f"Query completed: {{{{row_count}}}} rows")
        return row_count
    except Exception as e:
        context.log.error(f"Query failed: {{{{e}}}}")
        raise'''
    
    else:
        return _generate_generic_op(task, None, None)


def _generate_gcs_op(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    ins_def: str
) -> str:
    """Generate Cloud Storage op code."""
    task_id = task.get("taskId")
    
    if operation == "create_bucket" or operation == "ensure_bucket":
        bucket_name = params.get("bucket", "unknown-bucket")
        location = params.get("location", "US")
        
        return f'''@op({ins_def}required_resource_keys={{"gcs_client"}})
def {task_id}(context):
    """Create GCS bucket: {bucket_name}"""
    client = context.resources.gcs_client
    bucket = client.bucket("{bucket_name}")
    bucket.location = "{location}"
    
    try:
        if not bucket.exists():
            bucket.create()
            context.log.info(f"Created bucket {{bucket.name}}")
        else:
            context.log.info(f"Bucket {{bucket.name}} already exists")
        return bucket.name
    except Exception as e:
        context.log.error(f"Failed to create bucket: {{e}}")
        raise'''
    
    else:
        return _generate_generic_op(task, None, None)


def _generate_pubsub_op(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    ins_def: str
) -> str:
    """Generate Pub/Sub op code."""
    task_id = task.get("taskId")
    
    if operation == "create_topic":
        topic_name = params.get("topic", "unknown-topic")
        return f'''@op({ins_def}required_resource_keys={{"pubsub_client", "gcp_project"}})
def {task_id}(context):
    """Create Pub/Sub topic: {topic_name}"""
    client = context.resources.pubsub_client
    topic_path = client.topic_path(context.resources.gcp_project, "{topic_name}")
    
    try:
        topic = client.create_topic(request={{"name": topic_path}})
        context.log.info(f"Created topic {{topic.name}}")
        return topic.name
    except Exception as e:
        if "already exists" in str(e).lower():
            context.log.info(f"Topic {{topic_path}} already exists")
            return topic_path
        context.log.error(f"Failed to create topic: {{e}}")
        raise'''
    
    else:
        return _generate_generic_op(task, None, None)


def _generate_generic_op(
    task: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """Generate generic op."""
    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])
    
    if depends_on:
        dep_items = ', '.join(['"dep_{}": In(Nothing)'.format(d) for d in depends_on])
        ins_def = f", ins={{{dep_items}}}"
    else:
        ins_def = ""
    
    return f'''@op({ins_def})
def {task_id}(context):
    """Generic op: {action}"""
    context.log.info(f"Action: {action}")
    context.log.info(f"Params: {params!r}")
    return True'''


def _generate_job(
    contract_id: str,
    tasks: List[Dict[str, Any]],
    schedule: str,
    timezone: str
) -> str:
    """Generate job and schedule definitions."""
    # Build op call graph
    op_calls = []
    dependencies = {}
    
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        
        if depends_on:
            # Op with dependencies
            dep_args = ", ".join([f"dep_{d}={d}_result" for d in depends_on])
            op_calls.append(f"    {task_id}_result = {task_id}({dep_args})")
            dependencies[task_id] = depends_on
        else:
            # Independent op
            op_calls.append(f"    {task_id}_result = {task_id}()")
    
    op_calls_str = "\n".join(op_calls)
    
    # Convert cron to Dagster schedule
    cron_schedule = _convert_schedule(schedule)
    
    job_name = _sanitize_name(contract_id)
    
    return f'''# Job definition
@job(
    resource_defs={{
        "gcp_project": gcp_project,
        "gcp_region": gcp_region,
        "bigquery_client": bigquery_client,
        "gcs_client": gcs_client,
        "pubsub_client": pubsub_client,
    }},
    tags={{
        "fluid": "auto-generated",
        "contract_id": "{contract_id}",
        "provider": "gcp",
    }},
)
def {job_name}():
    """{contract_id} pipeline on GCP."""
{op_calls_str}

# Schedule
{job_name}_schedule = ScheduleDefinition(
    job={job_name},
    cron_schedule="{cron_schedule}",
    execution_timezone="{timezone}",
)'''


def _convert_schedule(schedule: str) -> str:
    """Convert FLUID schedule to Dagster cron schedule."""
    # Handle special keywords
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"
    
    # Pass through cron expressions
    if schedule.count(" ") >= 4:
        return schedule
    
    # Default to daily
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    """Sanitize name for Python identifier."""
    import re
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)
