# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for GCP Provider.

Generates Python flow code from FLUID contracts for Prefect on GCP.

Supports:
- BigQuery tasks with retries
- Cloud Storage operations
- Pub/Sub messaging
- Deployment configuration
"""

from typing import Dict, Any, List
from datetime import datetime
from fluid_build.cli.console import cprint, info, success


def generate_prefect_flow(
    contract: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """
    Generate Prefect flow Python code from FLUID contract.
    
    Args:
        contract: FLUID contract with orchestration section
        project: GCP project ID
        region: GCP region
        
    Returns:
        Python code for Prefect flow
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")
    
    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")
    
    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")
    
    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]
    
    # Generate flow code
    code = _generate_header(contract_id, contract_name, schedule, timezone, project, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_config(project, region)
    code += "\n\n"
    code += _generate_tasks(provider_tasks, project, region)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)
    
    return code


def _generate_header(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str,
    project: str,
    region: str
) -> str:
    """Generate file header with metadata."""
    return f'''"""
FLUID Generated Prefect Flow: {contract_name}

Contract ID: {contract_id}
Schedule: {schedule}
Timezone: {timezone}
GCP Project: {project}
GCP Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}Z
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return '''from prefect import flow, task
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
from google.cloud import bigquery, storage, pubsub_v1
import logging
from datetime import timedelta

logger = logging.getLogger(__name__)'''


def _generate_config(project: str, region: str) -> str:
    """Generate configuration constants."""
    return f'''# GCP Configuration
GCP_PROJECT = "{project}"
GCP_REGION = "{region}"'''


def _generate_tasks(
    tasks: List[Dict[str, Any]],
    project: str,
    region: str
) -> str:
    """Generate task definitions."""
    tasks_code = "# Prefect Tasks\n"
    
    for task_spec in tasks:
        tasks_code += _generate_single_task(task_spec, project, region)
        tasks_code += "\n\n"
    
    return tasks_code.rstrip()


def _generate_single_task(
    task_spec: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """Generate code for a single task."""
    task_spec.get("taskId")
    action = task_spec.get("action", "")
    params = task_spec.get("params", {})
    
    # Parse action
    action_parts = action.split(".")
    if len(action_parts) < 3:
        return _generate_generic_task(task_spec, project, region)
    
    service = action_parts[1]
    operation = action_parts[2]
    
    # Map to appropriate task
    if service == "bigquery":
        return _generate_bigquery_task(task_spec, operation, params)
    elif service == "gcs" or service == "storage":
        return _generate_gcs_task(task_spec, operation, params)
    elif service == "pubsub":
        return _generate_pubsub_task(task_spec, operation, params)
    else:
        return _generate_generic_task(task_spec, project, region)


def _generate_bigquery_task(
    task_spec: Dict[str, Any],
    operation: str,
    params: Dict[str, Any]
) -> str:
    """Generate BigQuery task code."""
    task_id = task_spec.get("taskId")
    
    if operation == "create_dataset":
        dataset_id = params.get("dataset_id", "unknown_dataset")
        location = params.get("location", "US")
        
        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=600)
def {task_id}():
    """Create BigQuery dataset: {dataset_id}"""
    client = bigquery.Client(project=GCP_PROJECT)
    dataset = bigquery.Dataset(f"{{GCP_PROJECT}}.{dataset_id}")
    dataset.location = "{location}"
    
    try:
        dataset = client.create_dataset(dataset, exists_ok=True)
        logger.info(f"Created dataset {{dataset.dataset_id}}")
        return dataset.dataset_id
    except Exception as e:
        logger.error(f"Failed to create dataset: {{e}}")
        raise'''
    
    elif operation == "query" or operation == "run_query":
        query_sql = params.get("query", "SELECT 1").replace('"', '\\"')
        
        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=1800)
def {task_id}():
    """Run BigQuery query"""
    client = bigquery.Client(project=GCP_PROJECT)
    query = """{query_sql}"""
    
    try:
        query_job = client.query(query)
        results = query_job.result()
        row_count = results.total_rows
        logger.info(f"Query completed: {{row_count}} rows")
        return row_count
    except Exception as e:
        logger.error(f"Query failed: {{e}}")
        raise'''
    
    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_gcs_task(
    task_spec: Dict[str, Any],
    operation: str,
    params: Dict[str, Any]
) -> str:
    """Generate Cloud Storage task code."""
    task_id = task_spec.get("taskId")
    
    if operation == "create_bucket" or operation == "ensure_bucket":
        bucket_name = params.get("bucket", "unknown-bucket")
        location = params.get("location", "US")
        
        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=300)
def {task_id}():
    """Create GCS bucket: {bucket_name}"""
    client = storage.Client(project=GCP_PROJECT)
    bucket = client.bucket("{bucket_name}")
    bucket.location = "{location}"
    
    try:
        if not bucket.exists():
            bucket.create()
            logger.info(f"Created bucket {{bucket.name}}")
        else:
            logger.info(f"Bucket {{bucket.name}} already exists")
        return bucket.name
    except Exception as e:
        logger.error(f"Failed to create bucket: {{e}}")
        raise'''
    
    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_pubsub_task(
    task_spec: Dict[str, Any],
    operation: str,
    params: Dict[str, Any]
) -> str:
    """Generate Pub/Sub task code."""
    task_id = task_spec.get("taskId")
    
    if operation == "create_topic":
        topic_name = params.get("topic", "unknown-topic")
        
        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=300)
def {task_id}():
    """Create Pub/Sub topic: {topic_name}"""
    client = pubsub_v1.PublisherClient()
    topic_path = client.topic_path(GCP_PROJECT, "{topic_name}")
    
    try:
        topic = client.create_topic(request={{"name": topic_path}})
        logger.info(f"Created topic {{topic.name}}")
        return topic.name
    except Exception as e:
        if "already exists" in str(e).lower():
            logger.info(f"Topic {{topic_path}} already exists")
            return topic_path
        logger.error(f"Failed to create topic: {{e}}")
        raise'''
    
    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_generic_task(
    task_spec: Dict[str, Any],
    project: str,
    region: str
) -> str:
    """Generate generic task."""
    task_id = task_spec.get("taskId")
    action = task_spec.get("action")
    params = task_spec.get("params", {})
    
    return f'''@task(retries=2, retry_delay_seconds=30)
def {task_id}():
    """Generic task: {action}"""
    logger.info(f"Action: {action}")
    logger.info(f"Params: {params!r}")
    return True'''


def _generate_flow(
    contract_id: str,
    contract_name: str,
    tasks: List[Dict[str, Any]]
) -> str:
    """Generate flow definition."""
    flow_name = _sanitize_name(contract_id)
    
    # Build task execution sequence
    task_executions = []
    task_results = {}
    
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        
        if depends_on:
            # Wait for dependencies (in Prefect, execution order is implicit)
            for dep in depends_on:
                if dep not in task_results:
                    task_results[dep] = f"{dep}_result"
            task_executions.append(f"    {task_id}_result = {task_id}()")
        else:
            task_executions.append(f"    {task_id}_result = {task_id}()")
        
        task_results[task_id] = f"{task_id}_result"
    
    task_exec_str = "\n".join(task_executions)
    
    return f'''# Flow definition
@flow(
    name="{flow_name}",
    description="{contract_name}",
    retries=1,
    retry_delay_seconds=60,
)
def {flow_name}_flow():
    """{contract_name} flow on GCP."""
{task_exec_str}
    
    logger.info("Flow completed successfully")
    return True'''


def _generate_deployment(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str
) -> str:
    """Generate deployment configuration."""
    flow_name = _sanitize_name(contract_id)
    cron_schedule = _convert_schedule(schedule)
    
    return f'''# Deployment configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name="{flow_name}-deployment",
        version="1.0",
        tags=["fluid", "auto-generated", "gcp", "{contract_id}"],
        schedule=CronSchedule(
            cron="{cron_schedule}",
            timezone="{timezone}",
        ),
        work_queue_name="default",
    )
    
    # To deploy: python {flow_name}_flow.py
    deployment.apply()
    
    success(f"Deployment created: {{deployment.name}}")
    cprint(f"   Schedule: {cron_schedule} ({timezone})")
    cprint(f"   Run: prefect deployment run '{flow_name}_flow/{flow_name}-deployment'")'''


def _convert_schedule(schedule: str) -> str:
    """Convert FLUID schedule to cron schedule."""
    # Handle special keywords
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"
    
    # Pass through cron expressions
    if schedule.count(" ") >= 4:
        return schedule
    
    # Default to daily
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    """Sanitize name for Python identifier."""
    import re
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)
