# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Airflow DAG Generation for AWS Provider.

Generates Python DAG files from FLUID contracts for deployment to MWAA
(Amazon Managed Workflows for Apache Airflow) or self-hosted Airflow.

Supports:
- Provider action tasks
- Task dependencies  
- Schedule configuration
- AWS-specific operators (S3, Glue, Athena, Redshift, Lambda)
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import json


def generate_airflow_dag(
    contract: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """
    Generate Airflow DAG Python code from FLUID contract.
    
    Args:
        contract: FLUID contract with orchestration section
        account_id: AWS account ID
        region: AWS region
        
    Returns:
        Python code for Airflow DAG
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")
    
    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")
    
    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")
    orchestration.get("engine", "airflow")
    
    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]
    
    # Generate DAG code
    dag_code = _generate_dag_header(contract_id, contract_name, schedule, timezone, account_id, region)
    dag_code += "\n\n"
    dag_code += _generate_dag_imports()
    dag_code += "\n\n"
    dag_code += _generate_dag_definition(contract_id, contract_name, schedule, timezone)
    dag_code += "\n\n"
    dag_code += _generate_task_definitions(provider_tasks, account_id, region)
    dag_code += "\n\n"
    dag_code += _generate_task_dependencies(provider_tasks)
    
    return dag_code


def _generate_dag_header(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str,
    account_id: str,
    region: str
) -> str:
    """Generate DAG file header with metadata."""
    return f'''"""
FLUID Generated DAG: {contract_name}

Contract ID: {contract_id}
Schedule: {schedule}
Timezone: {timezone}
AWS Account: {account_id}
AWS Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}
"""'''


def _generate_dag_imports() -> str:
    """Generate import statements."""
    return '''from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.operators.s3 import S3CreateBucketOperator
from airflow.providers.amazon.aws.operators.glue import GlueJobOperator
from airflow.providers.amazon.aws.operators.athena import AthenaOperator
from airflow.providers.amazon.aws.operators.redshift_data import RedshiftDataOperator
from airflow.providers.amazon.aws.operators.lambda_function import LambdaInvokeFunctionOperator
import json
import logging

logger = logging.getLogger(__name__)'''


def _generate_dag_definition(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str
) -> str:
    """Generate DAG definition with default arguments."""
    # Convert cron to Airflow schedule
    airflow_schedule = _convert_schedule(schedule)
    
    return f'''# Default DAG arguments
default_args = {{
    'owner': 'fluid-forge',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
    'execution_timeout': timedelta(hours=2),
}}

# DAG definition
dag = DAG(
    dag_id='{_sanitize_dag_id(contract_id)}',
    default_args=default_args,
    description='{contract_name}',
    schedule_interval='{airflow_schedule}',
    start_date=datetime(2026, 1, 1, tzinfo=ZoneInfo('{timezone}')),
    catchup=False,
    tags=['fluid', 'auto-generated', '{contract_id}'],
)'''


def _generate_task_definitions(
    tasks: List[Dict[str, Any]],
    account_id: str,
    region: str
) -> str:
    """Generate task definitions."""
    task_code = "# Task definitions\n"
    
    for task in tasks:
        task_code += _generate_single_task(task, account_id, region)
        task_code += "\n\n"
    
    return task_code.rstrip()


def _generate_single_task(
    task: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate code for a single task."""
    task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})
    
    # Parse action (e.g., "aws.s3.ensure_bucket")
    action_parts = action.split(".")
    if len(action_parts) < 3:
        # Fallback to PythonOperator
        return _generate_python_task(task, account_id, region)
    
    service = action_parts[1]
    operation = action_parts[2]
    
    # Map to appropriate Airflow operator
    if service == "s3":
        return _generate_s3_task(task, operation, params, account_id, region)
    elif service == "glue":
        return _generate_glue_task(task, operation, params, account_id, region)
    elif service == "athena":
        return _generate_athena_task(task, operation, params, account_id, region)
    elif service == "redshift":
        return _generate_redshift_task(task, operation, params, account_id, region)
    elif service == "lambda":
        return _generate_lambda_task(task, operation, params, account_id, region)
    else:
        # Fallback to PythonOperator
        return _generate_python_task(task, account_id, region)


def _generate_s3_task(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate S3 task code."""
    task_id = task.get("taskId")
    
    if operation == "ensure_bucket":
        bucket_name = params.get("bucket")
        return f'''{_sanitize_task_id(task_id)} = S3CreateBucketOperator(
    task_id='{_sanitize_task_id(task_id)}',
    bucket_name='{bucket_name}',
    region_name='{params.get("region", region)}',
    aws_conn_id='aws_default',
    dag=dag,
)'''
    else:
        # Generic S3 operation via Python
        return _generate_python_task(task, account_id, region)


def _generate_glue_task(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate Glue task code."""
    task_id = task.get("taskId")
    
    if operation == "ensure_database":
        database = params.get("database")
        return f'''{_sanitize_task_id(task_id)} = PythonOperator(
    task_id='{_sanitize_task_id(task_id)}',
    python_callable=lambda: _ensure_glue_database(
        database='{database}',
        region='{region}'
    ),
    dag=dag,
)'''
    
    elif operation == "ensure_table":
        database = params.get("database")
        table = params.get("table")
        return f'''{_sanitize_task_id(task_id)} = PythonOperator(
    task_id='{_sanitize_task_id(task_id)}',
    python_callable=lambda: _ensure_glue_table(
        database='{database}',
        table='{table}',
        params={json.dumps(params)},
        region='{region}'
    ),
    dag=dag,
)'''
    
    else:
        return _generate_python_task(task, account_id, region)


def _generate_athena_task(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate Athena task code."""
    task_id = task.get("taskId")
    
    if operation == "execute_query":
        query = params.get("query", "")
        database = params.get("database", "default")
        output_location = params.get("outputLocation", f"s3://aws-athena-query-results-{account_id}-{region}/")
        
        return f'''{_sanitize_task_id(task_id)} = AthenaOperator(
    task_id='{_sanitize_task_id(task_id)}',
    query='{query}',
    database='{database}',
    output_location='{output_location}',
    aws_conn_id='aws_default',
    dag=dag,
)'''
    
    else:
        return _generate_python_task(task, account_id, region)


def _generate_redshift_task(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate Redshift task code."""
    task_id = task.get("taskId")
    
    if operation == "execute_sql":
        sql = params.get("sql", "")
        cluster_id = params.get("cluster", "")
        database = params.get("database", "dev")
        
        return f'''{_sanitize_task_id(task_id)} = RedshiftDataOperator(
    task_id='{_sanitize_task_id(task_id)}',
    sql='{sql}',
    cluster_identifier='{cluster_id}',
    database='{database}',
    aws_conn_id='aws_default',
    dag=dag,
)'''
    
    else:
        return _generate_python_task(task, account_id, region)


def _generate_lambda_task(
    task: Dict[str, Any],
    operation: str,
    params: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate Lambda task code."""
    task_id = task.get("taskId")
    
    if operation == "invoke":
        function_name = params.get("function")
        payload = params.get("payload", {})
        
        return f'''{_sanitize_task_id(task_id)} = LambdaInvokeFunctionOperator(
    task_id='{_sanitize_task_id(task_id)}',
    function_name='{function_name}',
    payload=json.dumps({json.dumps(payload)}),
    aws_conn_id='aws_default',
    dag=dag,
)'''
    
    else:
        return _generate_python_task(task, account_id, region)


def _generate_python_task(
    task: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate generic Python task (fallback)."""
    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})
    
    return f'''{_sanitize_task_id(task_id)} = PythonOperator(
    task_id='{_sanitize_task_id(task_id)}',
    python_callable=lambda: _execute_provider_action(
        action='{action}',
        params={json.dumps(params)},
        account_id='{account_id}',
        region='{region}'
    ),
    dag=dag,
)'''


def _generate_task_dependencies(tasks: List[Dict[str, Any]]) -> str:
    """Generate task dependency declarations."""
    dep_code = "# Task dependencies\n"
    
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        
        if depends_on:
            sanitized_id = _sanitize_task_id(task_id)
            for dep in depends_on:
                sanitized_dep = _sanitize_task_id(dep)
                dep_code += f"{sanitized_dep} >> {sanitized_id}\n"
    
    if dep_code == "# Task dependencies\n":
        dep_code += "# No dependencies defined\n"
    
    return dep_code


def _generate_helper_functions() -> str:
    """Generate helper functions for tasks."""
    return '''
# Helper functions

def _ensure_glue_database(database: str, region: str):
    """Ensure Glue database exists."""
    import boto3
    client = boto3.client('glue', region_name=region)
    
    try:
        client.create_database(DatabaseInput={'Name': database})
        logger.info(f"Created Glue database: {database}")
    except client.exceptions.AlreadyExistsException:
        logger.info(f"Glue database already exists: {database}")


def _ensure_glue_table(database: str, table: str, params: dict, region: str):
    """Ensure Glue table exists."""
    import boto3
    client = boto3.client('glue', region_name=region)

    columns = params.get('columns', [])
    location = params.get('location', '')
    input_format = params.get('input_format', 'parquet')

    FORMAT_MAP = {
        'parquet': {
            'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
            'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
            'SerDe': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
        },
        'orc': {
            'InputFormat': 'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat',
            'OutputFormat': 'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat',
            'SerDe': 'org.apache.hadoop.hive.ql.io.orc.OrcSerde',
        },
        'json': {
            'InputFormat': 'org.apache.hadoop.mapred.TextInputFormat',
            'OutputFormat': 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat',
            'SerDe': 'org.openx.data.jsonserde.JsonSerDe',
        },
        'csv': {
            'InputFormat': 'org.apache.hadoop.mapred.TextInputFormat',
            'OutputFormat': 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat',
            'SerDe': 'org.apache.hadoop.hive.serde2.OpenCSVSerde',
        },
    }
    fmt = FORMAT_MAP.get(input_format, FORMAT_MAP['parquet'])

    table_input = {
        'Name': table,
        'StorageDescriptor': {
            'Columns': columns,
            'Location': location,
            'InputFormat': fmt['InputFormat'],
            'OutputFormat': fmt['OutputFormat'],
            'SerdeInfo': {'SerializationLibrary': fmt['SerDe']},
        },
        'TableType': 'EXTERNAL_TABLE',
    }
    description = params.get('description')
    if description:
        table_input['Description'] = description

    try:
        client.get_table(DatabaseName=database, Name=table)
        client.update_table(DatabaseName=database, TableInput=table_input)
        logger.info(f"Updated Glue table: {database}.{table}")
    except client.exceptions.EntityNotFoundException:
        client.create_table(DatabaseName=database, TableInput=table_input)
        logger.info(f"Created Glue table: {database}.{table}")


def _execute_provider_action(action: str, params: dict, account_id: str, region: str):
    """Execute generic provider action by dispatching to the appropriate actions module."""
    logger.info(f"Executing action: {action}")

    parts = action.split('.')
    if len(parts) < 3:
        logger.warning(f"Unrecognised action format: {action}")
        return

    service, operation = parts[1], parts[2]

    # Dispatch to the concrete AWS action implementations
    if service == 'glue':
        from fluid_build.providers.aws.actions import glue as glue_actions
        handler = getattr(glue_actions, operation, None)
        if handler:
            handler({**params, 'region': region, 'account_id': account_id})
            return
    elif service == 's3':
        from fluid_build.providers.aws.actions import s3 as s3_actions
        handler = getattr(s3_actions, operation, None)
        if handler:
            handler({**params, 'region': region, 'account_id': account_id})
            return

    logger.warning(f"No handler found for action: {action}")
'''


def _sanitize_dag_id(dag_id: str) -> str:
    """Sanitize DAG ID for Airflow."""
    # Airflow DAG IDs can contain letters, numbers, dashes, periods, underscores
    sanitized = ""
    for char in dag_id:
        if char.isalnum() or char in "-._":
            sanitized += char
        else:
            sanitized += "_"
    return sanitized


def _sanitize_task_id(task_id: str) -> str:
    """Sanitize task ID for Airflow."""
    # Same rules as DAG ID
    return _sanitize_dag_id(task_id)


def _convert_schedule(schedule: str) -> str:
    """Convert schedule to Airflow format."""
    # If already cron, return as-is
    if schedule.count(" ") >= 4:
        return schedule
    
    # Handle common presets
    presets = {
        "daily": "0 2 * * *",
        "hourly": "0 * * * *",
        "weekly": "0 2 * * 0",
        "monthly": "0 2 1 * *",
    }
    
    return presets.get(schedule.lower(), schedule)


# ── Airflow 2.x TaskFlow API Generation ──────────────────────────────

def generate_airflow_dag_taskflow(
    contract: Dict[str, Any],
    account_id: str,
    region: str,
) -> str:
    """
    Generate an Airflow 2.x TaskFlow-style DAG from a FLUID contract.

    Uses ``@dag`` / ``@task`` decorators instead of explicit operator
    instantiation.  Falls back to classic operators for AWS-specific
    operators (S3, Athena, Redshift, Lambda) that have no TaskFlow
    equivalent.

    Args:
        contract: FLUID contract with orchestration section
        account_id: AWS account ID
        region: AWS region

    Returns:
        Python source code for an Airflow 2.x TaskFlow DAG
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    code = _generate_dag_header(contract_id, contract_name, schedule, timezone, account_id, region)
    code += "\n\n"
    code += _generate_taskflow_imports()
    code += "\n\n"
    code += _generate_taskflow_dag(
        contract_id, contract_name, schedule, timezone,
        provider_tasks, account_id, region,
    )
    return code


def _generate_taskflow_imports() -> str:
    """Generate import statements for TaskFlow API."""
    return '''from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from airflow.decorators import dag, task
from airflow.providers.amazon.aws.operators.s3 import S3CreateBucketOperator
from airflow.providers.amazon.aws.operators.athena import AthenaOperator
from airflow.providers.amazon.aws.operators.redshift_data import RedshiftDataOperator
from airflow.providers.amazon.aws.operators.lambda_function import LambdaInvokeFunctionOperator
import json
import logging

logger = logging.getLogger(__name__)'''


def _generate_taskflow_dag(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str,
    tasks: List[Dict[str, Any]],
    account_id: str,
    region: str,
) -> str:
    """Generate the full @dag-decorated function body."""
    dag_id = _sanitize_dag_id(contract_id)
    airflow_schedule = _convert_schedule(schedule)

    lines: List[str] = []
    lines.append(f"@dag(")
    lines.append(f"    dag_id='{dag_id}',")
    lines.append(f"    description='{contract_name}',")
    lines.append(f"    schedule='{airflow_schedule}',")
    lines.append(f"    start_date=datetime(2026, 1, 1, tzinfo=ZoneInfo('{timezone}')),")
    lines.append(f"    catchup=False,")
    lines.append(f"    default_args={{")
    lines.append(f"        'owner': 'fluid-forge',")
    lines.append(f"        'retries': 3,")
    lines.append(f"        'retry_delay': timedelta(minutes=5),")
    lines.append(f"    }},")
    lines.append(f"    tags=['fluid', 'auto-generated', '{contract_id}'],")
    lines.append(f")")
    lines.append(f"def {dag_id.replace('-', '_').replace('.', '_')}():")

    # Build per-task variable names for dependency wiring
    task_vars: Dict[str, str] = {}
    for t in tasks:
        tid = t.get("taskId", "")
        task_vars[tid] = _sanitize_task_id(tid)

    for t in tasks:
        tid = t.get("taskId", "")
        var = task_vars[tid]
        action = t.get("action", "")
        params = t.get("params", {})
        parts = action.split(".")
        service = parts[1] if len(parts) >= 3 else ""
        operation = parts[2] if len(parts) >= 3 else ""

        if service == "s3" and operation == "ensure_bucket":
            bucket = params.get("bucket", "")
            lines.append(f"")
            lines.append(f"    {var} = S3CreateBucketOperator(")
            lines.append(f"        task_id='{var}',")
            lines.append(f"        bucket_name='{bucket}',")
            lines.append(f"        region_name='{params.get('region', region)}',")
            lines.append(f"        aws_conn_id='aws_default',")
            lines.append(f"    )")
        elif service == "athena" and operation == "execute_query":
            query = params.get("query", "")
            db = params.get("database", "default")
            out = params.get("outputLocation", f"s3://aws-athena-query-results-{account_id}-{region}/")
            lines.append(f"")
            lines.append(f"    {var} = AthenaOperator(")
            lines.append(f"        task_id='{var}',")
            lines.append(f"        query='{query}',")
            lines.append(f"        database='{db}',")
            lines.append(f"        output_location='{out}',")
            lines.append(f"        aws_conn_id='aws_default',")
            lines.append(f"    )")
        elif service == "glue":
            # Glue operations use @task decorators
            lines.append(f"")
            lines.append(f"    @task(task_id='{var}')")
            lines.append(f"    def {var}():")
            if operation == "ensure_database":
                db = params.get("database", "")
                lines.append(f"        _ensure_glue_database('{db}', '{region}')")
            elif operation == "ensure_table":
                db = params.get("database", "")
                tbl = params.get("table", "")
                lines.append(f"        _ensure_glue_table('{db}', '{tbl}', {json.dumps(params)}, '{region}')")
            else:
                lines.append(f"        _execute_provider_action('{action}', {json.dumps(params)}, '{account_id}', '{region}')")
            lines.append(f"    {var}_result = {var}()")
        else:
            # Generic @task fallback
            lines.append(f"")
            lines.append(f"    @task(task_id='{var}')")
            lines.append(f"    def {var}():")
            lines.append(f"        _execute_provider_action('{action}', {json.dumps(params)}, '{account_id}', '{region}')")
            lines.append(f"    {var}_result = {var}()")

    # Dependencies
    for t in tasks:
        tid = t.get("taskId", "")
        depends_on = t.get("dependsOn", [])
        if depends_on:
            var = task_vars[tid]
            for dep in depends_on:
                dep_var = task_vars.get(dep, _sanitize_task_id(dep))
                lines.append(f"    {dep_var} >> {var}")

    lines.append(f"")
    lines.append(f"")
    lines.append(f"{dag_id.replace('-', '_').replace('.', '_')}()")

    return "\n".join(lines)
