# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Dagster Pipeline Generation for AWS Provider.

Generates Dagster pipeline Python code from FLUID contracts.

Supports:
- Software-defined assets
- Task dependencies
- AWS resource integration
- Type-safe ops
"""

from typing import Dict, Any, List
from datetime import datetime
import json


def generate_dagster_pipeline(
    contract: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """
    Generate Dagster pipeline Python code from FLUID contract.
    
    Args:
        contract: FLUID contract with orchestration section
        account_id: AWS account ID
        region: AWS region
        
    Returns:
        Python code for Dagster pipeline
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")
    
    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")
    
    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    
    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]
    
    # Generate pipeline code
    code = _generate_header(contract_id, contract_name, account_id, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_resources(account_id, region)
    code += "\n\n"
    code += _generate_ops(provider_tasks, account_id, region)
    code += "\n\n"
    code += _generate_job(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_schedule(contract_id, schedule)
    code += "\n\n"
    code += _generate_repository(contract_id)
    
    return code


def _generate_header(
    contract_id: str,
    contract_name: str,
    account_id: str,
    region: str
) -> str:
    """Generate file header."""
    return f'''"""
FLUID Generated Dagster Pipeline: {contract_name}

Contract ID: {contract_id}
AWS Account: {account_id}
AWS Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return '''from dagster import (
    op,
    job,
    In,
    Out,
    resource,
    ResourceDefinition,
    ScheduleDefinition,
    repository,
    DagsterType,
    Field,
    String,
)
import boto3
import json
import logging

logger = logging.getLogger(__name__)'''


def _generate_resources(account_id: str, region: str) -> str:
    """Generate Dagster resources for AWS clients."""
    return f'''# AWS Resources

@resource(
    config_schema={{
        "account_id": Field(String, default_value="{account_id}"),
        "region": Field(String, default_value="{region}"),
    }}
)
def aws_s3_resource(context):
    """S3 client resource."""
    return boto3.client(
        's3',
        region_name=context.resource_config["region"]
    )


@resource(
    config_schema={{
        "account_id": Field(String, default_value="{account_id}"),
        "region": Field(String, default_value="{region}"),
    }}
)
def aws_glue_resource(context):
    """Glue client resource."""
    return boto3.client(
        'glue',
        region_name=context.resource_config["region"]
    )


@resource(
    config_schema={{
        "account_id": Field(String, default_value="{account_id}"),
        "region": Field(String, default_value="{region}"),
    }}
)
def aws_athena_resource(context):
    """Athena client resource."""
    return boto3.client(
        'athena',
        region_name=context.resource_config["region"]
    )


@resource(
    config_schema={{
        "account_id": Field(String, default_value="{account_id}"),
        "region": Field(String, default_value="{region}"),
    }}
)
def aws_lambda_resource(context):
    """Lambda client resource."""
    return boto3.client(
        'lambda',
        region_name=context.resource_config["region"]
    )'''


def _generate_ops(
    tasks: List[Dict[str, Any]],
    account_id: str,
    region: str
) -> str:
    """Generate Dagster ops for tasks."""
    ops_code = "# Task Ops\n\n"
    
    for task in tasks:
        ops_code += _generate_single_op(task, account_id, region)
        ops_code += "\n\n"
    
    return ops_code.rstrip()


def _generate_single_op(
    task: Dict[str, Any],
    account_id: str,
    region: str
) -> str:
    """Generate code for a single op."""
    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])
    
    # Determine required resources based on action
    action_parts = action.split(".")
    service = action_parts[1] if len(action_parts) > 1 else "unknown"
    
    # Build ins from dependencies
    ins_str = ""
    if depends_on:
        # Generate ins parameter as dictionary of In() objects
        ins_entries = [f'"{dep}": In()' for dep in depends_on]
        ins_str = f"    ins={{{', '.join(ins_entries)}}},"
    
    # Generate op decorator and function
    resource_name = f"aws_{service}_resource" if service in ["s3", "glue", "athena", "lambda"] else None
    required_resources = f'"{resource_name}"' if resource_name else ""
    
    return f'''@op(
{ins_str}
    required_resource_keys={{{required_resources}}},
)
def {_sanitize_op_name(task_id)}(context):
    """Execute {action}."""
    logger.info(f"Executing: {action}")
    params = {json.dumps(params, indent=4)}
    
    # Execute provider action
    {_generate_op_implementation(action, params, service)}
    
    return {{"status": "success", "task_id": "{task_id}"}}'''


def _generate_op_implementation(
    action: str,
    params: Dict[str, Any],
    service: str
) -> str:
    """Generate op implementation code."""
    if service == "s3":
        return '''s3_client = context.resources.aws_s3_resource
    bucket = params.get("bucket")
    if bucket:
        s3_client.create_bucket(Bucket=bucket)
        logger.info(f"Created S3 bucket: {bucket}")'''
    
    elif service == "glue":
        return '''glue_client = context.resources.aws_glue_resource
    database = params.get("database")
    if database:
        try:
            glue_client.create_database(DatabaseInput={'Name': database})
            logger.info(f"Created Glue database: {database}")
        except glue_client.exceptions.AlreadyExistsException:
            logger.info(f"Database already exists: {database}")'''
    
    elif service == "athena":
        return '''athena_client = context.resources.aws_athena_resource
    query = params.get("query")
    database = params.get("database", "default")
    if query:
        response = athena_client.start_query_execution(
            QueryString=query,
            QueryExecutionContext={'Database': database},
            ResultConfiguration={'OutputLocation': params.get("outputLocation", "s3://athena-results/")}
        )
        logger.info(f"Started Athena query: {response['QueryExecutionId']}")'''
    
    elif service == "lambda":
        return '''lambda_client = context.resources.aws_lambda_resource
    function_name = params.get("function")
    payload = params.get("payload", {})
    if function_name:
        response = lambda_client.invoke(
            FunctionName=function_name,
            Payload=json.dumps(payload)
        )
        logger.info(f"Invoked Lambda: {function_name}")'''
    
    else:
        return f'''# Generic provider action execution
    logger.info(f"Action: {action}")
    logger.info(f"Params: {{params}}")'''


def _generate_job(
    contract_id: str,
    contract_name: str,
    tasks: List[Dict[str, Any]]
) -> str:
    """Generate Dagster job definition."""
    # Build dependency graph
    graph_calls = []
    
    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        op_name = _sanitize_op_name(task_id)
        
        if depends_on:
            # Op with dependencies
            args = ", ".join([_sanitize_op_name(dep) for dep in depends_on])
            graph_calls.append(f"    {op_name}({args})")
        else:
            # Independent op
            graph_calls.append(f"    {op_name}()")
    
    graph_body = "\n".join(graph_calls)
    
    return f'''@job(
    resource_defs={{
        "aws_s3_resource": aws_s3_resource,
        "aws_glue_resource": aws_glue_resource,
        "aws_athena_resource": aws_athena_resource,
        "aws_lambda_resource": aws_lambda_resource,
    }},
    description="{contract_name}",
)
def {_sanitize_job_name(contract_id)}_job():
    """{contract_name} workflow."""
{graph_body}'''


def _generate_schedule(contract_id: str, schedule: str) -> str:
    """Generate schedule definition."""
    # Convert cron to Dagster schedule
    cron_schedule = _convert_to_cron(schedule)
    
    return f'''# Schedule
{_sanitize_job_name(contract_id)}_schedule = ScheduleDefinition(
    job={_sanitize_job_name(contract_id)}_job,
    cron_schedule="{cron_schedule}",
)'''


def _generate_repository(contract_id: str) -> str:
    """Generate Dagster repository."""
    job_name = _sanitize_job_name(contract_id)
    
    return f'''# Repository
@repository
def {job_name}_repository():
    """Dagster repository for {contract_id}."""
    return [
        {job_name}_job,
        {job_name}_schedule,
    ]'''


def _sanitize_op_name(name: str) -> str:
    """Sanitize op name for Dagster."""
    # Dagster op names must be valid Python identifiers
    sanitized = ""
    for i, char in enumerate(name):
        if char.isalnum() or char == "_":
            sanitized += char
        else:
            sanitized += "_"
    
    # Ensure doesn't start with number
    if sanitized and sanitized[0].isdigit():
        sanitized = "op_" + sanitized
    
    return sanitized or "unnamed_op"


def _sanitize_job_name(name: str) -> str:
    """Sanitize job name for Dagster."""
    return _sanitize_op_name(name)


def _convert_to_cron(schedule: str) -> str:
    """Convert schedule to cron format."""
    # If already cron, return as-is
    if schedule.count(" ") >= 4:
        return schedule
    
    # Handle common presets
    presets = {
        "daily": "0 2 * * *",
        "hourly": "0 * * * *",
        "weekly": "0 2 * * 0",
        "monthly": "0 2 1 * *",
    }
    
    return presets.get(schedule.lower(), "0 2 * * *")
