# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for AWS Provider.

Generates Prefect 2.x flow Python code from FLUID contracts.

Supports:
- Tasks and flows
- Task dependencies
- AWS integrations
- Deployment configurations
"""

import json
from datetime import datetime
from typing import Any, Dict, List


def generate_prefect_flow(contract: Dict[str, Any], account_id: str, region: str) -> str:
    """
    Generate Prefect 2.x flow Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        account_id: AWS account ID
        region: AWS region

    Returns:
        Python code for Prefect flow
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate flow code
    code = _generate_header(contract_id, contract_name, account_id, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_tasks(provider_tasks, account_id, region)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)

    return code


def _generate_header(contract_id: str, contract_name: str, account_id: str, region: str) -> str:
    """Generate file header."""
    return f'''"""
FLUID Generated Prefect Flow: {contract_name}

Contract ID: {contract_id}
AWS Account: {account_id}
AWS Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return """from prefect import flow, task
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
import boto3
import json
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)"""


def _generate_tasks(tasks: List[Dict[str, Any]], account_id: str, region: str) -> str:
    """Generate Prefect tasks."""
    tasks_code = "# Prefect Tasks\n\n"

    for task in tasks:
        tasks_code += _generate_single_task(task, account_id, region)
        tasks_code += "\n\n"

    return tasks_code.rstrip()


def _generate_single_task(task: Dict[str, Any], account_id: str, region: str) -> str:
    """Generate code for a single Prefect task."""
    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})

    # Parse action to determine service
    action_parts = action.split(".")
    service = action_parts[1] if len(action_parts) > 1 else "unknown"

    return f'''@task(
    name="{task_id}",
    description="Execute {action}",
    retries=3,
    retry_delay_seconds=300,
)
def {_sanitize_task_name(task_id)}() -> Dict[str, Any]:
    """Execute {action}."""
    logger.info(f"Executing: {action}")
    params = {json.dumps(params, indent=4)}
    
    {_generate_task_implementation(action, service, region)}
    
    return {{"status": "success", "task_id": "{task_id}"}}'''


def _generate_task_implementation(action: str, service: str, region: str) -> str:
    """Generate task implementation code."""
    if service == "s3":
        return f"""# S3 operation
    s3_client = boto3.client('s3', region_name='{region}')
    bucket = params.get("bucket")
    if bucket:
        try:
            s3_client.create_bucket(
                Bucket=bucket,
                CreateBucketConfiguration={{'LocationConstraint': '{region}'}}
            )
            logger.info(f"Created S3 bucket: {{bucket}}")
        except s3_client.exceptions.BucketAlreadyOwnedByYou:
            logger.info(f"Bucket already exists: {{bucket}}")"""

    elif service == "glue":
        return f"""# Glue operation
    glue_client = boto3.client('glue', region_name='{region}')
    
    if params.get("database"):
        database = params["database"]
        try:
            glue_client.create_database(
                DatabaseInput={{'Name': database}}
            )
            logger.info(f"Created Glue database: {{database}}")
        except glue_client.exceptions.AlreadyExistsException:
            logger.info(f"Database already exists: {{database}}")
    
    if params.get("table"):
        table = params["table"]
        database = params.get("database", "default")
        # TODO: Create table from params
        logger.info(f"Ensuring Glue table: {{database}}.{{table}}")"""

    elif service == "athena":
        return f"""# Athena operation
    athena_client = boto3.client('athena', region_name='{region}')
    query = params.get("query")
    database = params.get("database", "default")
    
    if query:
        response = athena_client.start_query_execution(
            QueryString=query,
            QueryExecutionContext={{'Database': database}},
            ResultConfiguration={{
                'OutputLocation': params.get("outputLocation", "s3://athena-results/")
            }}
        )
        query_id = response['QueryExecutionId']
        logger.info(f"Started Athena query: {{query_id}}")
        
        # Wait for completion
        import time
        while True:
            result = athena_client.get_query_execution(QueryExecutionId=query_id)
            status = result['QueryExecution']['Status']['State']
            if status in ['SUCCEEDED', 'FAILED', 'CANCELLED']:
                logger.info(f"Query {{query_id}} status: {{status}}")
                break
            time.sleep(2)"""

    elif service == "redshift":
        return f"""# Redshift operation
    redshift_data = boto3.client('redshift-data', region_name='{region}')
    sql = params.get("sql")
    cluster_id = params.get("cluster")
    database = params.get("database", "dev")
    
    if sql and cluster_id:
        response = redshift_data.execute_statement(
            ClusterIdentifier=cluster_id,
            Database=database,
            Sql=sql
        )
        logger.info(f"Executed Redshift SQL: {{response['Id']}}")"""

    elif service == "lambda":
        return f"""# Lambda operation
    lambda_client = boto3.client('lambda', region_name='{region}')
    function_name = params.get("function")
    payload = params.get("payload", {{}})
    
    if function_name:
        response = lambda_client.invoke(
            FunctionName=function_name,
            InvocationType='RequestResponse',
            Payload=json.dumps(payload)
        )
        logger.info(f"Invoked Lambda: {{function_name}}")
        result = json.loads(response['Payload'].read())
        logger.info(f"Lambda result: {{result}}")"""

    else:
        return f"""# Generic provider action
    logger.info(f"Action: {action}")
    logger.info(f"Params: {{params}}")
    # TODO: Implement provider action execution"""


def _generate_flow(contract_id: str, contract_name: str, tasks: List[Dict[str, Any]]) -> str:
    """Generate Prefect flow definition."""
    # Build task execution with dependencies
    flow_body_lines = []
    task_vars = {}  # Map task_id to variable name

    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        task_func = _sanitize_task_name(task_id)

        # Create task call
        if depends_on:
            # Task with dependencies - use wait_for
            wait_for_tasks = [task_vars[dep] for dep in depends_on if dep in task_vars]
            if wait_for_tasks:
                wait_for_str = ", ".join(wait_for_tasks)
                flow_body_lines.append(
                    f"    {task_func}_result = {task_func}(wait_for=[{wait_for_str}])"
                )
            else:
                flow_body_lines.append(f"    {task_func}_result = {task_func}()")
        else:
            # Independent task
            flow_body_lines.append(f"    {task_func}_result = {task_func}()")

        task_vars[task_id] = f"{task_func}_result"

    # Collect all results
    all_results = list(task_vars.values())
    flow_body_lines.append(f"\n    return [{', '.join(all_results)}]")

    flow_body = "\n".join(flow_body_lines)

    return f'''@flow(
    name="{contract_name}",
    description="FLUID workflow for {contract_id}",
    retries=2,
    retry_delay_seconds=600,
)
def {_sanitize_flow_name(contract_id)}_flow():
    """{contract_name} workflow."""
    logger.info("Starting FLUID workflow: {contract_name}")
{flow_body}'''


def _generate_deployment(contract_id: str, contract_name: str, schedule: str, timezone: str) -> str:
    """Generate Prefect deployment configuration."""
    cron_schedule = _convert_to_cron(schedule)
    flow_name = _sanitize_flow_name(contract_id)

    return f"""# Deployment Configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name="{contract_id}-deployment",
        schedule=CronSchedule(
            cron="{cron_schedule}",
            timezone="{timezone}"
        ),
        tags=["fluid", "auto-generated", "{contract_id}"],
        parameters={{}},
        work_queue_name="default",
    )
    
    deployment.apply()
    cprint(f"Deployed: {contract_name}")
    cprint(f"Schedule: {cron_schedule} ({timezone})")"""


def _sanitize_task_name(name: str) -> str:
    """Sanitize task name for Prefect."""
    # Must be valid Python identifier
    sanitized = ""
    for i, char in enumerate(name):
        if char.isalnum() or char == "_":
            sanitized += char
        else:
            sanitized += "_"

    # Ensure doesn't start with number
    if sanitized and sanitized[0].isdigit():
        sanitized = "task_" + sanitized

    return sanitized or "unnamed_task"


def _sanitize_flow_name(name: str) -> str:
    """Sanitize flow name for Prefect."""
    return _sanitize_task_name(name)


def _convert_to_cron(schedule: str) -> str:
    """Convert schedule to cron format."""
    # If already cron, return as-is
    if schedule.count(" ") >= 4:
        return schedule

    # Handle common presets
    presets = {
        "daily": "0 2 * * *",
        "hourly": "0 * * * *",
        "weekly": "0 2 * * 0",
        "monthly": "0 2 1 * *",
    }

    return presets.get(schedule.lower(), "0 2 * * *")
