# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
CLI command for generating dynamic DataOps pipeline templates

This command allows teams to generate CI/CD pipeline configurations
tailored to their preferred provider and requirements.
"""

import argparse
import hashlib
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from fluid_build.cli.artifact_paths import CI_HEADER_SCHEMA
from fluid_build.cli.artifact_envelope import utc_now_iso
from fluid_build.cli.console import cprint, success, warning
from fluid_build.cli.console import error as console_error

from ..forge.core.pipeline_templates import (
    PipelineComplexity,
    PipelineConfig,
    PipelineProvider,
    PipelineTemplateGenerator,
)

COMMAND = "generate-pipeline"


# ---------------------------------------------------------------------------
# Shared helpers — used by this CLI wrapper and by the forge auto-CI hook
# ---------------------------------------------------------------------------


def build_pipeline_config(
    provider: str,
    complexity: str = "standard",
    environments: Optional[List[str]] = None,
    *,
    enable_approvals: bool = False,
    enable_security_scan: bool = True,
    enable_marketplace_publishing: bool = False,
) -> PipelineConfig:
    """Coerce string inputs into a :class:`PipelineConfig`.

    Passing ``environments=None`` lets :meth:`PipelineConfig.__post_init__`
    pick complexity-appropriate defaults. Raises ``ValueError`` with a helpful
    message on unknown provider or complexity.
    """
    provider_aliases = {
        "circleci": "circle_ci",
    }
    provider = provider_aliases.get(provider, provider)
    try:
        provider_enum = PipelineProvider(provider)
    except ValueError as exc:
        raise ValueError(
            f"Unknown CI provider: {provider!r}. "
            f"Valid: {', '.join(p.value for p in PipelineProvider)}"
        ) from exc
    try:
        complexity_enum = PipelineComplexity(complexity)
    except ValueError as exc:
        raise ValueError(
            f"Unknown pipeline complexity: {complexity!r}. "
            f"Valid: {', '.join(c.value for c in PipelineComplexity)}"
        ) from exc
    return PipelineConfig(
        provider=provider_enum,
        complexity=complexity_enum,
        environments=environments,
        enable_approvals=enable_approvals,
        enable_security_scan=enable_security_scan,
        enable_marketplace_publishing=enable_marketplace_publishing,
    )


# ---------------------------------------------------------------------------
# Provenance header injection
# ---------------------------------------------------------------------------

#: Filenames that use Groovy-style `//` comments instead of `#` YAML comments.
#: Everything else defaults to `#`.  Adding a new provider that emits a
#: non-YAML file means adding a pattern here.
_GROOVY_COMMENT_PATTERNS = {"Jenkinsfile"}


def _comment_prefix_for(filename: str) -> str:
    """Return the provider-native comment prefix for a CI file.

    Rules:

    * Filenames ending in ``.yml`` / ``.yaml`` use ``#`` (all 6 YAML providers).
    * ``Jenkinsfile`` (Groovy) uses ``//``.
    * Anything else defaults to ``#`` — the safest choice for shell /
      config file formats we may add later.
    """
    name = Path(filename).name
    if name in _GROOVY_COMMENT_PATTERNS:
        return "//"
    return "#"


def _render_header(
    *,
    filename: str,
    command: str,
    tool_version: str,
    generated_at: Optional[str] = None,
    sha256_prefix: Optional[str] = None,
) -> str:
    """Return the multi-line DO-NOT-EDIT header for a CI file.

    The header matches the CI_HEADER_SCHEMA identifier exported by
    :mod:`fluid_build.cli.artifact_paths` so future ``fluid doctor``
    checks can identify our files without reading ``ci-state.json``.
    """
    prefix = _comment_prefix_for(filename)
    timestamp = generated_at or utc_now_iso()
    lines = [
        f"{prefix} Generated by fluid-cli v{tool_version} on {timestamp}",
        f"{prefix} Command: {command}",
    ]
    if sha256_prefix:
        lines.append(f"{prefix} Provenance: {sha256_prefix}  (do not edit — regenerate with `fluid forge --ci <provider>`)")
    else:
        lines.append(f"{prefix} Do not edit — regenerate with `fluid forge --ci <provider>`")
    lines.append(f"{prefix} Schema: {CI_HEADER_SCHEMA}")
    return "\n".join(lines) + "\n"


def _prepend_header(content: str, header: str) -> str:
    """Prepend *header* to *content* as the first lines of the file.

    Preserves a trailing newline on the original content if present.
    """
    if not header.endswith("\n"):
        header += "\n"
    return header + content


def write_pipeline_files(
    files: Dict[str, str],
    output_dir: Path,
    *,
    dry_run: bool = False,
    console: Any = None,
    command: Optional[str] = None,
    tool_version: Optional[str] = None,
    inject_header: bool = True,
) -> List[Path]:
    """Write generated pipeline files under *output_dir*.

    In ``dry_run`` mode, reports planned writes without touching disk.
    Returns the list of written (or planned) paths in insertion order.

    When ``inject_header`` is true (default), each file is prefixed with
    a provenance header in the provider's native comment syntax — YAML
    providers get ``#`` lines, Jenkinsfile gets ``//`` lines.  The header
    names the generator, timestamp, command, and sha256 prefix so PR
    reviewers can tell generated CI from hand-edited CI at a glance.

    ``command`` and ``tool_version`` populate the header.  They default
    to ``"fluid generate-pipeline"`` and ``fluid_build.__version__`` so
    existing callers that don't know about the header get a sensible
    default.
    """
    if command is None:
        command = "fluid generate-pipeline"
    if tool_version is None:
        try:
            from fluid_build import __version__ as _tv
        except Exception:  # pragma: no cover — defensive
            _tv = ""
        tool_version = str(_tv)

    written: List[Path] = []
    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in files.items():
        file_path = output_dir / filename

        # Inject header before dry-run reporting so the planned output
        # in preview mode matches the real output byte-for-byte.
        if inject_header:
            body_sha = hashlib.sha256(content.encode("utf-8")).hexdigest()[:12]
            header = _render_header(
                filename=filename,
                command=command,
                tool_version=tool_version,
                sha256_prefix=body_sha,
            )
            content = _prepend_header(content, header)

        if dry_run:
            message = f"would write: {file_path}"
            if console is not None:
                try:
                    console.print(f"[dim]{message}[/dim]")
                except Exception:  # noqa: BLE001
                    cprint(message)
            else:
                cprint(message)
            written.append(file_path)
            continue
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with file_path.open("w") as f:
            f.write(content)
        success(f"Created: {file_path}")
        written.append(file_path)
    return written


def register(subparsers: argparse._SubParsersAction) -> None:
    """Register pipeline generator command"""
    parser = subparsers.add_parser(
        COMMAND,
        help="🚀 Generate CI/CD pipeline templates for FLUID projects",
        description="Create dynamic DataOps pipeline configurations for your preferred CI/CD provider",
    )

    parser.add_argument(
        "--provider",
        choices=[
            "github_actions",
            "gitlab_ci",
            "azure_devops",
            "jenkins",
            "bitbucket",
            "circleci",
            "tekton",
        ],
        help="CI/CD provider to generate pipeline for",
    )
    parser.add_argument(
        "--complexity",
        choices=["basic", "standard", "advanced", "enterprise"],
        default="standard",
        help="Pipeline complexity level",
    )
    parser.add_argument(
        "--environments",
        nargs="*",
        default=["dev", "staging", "prod"],
        help="Deployment environments",
    )
    parser.add_argument(
        "--enable-approvals", action="store_true", help="Enable manual approval gates"
    )
    parser.add_argument(
        "--enable-security-scan",
        action="store_true",
        default=True,
        help="Enable security scanning in pipeline",
    )
    parser.add_argument(
        "--enable-marketplace", action="store_true", help="Enable marketplace publishing"
    )
    parser.add_argument("--output-dir", default=".", help="Directory to output pipeline files")
    parser.add_argument(
        "--preview", action="store_true", help="Preview pipeline content without writing files"
    )
    parser.add_argument(
        "--interactive", action="store_true", help="Interactive mode for configuration"
    )


def run(args: argparse.Namespace, logger: logging.Logger) -> int:
    """
    Generate dynamic DataOps pipeline templates for FLUID projects.

    This command creates comprehensive CI/CD pipeline configurations that include
    all FLUID workflow steps: validate, plan, apply, test, visualize, and marketplace publishing.
    """
    try:
        cprint("🚀 FLUID Dynamic DataOps Pipeline Generator")
        cprint("=" * 50)

        # Use interactive mode if provider not specified
        if args.interactive or not args.provider:
            (
                provider,
                complexity,
                environments,
                enable_approvals,
                enable_security_scan,
                enable_marketplace,
            ) = _interactive_config()
        else:
            provider = args.provider
            complexity = args.complexity
            environments = args.environments
            enable_approvals = args.enable_approvals
            enable_security_scan = args.enable_security_scan
            enable_marketplace = args.enable_marketplace

        # Create configuration
        config = build_pipeline_config(
            provider=provider,
            complexity=complexity,
            environments=environments,
            enable_approvals=enable_approvals,
            enable_security_scan=enable_security_scan,
            enable_marketplace_publishing=enable_marketplace,
        )

        # Generate pipeline
        generator = PipelineTemplateGenerator()
        files = generator.generate_pipeline(config)

        # Handle preview mode
        if args.preview:
            cprint(f"\n🔍 Preview mode - would generate {len(files)} files:")
            for filename, content in files.items():
                cprint(f"\n📄 {filename}")
                cprint("-" * 40)
                cprint(content[:500] + "..." if len(content) > 500 else content)
            return 0

        # Write files to output directory — header injection is on by default.
        output_dir = Path(args.output_dir)
        command_str = f"fluid generate-pipeline --provider {provider} --complexity {complexity}"
        try:
            from fluid_build import __version__ as _tv
        except Exception:  # pragma: no cover — defensive
            _tv = ""
        written_paths = write_pipeline_files(
            files,
            output_dir,
            command=command_str,
            tool_version=str(_tv),
        )

        # Emit ci-state.json alongside the generated files so forge runs
        # on other machines can detect drift against the provider choice
        # this command just made.
        try:
            from fluid_build.cli.artifact_ci_state import (
                build_ci_state_payload,
                write_ci_state,
            )

            doc = build_ci_state_payload(
                provider=provider,
                complexity=complexity,
                environments=list(config.environments or []),
                options={
                    "enable_approvals": bool(config.enable_approvals),
                    "enable_security_scan": bool(config.enable_security_scan),
                    "enable_marketplace_publishing": bool(config.enable_marketplace_publishing),
                },
                written_files=written_paths,
                product_root=output_dir,
                body_contents=files,
            )
            write_ci_state(
                doc,
                output_dir,
                command=command_str,
                tool_version=str(_tv),
            )
        except Exception as exc:  # noqa: BLE001 — best-effort
            logger.debug("ci_state_write_failed_standalone: %s", exc)

        cprint(f"\n🎉 Successfully generated {len(files)} pipeline files!")
        _show_next_steps(provider, output_dir)

        return 0

    except Exception as e:
        logger.error(f"Pipeline generation failed: {e}")
        console_error(f"Error: {e}")
        return 1


def _interactive_config():
    """Interactive configuration mode"""
    cprint("\n🎯 Interactive Pipeline Configuration")

    # Provider selection
    providers = [p.value for p in PipelineProvider]
    cprint("\nAvailable CI/CD providers:")
    for i, provider in enumerate(providers, 1):
        cprint(f"  {i}. {provider.replace('_', ' ').title()}")

    while True:
        try:
            choice = int(input("\nSelect provider (1-7): "))
            if 1 <= choice <= len(providers):
                provider = providers[choice - 1]
                break
            else:
                console_error("Invalid choice. Please select 1-7.")
        except ValueError:
            console_error("Please enter a valid number.")

    # Complexity selection
    complexities = [c.value for c in PipelineComplexity]
    cprint("\nPipeline complexity levels:")
    cprint("  1. Basic - Simple validate -> apply workflow")
    cprint("  2. Standard - Full workflow with testing and multi-environment")
    cprint("  3. Advanced - Multi-environment with approvals and security")
    cprint("  4. Enterprise - Full governance and compliance")

    while True:
        try:
            choice = int(input("\nSelect complexity (1-4, default=2): ") or "2")
            if 1 <= choice <= len(complexities):
                complexity = complexities[choice - 1]
                break
            else:
                console_error("Invalid choice. Please select 1-4.")
        except ValueError:
            console_error("Please enter a valid number.")

    # Environment configuration
    environments = ["dev", "staging", "prod"]
    if complexity in ["standard", "advanced", "enterprise"]:
        env_input = input(
            f"\nUse default environments ({', '.join(environments)})? [Y/n]: "
        ).lower()
        if env_input in ["n", "no"]:
            environments = []
            cprint("\nEnter environments (press Enter when done):")
            while True:
                env = input("Environment name: ").strip()
                if not env:
                    break
                environments.append(env)

            if not environments:
                environments = ["dev"]
                warning("No environments specified, using 'dev' as default")
    else:
        environments = ["dev"]

    # Advanced options
    enable_approvals = False
    enable_security_scan = True
    enable_marketplace = False

    if complexity in ["advanced", "enterprise"]:
        enable_approvals = input(
            "\nEnable manual approval gates for production? [Y/n]: "
        ).lower() not in ["n", "no"]
        enable_security_scan = input("Enable security scanning? [Y/n]: ").lower() not in ["n", "no"]
        enable_marketplace = input("Enable marketplace publishing? [y/N]: ").lower() in ["y", "yes"]

    return (
        provider,
        complexity,
        environments,
        enable_approvals,
        enable_security_scan,
        enable_marketplace,
    )


def _show_next_steps(provider: str, output_dir: Path):
    """Show next steps for setup"""
    cprint(f"\n📋 Next Steps for {provider.replace('_', ' ').title()}:")

    if provider == "github_actions":
        cprint("1. Commit the .github/workflows/ files to your repository")
        cprint("2. Configure repository secrets for deployment credentials")
        cprint("3. Set up environment protection rules in repository settings")
        cprint("4. Configure any required GitHub Apps or integrations")
    elif provider == "gitlab_ci":
        cprint("1. Commit the .gitlab-ci.yml file to your repository")
        cprint("2. Configure CI/CD variables for deployment credentials")
        cprint("3. Set up environments and deployment rules in GitLab")
        cprint("4. Configure runners with appropriate tags if using self-hosted runners")
    elif provider == "azure_devops":
        cprint("1. Commit the azure-pipelines.yml file to your repository")
        cprint("2. Configure service connections for deployment targets")
        cprint("3. Set up environments with approval and check policies")
        cprint("4. Configure variable groups for environment-specific settings")
    elif provider == "jenkins":
        cprint("1. Create a new pipeline job in Jenkins")
        cprint("2. Configure the Jenkinsfile in your repository")
        cprint("3. Set up Jenkins credentials for deployment targets")
        cprint("4. Configure any required Jenkins plugins")
    else:
        cprint("1. Commit the pipeline configuration to your repository")
        cprint("2. Configure deployment credentials and secrets")
        cprint("3. Set up environment-specific configurations")
        cprint("4. Test the pipeline with a sample commit")

    cprint(f"\n📁 Pipeline files created in: {output_dir.absolute()}")
    cprint("\n🔧 FLUID Commands included in pipeline:")
    cprint("  • fluid validate --strict")
    cprint("  • fluid plan --output plan.json")
    cprint("  • fluid apply --plan plan.json")
    cprint("  • fluid test --coverage")
    cprint("  • fluid viz-plan --output pipeline-viz.html")
    cprint("  • fluid export-opds --output opds-catalog.json")
    cprint("  • fluid marketplace publish --catalog opds-catalog.json")
