"""
FLUID Generated Dagster Pipeline: Financial Analytics Pipeline

Contract ID: financial_analytics
AWS Account: YOUR_AWS_ACCOUNT_ID
AWS Region: us-east-1

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: 2026-01-30T14:02:10.321233
"""

import json
import logging

import boto3
from dagster import (
    DagsterType,
    Field,
    In,
    Out,
    ResourceDefinition,
    ScheduleDefinition,
    String,
    job,
    op,
    repository,
    resource,
)

logger = logging.getLogger(__name__)

# AWS Resources


@resource(
    config_schema={
        "account_id": Field(String, default_value="YOUR_AWS_ACCOUNT_ID"),
        "region": Field(String, default_value="us-east-1"),
    }
)
def aws_s3_resource(context):
    """S3 client resource."""
    return boto3.client("s3", region_name=context.resource_config["region"])


@resource(
    config_schema={
        "account_id": Field(String, default_value="YOUR_AWS_ACCOUNT_ID"),
        "region": Field(String, default_value="us-east-1"),
    }
)
def aws_glue_resource(context):
    """Glue client resource."""
    return boto3.client("glue", region_name=context.resource_config["region"])


@resource(
    config_schema={
        "account_id": Field(String, default_value="YOUR_AWS_ACCOUNT_ID"),
        "region": Field(String, default_value="us-east-1"),
    }
)
def aws_athena_resource(context):
    """Athena client resource."""
    return boto3.client("athena", region_name=context.resource_config["region"])


@resource(
    config_schema={
        "account_id": Field(String, default_value="YOUR_AWS_ACCOUNT_ID"),
        "region": Field(String, default_value="us-east-1"),
    }
)
def aws_lambda_resource(context):
    """Lambda client resource."""
    return boto3.client("lambda", region_name=context.resource_config["region"])


# Task Ops


@op(
    required_resource_keys={"aws_s3_resource"},
)
def create_bucket(context):
    """Execute aws.s3.ensure_bucket."""
    logger.info("Executing: aws.s3.ensure_bucket")
    params = {
        "bucket": "financial-data-lake-{{account_id}}",
        "region": "us-east-1",
        "versioning": true,
        "encryption": "AES256",
    }

    # Execute provider action
    s3_client = context.resources.aws_s3_resource
    bucket = params.get("bucket")
    if bucket:
        s3_client.create_bucket(Bucket=bucket)
        logger.info(f"Created S3 bucket: {bucket}")

    return {"status": "success", "task_id": "create_bucket"}


@op(
    ins={"create_bucket": In()},
    required_resource_keys={"aws_glue_resource"},
)
def create_database(context):
    """Execute aws.glue.ensure_database."""
    logger.info("Executing: aws.glue.ensure_database")
    params = {"database": "financial_analytics", "description": "Financial analytics data catalog"}

    # Execute provider action
    glue_client = context.resources.aws_glue_resource
    database = params.get("database")
    if database:
        try:
            glue_client.create_database(DatabaseInput={"Name": database})
            logger.info(f"Created Glue database: {database}")
        except glue_client.exceptions.AlreadyExistsException:
            logger.info(f"Database already exists: {database}")

    return {"status": "success", "task_id": "create_database"}


@op(
    ins={"create_database": In()},
    required_resource_keys={"aws_glue_resource"},
)
def create_transactions_table(context):
    """Execute aws.glue.ensure_table."""
    logger.info("Executing: aws.glue.ensure_table")
    params = {
        "database": "financial_analytics",
        "table": "transactions",
        "s3_location": "s3://financial-data-lake-{{account_id}}/transactions/",
        "format": "parquet",
        "schema": {
            "columns": [
                {"name": "transaction_id", "type": "string"},
                {"name": "customer_id", "type": "string"},
                {"name": "amount", "type": "double"},
                {"name": "currency", "type": "string"},
                {"name": "timestamp", "type": "timestamp"},
                {"name": "category", "type": "string"},
            ],
            "partition_keys": [
                {"name": "year", "type": "int"},
                {"name": "month", "type": "int"},
                {"name": "day", "type": "int"},
            ],
        },
    }

    # Execute provider action
    glue_client = context.resources.aws_glue_resource
    database = params.get("database")
    if database:
        try:
            glue_client.create_database(DatabaseInput={"Name": database})
            logger.info(f"Created Glue database: {database}")
        except glue_client.exceptions.AlreadyExistsException:
            logger.info(f"Database already exists: {database}")

    return {"status": "success", "task_id": "create_transactions_table"}


@op(
    ins={"create_transactions_table": In()},
    required_resource_keys={"aws_athena_resource"},
)
def run_daily_summary(context):
    """Execute aws.athena.execute_query."""
    logger.info("Executing: aws.athena.execute_query")
    params = {
        "database": "financial_analytics",
        "query": "SELECT category, SUM(amount) as total_amount, COUNT(*) as transaction_count FROM transactions WHERE year = YEAR(CURRENT_DATE) AND month = MONTH(CURRENT_DATE) AND day = DAY(CURRENT_DATE) GROUP BY category",
        "workgroup": "primary",
        "output_location": "s3://financial-data-lake-{{account_id}}/results/daily_summary/",
    }

    # Execute provider action
    athena_client = context.resources.aws_athena_resource
    query = params.get("query")
    database = params.get("database", "default")
    if query:
        response = athena_client.start_query_execution(
            QueryString=query,
            QueryExecutionContext={"Database": database},
            ResultConfiguration={
                "OutputLocation": params.get("outputLocation", "s3://athena-results/")
            },
        )
        logger.info(f"Started Athena query: {response['QueryExecutionId']}")

    return {"status": "success", "task_id": "run_daily_summary"}


@job(
    resource_defs={
        "aws_s3_resource": aws_s3_resource,
        "aws_glue_resource": aws_glue_resource,
        "aws_athena_resource": aws_athena_resource,
        "aws_lambda_resource": aws_lambda_resource,
    },
    description="Financial Analytics Pipeline",
)
def financial_analytics_job():
    """Financial Analytics Pipeline workflow."""
    create_bucket()
    create_database(create_bucket)
    create_transactions_table(create_database)
    run_daily_summary(create_transactions_table)


# Schedule
financial_analytics_schedule = ScheduleDefinition(
    job=financial_analytics_job,
    cron_schedule="0 2 * * *",
)


# Repository
@repository
def financial_analytics_repository():
    """Dagster repository for financial_analytics."""
    return [
        financial_analytics_job,
        financial_analytics_schedule,
    ]
