"""
FLUID Generated DAG: Financial Analytics Pipeline

Contract ID: financial_analytics
Schedule: 0 2 * * *
Timezone: UTC
AWS Account: YOUR_AWS_ACCOUNT_ID
AWS Region: us-east-1

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: 2026-01-30T14:02:10.320788
"""

import json
import logging
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.operators.athena import AthenaOperator
from airflow.providers.amazon.aws.operators.glue import GlueJobOperator
from airflow.providers.amazon.aws.operators.lambda_function import LambdaInvokeFunctionOperator
from airflow.providers.amazon.aws.operators.redshift_data import RedshiftDataOperator
from airflow.providers.amazon.aws.operators.s3 import S3CreateBucketOperator

logger = logging.getLogger(__name__)


def _ensure_glue_database(**kwargs):
    return kwargs


def _ensure_glue_table(**kwargs):
    return kwargs


# Default DAG arguments
default_args = {
    "owner": "fluid-forge",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
}

# DAG definition
dag = DAG(
    dag_id="financial_analytics",
    default_args=default_args,
    description="Financial Analytics Pipeline",
    schedule_interval="0 2 * * *",
    start_date=datetime(2026, 1, 1, tzinfo=ZoneInfo("UTC")),
    catchup=False,
    tags=["fluid", "auto-generated", "financial_analytics"],
)

# Task definitions
create_bucket = S3CreateBucketOperator(
    task_id="create_bucket",
    bucket_name="financial-data-lake-{{account_id}}",
    region_name="us-east-1",
    aws_conn_id="aws_default",
    dag=dag,
)

create_database = PythonOperator(
    task_id="create_database",
    python_callable=lambda: _ensure_glue_database(
        database="financial_analytics", region="us-east-1"
    ),
    dag=dag,
)

create_transactions_table = PythonOperator(
    task_id="create_transactions_table",
    python_callable=lambda: _ensure_glue_table(
        database="financial_analytics",
        table="transactions",
        params={
            "database": "financial_analytics",
            "table": "transactions",
            "s3_location": "s3://financial-data-lake-{{account_id}}/transactions/",
            "format": "parquet",
            "schema": {
                "columns": [
                    {"name": "transaction_id", "type": "string"},
                    {"name": "customer_id", "type": "string"},
                    {"name": "amount", "type": "double"},
                    {"name": "currency", "type": "string"},
                    {"name": "timestamp", "type": "timestamp"},
                    {"name": "category", "type": "string"},
                ],
                "partition_keys": [
                    {"name": "year", "type": "int"},
                    {"name": "month", "type": "int"},
                    {"name": "day", "type": "int"},
                ],
            },
        },
        region="us-east-1",
    ),
    dag=dag,
)

run_daily_summary = AthenaOperator(
    task_id="run_daily_summary",
    query="SELECT category, SUM(amount) as total_amount, COUNT(*) as transaction_count FROM transactions WHERE year = YEAR(CURRENT_DATE) AND month = MONTH(CURRENT_DATE) AND day = DAY(CURRENT_DATE) GROUP BY category",
    database="financial_analytics",
    output_location="s3://aws-athena-query-results-YOUR_AWS_ACCOUNT_ID-us-east-1/",
    aws_conn_id="aws_default",
    dag=dag,
)

# Task dependencies
create_bucket >> create_database
create_database >> create_transactions_table
create_transactions_table >> run_daily_summary
